### PR TITLE
Support annotating sorts of contributions

### PR DESCRIPTION
**Pull request by hexylena**
This adds a new field `contributions` which is analogous to `contributors`, except now it's a map instead of a list which supports the following categories: Authorship, Editing, Testing, UI/UX design (mostly for gtn itself), Infrastructure (mostly for gtn itself/recognising sysads), Funding.

fixes https://github.com/galaxyproject/training-material/issues/2015

Simply swap the key, and annotate the existing list with their contributions:

```diff
-contributors:
+contributions:
+  authorship:
   - carpentries
+  editing:
   - bebatut
   - fpsom
   - tobyhodges
+  funding:
   - erasmusplus
```

image

Or in a tutorial (the poor spacing is due to the overview box, not the list.
The individual categories are annotated with what that contribution implies

image

This does not affect existing tutorials and is an opt-in upgrade:

image

### CODE REVIEW

**Comment by hexylena** [comment]
Moved to end (a la real papers) @shiltemann.

image

**Comment by hexylena** [comment]
image

Now includes contributor profile icons

**Comment by hexylena** [comment]
TODOs:

- [ ] move funding into separate field, it shouldn't get rendered with contributors
- [ ] slides
- [ ] slides-plain
- [ ] re-unify contributors again

**Comment by hexylena** [comment]
fixed the conflict @shiltemann

**Comment by bebatut** [comment]
It looks really interesting.
Just a quick question. Is the funding before the feedback? Could it be after? so people do not miss the feedback form

**Comment by hexylena** [comment]
it is after feedback, no worries. Didn't want to take away from that!

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
thanks @hexylena!

**Pull request merged**
