### PR TITLE
Support level metadata

### PR DESCRIPTION
**Pull request by bebatut**
As discussed in #1289, this PR adds an extra possible metadata to the tutorial: level ("Introductory" / "Intermediate" / "Advanced")

- Display on the topic page
 
    screenshot 2019-03-04 at 18 37 38

    screenshot 2019-03-04 at 18 41 12

- Update the tutorial documentation
- Update the front validator to check the value
- Add bioschema annotation

### CODE REVIEW

**Comment by erasche** [comment]
Awesome :)

Have you tried displaying them with the same styling as the tags? (But maybe with a different colour like blue to indicate it's a different kind of tag?) That might save us some vertical space

**Comment by shiltemann** [comment]
I wonder if we could do some kind of visual difficulty indicator, a bit like the way chilipepper icons are used to indicate spiciness level on menus? ..but maybe we replace it with graduation cap icons orso? 

made a super quick mock-up:
 
image

**Comment by bebatut** [comment]
I love your idea @shiltemann

**Comment by nsoranzo** [comment]
@shiltemann Nice! Other possible inspirations:

https://images.app.goo.gl/M1APvtFHjCFQbt2z8

and

https://images.app.goo.gl/j3gY6cixU8uQAVRMA

**Comment by erasche** [comment]
@nsoranzo we discussed exactly that first image haha, @shiltemann and I rationalised that it might be hard to find icons for that, whereas we have the graduation cap icons already.

**Comment by shiltemann** [comment]
ok, I pushed an implementation of the above idea, along with displaying it in the overview box at top of the tutorial:

image

(but am happy to change/adapt if we want to do something different orso)

**Pull request merged**
