### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by erxleben**
additional comments:
- line 119: parameter is called Logistic Regression
- line 121 and 125: (as tabular) is shown as selection
- line 249: Nearest Neighbor Class. tool in Statistics has different parameters to select (wrong ones for this tutorial). NNC in ML section is the right one

### CODE REVIEW

**Comment by bgruening** [comment]
@anuprulez @khanteymoori ...

**Comment by anuprulez** [comment]
Thanks @erxleben. Looks ok to me

**Comment by khanteymoori** [comment]
Thanks to @erxleben 
we have two NN, the right one is in Machine Learning part.
Logistic Regression <----- Logistic Regression model, in the new version
and maybe I remove the extract parameters part,  because the new Pipeline builder tool creates both of the model and parameters.
I will apply the changes

**Comment by khanteymoori** [comment]
I have applied additional comments in this PR: https://github.com/galaxyproject/training-material/pull/1929

**Pull request merged**
