### PR TITLE
image 10

### PR DESCRIPTION
**Pull request by Swathi266**
TODO: Describe your changes here..

### CODE REVIEW

**Review by Swathi266 — COMMENTED** [review]
Image after running velvetg in the tutorial - https://training.galaxyproject.org/training-material/topics/assembly/tutorials/general-introduction/tutorial.html
Contigs file

**Comment by bgruening** [comment]
@Swathi266 you need to embed this image somewhere? The image name could also be adopted, currently it contains spaces and two times `png`

**Comment by Swathi266** [comment]
Hello @bgruening 
I would like to replace the current tutorial image number 10 with the image I suggested.

**Comment by shiltemann** [comment]
@Swathi266 I also updated the filename here to replace the original. I am not so familiar with this tutorials so I cannot judge if this is correct, but maybe @AnnaSyme can have a look.

**Comment by Swathi266** [comment]
Thank you @shiltemann

**Review by shiltemann — APPROVED** [review]

**Comment by Swathi266** [comment]
Thank you @bgruening @shiltemann @AnnaSyme

**Pull request merged**
