### PR TITLE
Metatranscriptomics tutorial

### PR DESCRIPTION
**Pull request by subinamehta**

### CODE REVIEW

**Comment by bebatut** [comment]
As discussed with @subinamehta, I worked on the tutorial:

- I generated a new input dataset (from T1A) with more sequences: I tried to conserve the same taxonomic diversity as in the original dataset but also similar proportion of sequences removed/conserved at each steps
- I added more information and explanation for each steps, but try to show how to interpret the outputs via questions

This tutorial is ready for review. @subinamehta, @PratikDJagtap, @jraysajulga, @shiltemann?

In the meantime, I am running the full workflow on the other time points and replicates of the original dataset. The idea would be to have a second tutorial with comparative analysis (there is already a draft in this PR).

**Comment by PratikDJagtap** [comment]
Hello Bérénice,

Thanks for updating the tutorial. I had a look a brief look at it - and it
looks great! Thanks for your and Subina's work on this. We will review it
in details and send you feedback. Once ready, I think it will be a good
idea to publish the tutorial as a manuscript. We are still waiting to hear
from ABRF if the proposal will be accepted as a workshop. If we do hear
something positive - we will be ready!

I like the idea of comparative analysis of the large datasets - and thanks
for taking it on. Do you plan to use statistical analysis and visualization
outputs (PCA, heatmap, volcano plots) for interpretation? @Ray Sajulga
<rsajulga@umn.edu> had a few ideas/plans and it would be a good idea to
discuss at some point.
I have copied Tim and Praveen on this email so that they are in the loop.

Thanks again!

Cheers,
Pratik

Pratik Jagtap,

Research Assistant Professor,

Department of Biochemistry, Molecular Biology, and Biophysics, University
of Minnesota.

*Office:* 7-136 MCB, 420 Washington Ave SE, Minneapolis, MN 55455

*Phone: *612-816-4232

*Email: *pjagtap@umn.edu

*Shipping address: *6-155 Jackson Hall, 321 Church Street SE, Minneapolis,
MN 55455



http://galaxyp.org

**Comment by bebatut** [comment]
I moved the draft of the comparative tutorial to its own PR #1608.
This tutorial should be ready soonish. @shiltemann do you want to review it?

**Comment by subinamehta** [comment]
Thanks Berenice, I will also review that.

**Comment by shiltemann** [comment]
@bebatut @subinamehta yep, I will review this soon, thanks for all the hard work!

**Comment by shiltemann** [comment]
:tada::tada::tada: thanks so much!

**Pull request merged**
