### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by Ewran**
it was written as
"We expect that the replicates of the ChIP-seq experiments should be clustered more closely to each other than the replicates of the input samples.".
but I think replicates of the same samples clustered more closely to each other than replicates of different samples.
So it should be written as
"We expect that the replicates of the same samples (cell types) should be clustered more closely to each other than the replicates of the different samples.".

### CODE REVIEW

**Comment by willdurand** [comment]
Hi @malloryfreeberg, what do you think of these changes?

**Comment by malloryfreeberg** [comment]
The phrase "replicates of the different samples" doesn't make sense to me. If two experiments are from different samples, then they aren't replicates. 

A better wording would be: "We expect that replicate samples will cluster most closely to each other than to other samples." This sentence is the most conservative way of saying that we expect, for example, G1E Tal1 IP R1 to most closely cluster with G1E Tal1 IP R2, and not the G1E input replicates or the megakaryocyte Tal1 IP replicates or the megakaryoctye input replicates.

**Comment by Ewran** [comment]
Thank you so much @malloryfreeberg , @willdurand , I revised it again.

**Comment by willdurand** [comment]
thanks @Ewran!

**Pull request merged**
