### PR TITLE
update advanced cut tool

### PR DESCRIPTION
**Pull request by Marie59**
Small update to fill in correctly the Advanced cut tool according to its new version.

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
Do you need to update the worklow as well?

**Comment by Marie59** [comment]
> Do you need to update the worklow as well?

I am not sure I don't think it changes anything for the workflow in the end ...

**Comment by hexylena** [comment]
@Marie59 no, but bjoern is right, we like to the keep the version of the tool used in the workflow matching the tutorial itself. Could we trouble you to update the workflow as well to ensure it uses this same newer version of cut as well? :)

**Comment by Marie59** [comment]
It should be up to date now ;)

**Comment by hexylena** [comment]
Ah super!!

**Review by hexylena — APPROVED** [review]
Oh and even with some nice improvements! great to see :)

**Comment by Marie59** [comment]
as always I don't have the test :)

**Pull request merged**
