### PR TITLE
Update some tools in tuberculosis variant analysis tutorial

### PR DESCRIPTION
**Pull request by wm75**

### CODE REVIEW

**Comment by wm75** [comment]
@pvanheus the linter complains about the WF not specifying a creator and a license. I'm hesitant to add a license in particular since it's not my WF.

**Comment by pvanheus** [comment]
The WF was meant to be the steps of the tutorial itself. So can it fall under whatever license covers the tutorial?

**Comment by wm75** [comment]
The content of the tutorials is CC BY 4.0-licensed, but you could argue that workflows are "code" more than tutorial content, and for that MIT would be roughly the equivalent (and also what the repo here uses).

**Comment by pvanheus** [comment]
Ok then I'm happy to go with MIT license.

**Review by bgruening — APPROVED** [review]

**Pull request merged**
