### PR TITLE
Machine Learning: tour and workflow

### PR DESCRIPTION
**Pull request by polkhe**
- tour
- workflow
@bebatut

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @polkhe 
@anuprulez would have time to you check this tour and workflow?

**Comment by anuprulez** [comment]
@bebatut Ok, will have a look at it. Thanks

**Comment by anuprulez** [comment]
@bebatut I am not sure how to execute a tour. Clicking on any tour takes me to the checked-in `tour.yaml` file. Moreover, this link -
https://github.com/galaxyproject/training-material/tree/master/topics/statistics/tutorials/machinelearning/tours/
is broken.
@polkhe

**Comment by anuprulez** [comment]
ping @polkhe 

Thanks a lot for this work. I executed the workflow and it worked correctly. I have further comments on the tour:

step_open_upload

- When I reach the above step and do `Click on Paste/Fetch data` and then click `Next`, I get two blocks filled with the links to the datasets (shown below). But, when I just click on `Next` without doing `Click on Paste/Fetch data` it works fine. `Click on Paste/Fetch data` text is misleading I think.

step_start_upload

- When I reach the step "Train a classifier", the tour box seems to block the view of the tool. I am not sure if it is possible but a user should be able to drag this box to a conveninent area on the screen so that she/he can proceed with the toturial without having any view blocked by this box.

step_train

- Similar observation in step "Predict using trained model"

step_test

**Pull request merged**
