### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by anuprulez**

### CODE REVIEW

**Comment by bedroesb** [comment]
Hello @anuprulez 
Is it possible to change the data-library.yaml file to the latest format? regarding #1255 
for more information: https://galaxyproject.github.io/training-material/topics/contributing/tutorials/create-new-tutorial-technical/tutorial.html

**Comment by bebatut** [comment]
I moved all input datasets to one Zenodo repo (https://zenodo.org/record/2579649#.XHep39F7mL4) and created the corresponding data library (following the latest format)

I worked on the tutorial text: I split some hands-on sections into sub-steps and did some formatting.

@anuprulez can you check if my changes to the tutorial make sense? 
and the metadata in the Zenodo are sparse, should we add more information?
-

**Comment by bebatut** [comment]
@anuprulez what is the different between this PR and https://github.com/galaxyproject/training-material/pull/1128/files ?

**Comment by anuprulez** [comment]
@bebatut I will look at them tomorrow ... thank you for looking into it ... :)

**Comment by anuprulez** [comment]
@bebatut We should keep this PR and I will close the other one (https://github.com/galaxyproject/training-material/pull/1128). Moreover, this PR needs some work from my side. There are a couple of images I added - their colours are too strong (and I think they do not look good). I will need to do some formatting as well. I will do these changes, most probably next week. :)

Thanks!

**Comment by anuprulez** [comment]
@bebatut thanks for merging :)

**Comment by shiltemann** [comment]
awesome, thanks @anuprulez! :tada:

**Pull request merged**
