### PR TITLE
removed screenshots from tutorials and restructured hands-on from non-dip

### PR DESCRIPTION
**Pull request by polkhe**
variant-analysis/non-dip
@bebatut

### CODE REVIEW

**Comment by erasche** [comment]
Hey @wm75 would you have time to check this today during the co-fest?

**Comment by wm75** [comment]
This cannot get merged as is since some of the boxes replacing the images are insufficient.
I will work on completing them, and leave this PR open until I'm done.

**Comment by hexylena** [comment]
Sounds good @wm75, tagging as work-in-progress until then :)

**Comment by shiltemann** [comment]
@wm75 This PR is quite old, and has accumulated a fair number of conflicts now, what would you like to do with it? Happy to leave it open if still useful, but if not then maybe we close it?

**Comment by shiltemann** [comment]
@wm75 @polkhe my gentle annual reminder about this very old PR, let me know what you think, are you still willing and able to finish it? is it still relevant? should we close it? up to you, but let me know :)

**Comment by shiltemann** [comment]
looks like most of what this PR was aiming to do is already present in the main branch, so closing this. Thanks!

**Pull request closed without merging**
