### PR TITLE
Minor clarifications and consistency improvements for the ML RNN tutorial

### PR DESCRIPTION
**Pull request by afgane**
@kxk302 please take a look.

### CODE REVIEW

**Comment by kxk302** [comment]
> @kxk302 please take a look.

The changes look good to me. Thanks @afgane!

**Comment by shiltemann** [comment]
@kxk302 please feel free to approve and merge if you are happy!

**Review by kxk302 — APPROVED** [review]
Looks Good!

**Comment by kxk302** [comment]
> @kxk302 please feel free to approve and merge if you are happy!

Thanks @shiltemann!

**Pull request merged**
