### PR TITLE
use workflow listing to point to our new workflow pages

### PR DESCRIPTION
**Pull request by hexylena**
Screenshot 2024-11-15 at 13-21-19 Workflows _ Large genome assembly and polishing _ Assembly

simplifies the page and looks a bit cleaner

### CODE REVIEW

**Comment by nekrut** [comment]
Is this linked to IWC?

**Comment by hexylena** [comment]
nope, GTN workflows are disconnected from IWC workflows and infrastructure (they have different goals/audiences.) Any reason you're asking?

(if you want to use IWC workflows in GTN tutorials, please don't add them to the GTN, just [use one of these snippets to instruct users on how to launch IWC workflows](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#workflows))

**Comment by nekrut** [comment]
> nope, GTN workflows are disconnected from IWC workflows and infrastructure (they have different goals/audiences.) Any reason you're asking?
> 
> (if you want to use IWC workflows in GTN tutorials, please don't add them to the GTN, just [use one of these snippets to instruct users on how to launch IWC workflows](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#workflows))

I'm concerned with effort duplication.

**Comment by hexylena** [comment]
@lldelisle it will be live shortly :) (The workflow pages have existed since ~6 months, due to our WorkflowHub integration, but just took some time to get around to making them more visible.)

**Comment by lldelisle** [comment]
Thanks @hexylena

**Comment by hexylena** [comment]
https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/differential-isoform-expression/workflows/

i'm still not so happy with mermaid for rendering these very large graphs, but, I don't know how to fix that.

**Comment by lldelisle** [comment]
This one has frame comments, could this be integrated?
image

**Comment by hexylena** [comment]
(moving to another issue)

**Pull request merged**
