### PR TITLE
RNA-seq limma-voom tutorials: some more edits

### PR DESCRIPTION
**Pull request by mblue9**
One question, I've updated the Zenodo dataset for one of the tutorials how do I regenerate the data-library.yaml?

I tried `planemo training_fill_data_library --topic_name "transcriptomics" --tutorial_name "rna-seq-genes-to-pathways" --zenodo_link "https://zenodo.org/record/2596382"`

but got an error about title:
`/venvs/.venv/lib/python3.7/site-packages/planemo/training/utils.py", line 19, in init_from_dict
    self.title = dict['title']
KeyError: 'title'`

### CODE REVIEW

**Comment by bebatut** [comment]
The current version of Planemo is broken. I open a PR to fix it https://github.com/galaxyproject/planemo/pull/913
I deployed it locally for me. I can regenerate the data-library file if you want

**Comment by mblue9** [comment]
Ah I see, that would be great if you could generate the file. I was thinking I could do it manually if need be but don't know where to get the api urls e.g. `- url: https://zenodo.org/api/files/fd880772-78f5-48c7-8960-838ae2f7c496/limma-voom_basalpregnant-basallactate`

**Comment by bebatut** [comment]
To be sure, did you change the Zenodo link somewhere else than in `rna-seq-genes-to-pathways`?

**Comment by mblue9** [comment]
Nope just `rna-seq-genes-to-pathways`, thanks for making the file!

**Comment by bgruening** [comment]
Danke Maria!

**Pull request merged**
