### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by felicitas215**
Clarify Helixer's behavior when using a soft-masked or hard-masked genome

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks a lot @felicitas215! 

Can you add yourself to https://github.com/galaxyproject/training-material/blob/main/CONTRIBUTORS.yaml :)

Thanks!

**Comment by felicitas215** [comment]
Thank you too, Björn. It's really nice of you to give me the chance to be a contributer. I added myself to the list :).

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @felicitas215 !

**Comment by bgruening** [comment]
You also now have this page for you own: https://training.galaxyproject.org/training-material/hall-of-fame/felicitas215/

**Pull request merged**
