### PR TITLE
Updating my contact info in Contributors section

### PR DESCRIPTION
**Pull request by hujambo-dunia**
Related to this issue #5176 
Also, side note: I see this error on this PR `At least 1 approving review is required by reviewers with write access.` However, I do not seem to have permission to even add Reviewers (video below).

[Cc](https://github.com/galaxyproject/training-material/pull/5176#discussion_r1722013619): @teresa-m

### CODE REVIEW

**Comment by teresa-m** [comment]
> Related to this issue #5176 Also, side note: I see this error on this PR `At least 1 approving review is required by reviewers with write access.` However, I do not seem to have permission to even add Reviewers (video below).
> 
>  [  ](https://private-user-images.githubusercontent.com/3672779/359560568-23a22144-828d-473a-bde5-07f9a73ce408.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODg5MTMsIm5iZiI6MTcyNDE4ODYxMywicGF0aCI6Ii8zNjcyNzc5LzM1OTU2MDU2OC0yM2EyMjE0NC04MjhkLTQ3M2EtYmRlNS0wN2Y5YTczY2U0MDguZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMjExNjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI5NGFmM2I0YmQ4ZmQzODAxMmZkYmM5NzQwZmI5NjEzZGMxN2Q2YzNmNDcyZjQ4ZDQ0MmNiOGU2Mjk2MDQ5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bo-uNCGqLeBv9C57zuLIeNjkLEV6h_btRSUguAA2k04) [ ](https://private-user-images.githubusercontent.com/3672779/359560568-23a22144-828d-473a-bde5-07f9a73ce408.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODg5MTMsIm5iZiI6MTcyNDE4ODYxMywicGF0aCI6Ii8zNjcyNzc5LzM1OTU2MDU2OC0yM2EyMjE0NC04MjhkLTQ3M2EtYmRlNS0wN2Y5YTczY2U0MDguZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMjExNjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI5NGFmM2I0YmQ4ZmQzODAxMmZkYmM5NzQwZmI5NjEzZGMxN2Q2YzNmNDcyZjQ4ZDQ0MmNiOGU2Mjk2MDQ5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bo-uNCGqLeBv9C57zuLIeNjkLEV6h_btRSUguAA2k04)
> 
> [Cc](https://github.com/galaxyproject/training-material/pull/5176#discussion_r1722013619): @teresa-m

@hujambo-dunia:
Reviewers will be always assigned automatically. Or you just ping someone specifically to get this person to review. 
Not sure if this solves your concerns. 
Maybe @shiltemann or @hexylena can give you a reason why this is the case.

**Review by teresa-m — APPROVED** [review]
Thanks for adding details.

**Comment by bgruening** [comment]
It's not an error imho, this is normal GitHub behaviour. You only can assign reviewers to a PR if you have certain permissions.

**Comment by hujambo-dunia** [comment]
@bgruening ok - sounds good

**Pull request merged**
