### PR TITLE
Update dev slides

### PR DESCRIPTION
**Pull request by cmonjeau**

### CODE REVIEW

**Comment by bgruening** [comment]
@cmonjeau great work. Please ping me if you don't have any pending changes!

**Comment by cmonjeau** [comment]
Hi @bgruening @abretaud 

I tried to fix travis errors and there are some 'time out' when it checks some URLs

` got a time out (response code 303)`

Any ideas?

**Comment by cmonjeau** [comment]
Oh it's ok now. Thanks @abretaud for relaunching travis.

**Comment by willdurand** [comment]
@cmonjeau thanks, I still see the source map files though.

**Comment by cmonjeau** [comment]
Hi @bgruening @willdurand. Thanks for the review.

I added these files because on firefox, I've an error without them.

> Server running... press ctrl-c to stop.
> [2018-02-09 08:05:50] ERROR `/training-material/assets/css/bootstrap.min.css.map' not found.
> 

I don't understand why we should delete them... :(

**Comment by bgruening** [comment]
@cmonjeau works for me locally. Can you run `make build` again?

**Comment by cmonjeau** [comment]
Hi @bgruening ,

It seems to work after the build. I forgot about that stage.  Sorry

**Comment by bgruening** [comment]
No problem. Thanks a lot for your contributions!

**Pull request merged**
