### PR TITLE
Updated EBI input tutorial 

### PR DESCRIPTION
**Pull request by wee-snufkin**
Minor updates:
- fixed renaming the columns
- updated history and workflow
- workflow tests added

### CODE REVIEW

**Comment by wee-snufkin** [comment]
Hmm, the tests don't produce .yml file or anything in the test-data folder...

**Comment by pavanvidem** [comment]
Tested it and works well. I don't understand the error. The `-test.yml` file exists. @hexylena  is it something to do with the parentheses in the workflow name?

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
Yep, linting issue was down to trying to find files with that extension, I used `.grep()` and failed to escape the filename first.

**Review by pavanvidem — COMMENTED** [review]
Good to go!! Thanks @wee-snufkin

**Review by pavanvidem — APPROVED** [review]

**Pull request merged**
