### PR TITLE
Choose your Own Adventure by @hexylena

### PR DESCRIPTION
**Pull request by lldelisle**
I just cherry-pick some commits from @hexylena on PR #3330 to make an independent PR.
I don't know if it was the good way to do it...

### CODE REVIEW

**Comment by lldelisle** [comment]
For sure, if we split, this PR needs to be merged before mine... For reviewers, it may be easier to first merge this PR and then review mine, I don't know.

**Comment by hexylena** [comment]
I'll use this PR to fix the failing test, and then I'll merge it. Thanks @lldelisle :)

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
@beatrizserrano I fixed the lint yaml metadata check here.

**Comment by lldelisle** [comment]
Thanks,
For PR #3330, once this PR is merged, should I run `git pull upstream main` on my local branch or `git pull --rebase upstream main`?

**Comment by hexylena** [comment]
I usually do something like

```
git checkout main
git pull upstream main
git checkout update_ref_based_RNAseq
git rebase main
```

**Comment by nsoranzo** [comment]
Which is equivalent to `git pull --rebase upstream main` ;)

**Comment by lldelisle** [comment]
In fact, this does not work if you already pushed to github. At least, for me it did not worked. So I needed to do:
`git pull upstream main` (in merge mode).

**Comment by nsoranzo** [comment]
You just need to run `git push --force` to overwrite the commits on your `origin` remote.

**Comment by lldelisle** [comment]
Thanks for the tip

**Comment by hexylena** [comment]
cheers @nsoranzo

**Pull request merged**
