### PR TITLE
mapping-by-sequencing tutorial: add workflow

### PR DESCRIPTION
**Pull request by wm75**

### CODE REVIEW

**Comment by bgruening** [comment]
@erasche this workflow is working on our server, would be a nice first target for testing.

**Comment by bgruening** [comment]
@wm75 you need to change this here: https://github.com/wm75/training-material/blob/a14e0a4b74829330dd99f3f82a0d2320c756b0e9/topics/variant-analysis/metadata.yaml#L91 to true.

**Comment by bgruening** [comment]
Yes, probably.

**Comment by bebatut** [comment]
Thanks @wm75

**Pull request merged**
