### PR TITLE
Metabolomics lcms preprocess

### PR DESCRIPTION
**Pull request by lecorguille**
Here will be our ([the W4M project](http://workflow4metabolomics.org/)) first contribution to the GTN 

Those materials are direct translation of Jean-François Martin(@jfrancoismartin) slides in GTN

### CODE REVIEW

**Comment by lecorguille** [comment]
It's just a first PR to know if the template is good.
And it looks that it's not the case :)

**Comment by bgruening** [comment]
@lecorguille are you joining the train the trainer and help us to merge this ;)

**Comment by lecorguille** [comment]
Unfortunatly, it's just a skeleton. I have excepted to work on that during
the Hackthon :/
Sure this summer, it will grow :)


Le mer. 28 juin 2017 à 01:00, Björn Grüning <notifications@github.com> a
écrit :

**Comment by bernt-matthias** [comment]
Hi there. A colleague and me would like to give a W4M tutorial in February. Maybe we could contribute to the tutorial. I guess we could do most on the LC/MS part. Any suggestions?

**Comment by bgruening** [comment]
@lecorguille @bernt-matthias any process on this one? We would like to mention metabolomics as part of the GTN :)

**Comment by bernt-matthias** [comment]
@bgruening unfortunatelly I'm out of time at the moment

**Comment by lecorguille** [comment]
So I am!

Concerning the preprocessing LC/MS: currently, I'm working on the update of the wrappers to XCMS3. It changes a lot the functions and options names. There should be some changes in the graphics too. So I guess I will wait for this version before writing a tutorial. The slides are almost finish for XCMS1.x but they have to be read. 

About the rest of the workflow (normalisation, quality checking, statistics, annotation) and about the other worlflows (GC/MS, FIA/MS, NMR), unfortunately, so far, I didn't manage to motivate the group :(

**Comment by erasche** [comment]
Hi @lecorguille, we [changed the way metadata works](https://github.com/galaxyproject/training-material/pull/966) in the repository, so I updated your PR accordingly, metadata is now at the top of the slides.html/tutorial.md files.

**Comment by erasche** [comment]
Hi @lecorguille is this still relevant with https://github.com/galaxyproject/training-material/pull/958 ?

**Comment by erasche** [comment]
Sure @lecorguille!

**Pull request closed without merging**
