### PR TITLE
Reshape AMR detection tutorials and prepare learning pathway for AMR detection

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I reshaped the existing AMR detection tutorial and split it between assembly and AMR detection.
The second part was added as a new tutorial in genome-annotation.

To connect everything, I started a learning pathway.

This PR is a start. More tutorials will be added in the near future in other PR

### CODE REVIEW

**Review by pimarin — APPROVED** [review]
Okay for me !
Thanks @bebatut !

**Comment by hexylena** [comment]
> This workflow has a creator but is missing an identifier for them. Please ensure all creators have valid ORCIDs

we can approve in spite of this, from our side just intending to be a "nudge" to improve the data quality, but 

```
* At ./_site/training-material/topics/genome-annotation/tutorials/amr-gene-detection/tutorial.html:1447:

  'a' tag is missing a reference

For the Links > Internal check, the following failures were found:

* At ./_site/training-material/learning-pathways/amr-gene-detection.html:540:

  internally linking to /training-material/NO%20LINK, which does not exist
```

these look more real.

**Comment by bebatut** [comment]
> * At ./_site/training-material/topics/genome-annotation/tutorials/amr-gene-detection/tutorial.html:1447:
>
> 'a' tag is missing a reference

I am not sure where the `a` tag is missing a reference

**Comment by hexylena** [comment]
```
1435   <p>If you already ran <strong>Bakta</strong> on your contigs (maybe after another <a href="">tutorial</a>), you can just upload here the GFF generated by <strong>Bakta</strong>.</p>                      
```

**Comment by hexylena** [comment]
Pushed a commit with a linter error for it :)

**Comment by bebatut** [comment]
Thanks @hexylena and @bgruening for the help and merge!

**Pull request merged**
