### PR TITLE
new tour for chipseq

### PR DESCRIPTION
**Pull request by polkhe**
added tour for _chipseq: estrogen receptor binding site identification_

### CODE REVIEW

**Comment by bebatut** [comment]
@vivekbhr @fidelram can you check if the content of this tour is correct? Thanks a lot! You can use the Galaxy Tourbuilder web-browser extension (Firefox, Chrome) to test it on any Galaxy instance :)

**Comment by bebatut** [comment]
@fidelram did you test it? Can we merge it?

**Comment by fidelram** [comment]
@bebatut sorry I just noticed this. Looks ok to me

**Comment by bebatut** [comment]
Thanks @fidelram for checking it!

**Pull request merged**
