### PR TITLE
Lecture 4 for genomics course...

### PR DESCRIPTION
**Pull request by nekrut**
practical intro into lists and dicts

### CODE REVIEW

**Comment by hexylena** [comment]
Reproducing my query from last time, to extract an answer before I will click approve :)

> @nekrut would you like to nominate one of your own staff to be responsible for this? we can ensure they have powers to merge things, and you can ping them directly.

**Comment by bgruening** [comment]
@hexylena no worries. We try to review those.

**Review by bgruening — APPROVED** [review]

**Comment by hexylena** [comment]
@bgruening no, don't. stop. seriously.

we need more Americans involved in this, he has plenty of staff that should at least be cross trained on this. 

you merging it just papers over the underlying problem. I don't want that.

**Comment by bgruening** [comment]
> we need more Americans involved in this, he has plenty of staff that should at least be cross trained on this. It would be better for the long term health of the community, you want that too, no?

Sure, that would be nice. But we (Freiburg) also have an interest in those lectures and I discussed with Anton to help as much as I can. Happy to discuss this further with you, but I think this can go in now.

**Pull request merged**
