### PR TITLE
Add support for automatic RMarkdown output

### PR DESCRIPTION
**Pull request by hexylena**
Just like the Jupyter notebook output, except now it's RMarkdown! We've not gone the route of hardcoding all the HTML here since sometimes people like to read the RMd file itself, so we've made an attempt to make that still readable despite tip/question/etc classes. Those will of course still render better in the HTML output of the RMarkdown processing pipeline, but, oh well.

Now the R tutorials are available in both RStudio/RMarkdown + Jupyter Notebooks. Fantastic!

image

Some Screenshots

Metadata | Boxes | Q&A + Nice Tables
--- | --- | ---
screenshot of header of Rmarkdown document showing nice metadata like author, date, table of contents, etc. | image of a tip box in the tutorial | screenshot of a Q&A nested box as well as the nice table viewer

Done in support of https://github.com/gallantries/organisation/issues/21

### CODE REVIEW

**Comment by hexylena** [comment]
Ready to test if anyone would like to

- Check out this branch
- Go to the R tutorial
- Follow the instructions in the header box and see if it all works.

**Review by shiltemann — COMMENTED** [review]
This is currently missing "what to do next" now that you've got it in RStudio. Bslib is missing, perhaps remove the theme?

Perhaps you could structure it as two tip boxes:
- how to run this in rstudio (running cell by cell)
- How to knit to HTML
and then authors could choose between them, which is appropriate for their tutorial?

Please also change `jupyter` to `rstudio` in the current how-to-run box

**Comment by hexylena** [comment]
Now available as a big ol hand-on block at the top of the tutorial.
image

I've just left the knitting as an FAQ, not part of the tutorial. I suspect that'll be nicer since it's not relevant most of the time.

The rest of the review comments have been addressed, thanks @shiltemann

**Comment by hexylena** [comment]
@shiltemann this is ready for review whenever. Specifically can you test:

- when you download a jupyter notebook, does it run ok (I've replaced `notedown` with a custom notebook conversion algorithm)
- when you download an RMarkdown file
	- are the instructions clear enough on how to use the rmarkdown notebook?
	- can you run the cells and see outputs / does it work (also a custom algorithm)

**Review by shiltemann — APPROVED** [review]

**Pull request merged**
