### PR TITLE
Fixes to single-cell training material

### PR DESCRIPTION
**Pull request by mtekman**
Updates to slides, trainings based on suggestions.

Thanks for the review @astrovsky01 !

### CODE REVIEW

**Comment by mtekman** [comment]
@bgruening I'm getting "The command "make install" failed and exited with 2"  with Travis

**Comment by bgruening** [comment]
restarted, this was fixed by @shiltemann and @erasche

**Comment by mtekman** [comment]
thanks @erasche @shiltemann !

**Comment by bgruening** [comment]
Danke.

**Pull request merged**
