### PR TITLE
add emoji flags to translations

### PR DESCRIPTION
**Pull request by martenson**
not sure what flag can Arabic have

### CODE REVIEW

**Comment by martenson** [comment]
A_short_introduction_to_Galaxy

**Comment by bebatut** [comment]
At the beginning we wanted to use flags also. But we were not sure because many countries speak one language and how to choose.
I do not know what de should do

**Comment by nsoranzo** [comment]
> At the beginning we wanted to use flags also. But we were not sure because many countries speak one language and how to choose.

Agreed, it's a can of worms :-1:

**Comment by martenson** [comment]
I see it as more useful, but have no horse here. What about we include francais|اللغة العربية|日本語 next to the code?

**Comment by lyoussar** [comment]
I found the flag attached for Arabic language is appropriate.
Did anyone started the translation to Arabic language?
arabic

**Comment by martenson** [comment]
We have decided flags are not good enough representation and will implement native language name tags instead. Thanks for contributions.

**Pull request closed without merging**
