### PR TITLE
Update An introduction to get started in genome assembly and annotation (update 2)

### PR DESCRIPTION
**Pull request by alexcorm**
Minor changes (typo and picture update) and add key points

### CODE REVIEW

**Review by hexylena — COMMENTED** [review]
I can't comment on image changes in the github UI so writing it here:

1. Did you make the updated image yourself? (Just asking because reverse image search isn't showing anything / want to make sure we aren't distributing a copyright image)
2. This is a strictly better image, could you remove `images/fastq_format.png`

**Comment by alexcorm** [comment]
> I can't comment on image changes in the github UI so writing it here:
> 
>     1. Did you make the updated image yourself? (Just asking because reverse image search isn't showing anything / want to make sure we aren't distributing a copyright image)

The image came from Hosseini, M., Pratas, D. & Pinho, A. J. A Survey on Data Compression Methods for Biological Sequences. Information 7, 56 (2016). The article is cited as reference in slides for fasta, fastq and bam/sam format.

> 
>     2. This is a strictly better image, could you remove `images/fastq_format.png`

Yes! Do I make a copy of the new `fastq_format.png` in `images` or a symlink from `images/genome_assembly_introduction`?

**Comment by hexylena** [comment]
> This is an open access article distributed under the [Creative Commons Attribution License](https://creativecommons.org/licenses/by/4.0/) which permits unrestricted use, distribution, and reproduction in any medium, provided the original work is properly cited.

Ok, that's fantastic, it works for us then. Could you please add a `slides.bib` file next to the slides.html, with the article's citation

```
@article{datacompression2016, title={A Survey on Data Compression Methods for Biological Sequences}, volume={7}, ISSN={2078-2489}, url={http://dx.doi.org/10.3390/info7040056}, DOI={10.3390/info7040056}, number={4}, journal={Information}, publisher={MDPI AG}, author={Hosseini, Morteza and Pratas, Diogo and Pinho, Armando}, year={2016}, month={Oct}, pages={56} }
```

and then include `Image licensed CC-BY 4.0 {% cite datacompression2016 %}` below the image when it's used on a slide? Just to make sure we're completely safe :)

**Comment by hexylena** [comment]
> Yes! Do I make a copy of the new fastq_format.png in images or a symlink from images/genome_assembly_introduction?

It _looks_ like `images/fastq_format.png` is completely unused throughout the GTN, please just delete that file then. No other changes needed!

**Comment by alexcorm** [comment]
@hexylena Done ;)

**Comment by hexylena** [comment]
Thanks so much @alexcorm !

**Pull request merged**
