### PR TITLE
Update zenodo for chip seq xi

### PR DESCRIPTION
**Pull request by erasche**
Per a user complaint, cc @bgruening

### CODE REVIEW

**Comment by bgruening** [comment]
Awesome, we ping jekyll to <4, which gets installed, but something is pulling in jekyll-4 just a few lines later https://travis-ci.org/galaxyproject/training-material/jobs/577850831#L1451

**Comment by bebatut** [comment]
It seems like there is again a conflict between the gem dependencies. I am investigating

**Comment by bgruening** [comment]
@bebatut it seem we are not using the lock file, can this be?

**Comment by bebatut** [comment]
we are not using the lock file on Travis, just for Heroku

**Pull request merged**
