### PR TITLE
Add author info

### PR DESCRIPTION
**Pull request by yezhengSTAT**

### CODE REVIEW

**Comment by shiltemann** [comment]
Welcome @yezhengSTAT! If there are specific tutorials or slides you helped out with, could you also put your username in the metadata at the top of those files? Then you will be listed as a contributor there as well :)

or, if you haven't contributed yet but would like to start doing so, please let us know how we can help with that!

**Comment by yezhengSTAT** [comment]
> Welcome @yezhengSTAT! If there are specific tutorials or slides you helped out with, could you also put your username in the metadata at the top of those files? Then you will be listed as a contributor there as well :)
> 
> or, if you haven't contributed yet but would like to start doing so, please let us know how we can help with that!

Hello,
Thanks for offering help! I am learning about how to contribute a new tutorial for our collaborated project. I have just gone through the galaxy tutorial about "creating a new tutorial" and found a few issues that I cannot handle. For example, when running the website locally, it always generate error messages like the following on my MacBook. I tried on another MacBook and ended up with the same problem. Is there any google group or forum where I can check if other new users have similar issue and may find solution there.

```
Error? Could not find any relevant pages for climate
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
  Liquid Exception: undefined method `[]' for nil:NilClass in /_layouts/tutorial_hands_on.html
             Error: undefined method `[]' for nil:NilClass
             Error: Run jekyll build --trace for more information.
```

Thanks,
Ye

**Comment by yezhengSTAT** [comment]
> > Welcome @yezhengSTAT! If there are specific tutorials or slides you helped out with, could you also put your username in the metadata at the top of those files? Then you will be listed as a contributor there as well :)
> > or, if you haven't contributed yet but would like to start doing so, please let us know how we can help with that!
> 
> Hello,
> Thanks for offering help! I am learning about how to contribute a new tutorial for our collaborated project. I have just gone through the galaxy tutorial about "creating a new tutorial" and found a few issues that I cannot handle. For example, when running the website locally, it always generate error messages like the following on my MacBook. I tried on another MacBook and ended up with the same problem. Is there any google group or forum where I can check if other new users have similar issue and may find solution there.
> 
> ```
> Error? Could not find any relevant pages for climate
>            Warning: Empty `slug` generated for ''.
>            Warning: Empty `slug` generated for ''.
>   Liquid Exception: undefined method `[]' for nil:NilClass in /_layouts/tutorial_hands_on.html
>              Error: undefined method `[]' for nil:NilClass
>              Error: Run jekyll build --trace for more information.
> ```
> 
> Thanks,
> Ye

I was able to find the solution on GITTER!! That seems to be a very good resources!

**Comment by shiltemann** [comment]
@yezhengSTAT great! glad you solved it :) let me know (here, or on Gitter) if you have any other questions or run into any other issues, and thanks a lot for contributing!!

**Comment by yezhengSTAT** [comment]
> @yezhengSTAT great! glad you solved it :) let me know (here, or on Gitter) if you have any other questions or run into any other issues, and thanks a lot for contributing!!

Hello,
I was able to generate a local tutorial website. However, my collaborators want to know if there is any method to leave question on the tutorial or open a discussion about certain analysis or certain processing step? That becomes critical for our tutorial.

Thanks,
Ye

**Comment by bgruening** [comment]
@yezhengSTAT under every tutorial is a feedback form. In Addition we recommend users of the GTN material to join our gitter chat to ask questions if they have problems.

**Comment by hexylena** [comment]
Closing this for now, but looking forward to your new tutorials @yezhengSTAT!

**Pull request closed without merging**
