### PR TITLE
Make @anuprulez a maintainer for ML/stats

### PR DESCRIPTION
**Pull request by hexylena**
@martenson could you add him to the @galaxyproject/training-statistics group?

### CODE REVIEW

**Comment by shiltemann** [comment]
thanks @anuprulez, great to have you on board as a maintainer!

**Comment by hexylena** [comment]
I went ahead and manually added @anuprulez, hopefully we can get him added via the team soon, but for now we can merge.

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
Thanks @anuprulez! Great to have you on board!

**Comment by martenson** [comment]
Done, sorry. Thanks @anuprulez !

**Pull request merged**
