### PR TITLE
New CiteSeq Tool Tutorial--DRAFT (WIP)

### PR DESCRIPTION
**Pull request by Camila-goclowski**
These are the beginnings of a tutorial which will use the recently added CITE-Seq capabilities on the Seurat tool. The tutorial plan is to move into RStudio and highlight some of Seurat's functionality when it comes to exploring and visualizing multimodal data!

### CODE REVIEW

**Comment by lldelisle** [comment]
Hi @Camila-goclowski ,
I added the CITE-seq tool. I was very happy that someone wrote a tutorial about it. Why did you close the PR. Is it somewhere else?

**Comment by lldelisle** [comment]
I am using it in this workflow in order to analyse CellPlex 10X data. I don't know if this can help you: https://github.com/galaxyproject/iwc/blob/fa7da0e1f8ff4e4cf2091570d552af42d93e7947/workflows/transcriptomics/sc-rnaseq/Galaxy-Workflow-scRNA-seq_preprocessing_10X_cellPlex.ga

**Comment by hexylena** [comment]
@lldelisle it seems to now be #4475

**Comment by lldelisle** [comment]
Thanks @hexylena

**Pull request closed without merging**
