### PR TITLE
added the way I used to generate a toy dataset

### PR DESCRIPTION
**Pull request by lldelisle**
Hi,
I added a small paragraph to explain what I did but I think I would need to wrap it a bit better.

### CODE REVIEW

**Comment by lldelisle** [comment]
Is it normal that Travis is failing?

**Comment by shiltemann** [comment]
Hi @lldelisle thanks! and travis is failing because you are not yet in the CONTRIBUTORS.yaml file. I know you added yourself in https://github.com/galaxyproject/training-material/pull/1472, but since that is still a work in progress, please add yourself here too, and then I can merge this :)

**Comment by lldelisle** [comment]
Many thanks, I forgot...

**Comment by lldelisle** [comment]
Many thanks for the formatting... This is much more clear now.

**Comment by shiltemann** [comment]
thanks @lldelisle!

**Pull request merged**
