### PR TITLE
Add support for details type box for FAQs

### PR DESCRIPTION
**Pull request by shiltemann**
This should allow setting `box_type: details` on FAQs per @bebatut request

### CODE REVIEW

**Comment by bebatut** [comment]
I think I already did it in the PR with the TtT material...

**Comment by shiltemann** [comment]
are you sure? I don't see it?

**Comment by bebatut** [comment]
My bad, it is the beer tutorial...

**Comment by shiltemann** [comment]
ahh ok, we can wait until that one then, will close this again

**Pull request closed without merging**
