### PR TITLE
Try to ameliorate boxes rerun + answer in a question box

### PR DESCRIPTION
**Pull request by yvanlebras**
as for now this is not really well rendered in the training website

photo_2020-11-27_09-33-22

### CODE REVIEW

**Comment by shiltemann** [comment]
Thanks @yvanlebras, unfortunately the snippets assume exactly 1 level of nesting. So this change still won't fix it. 

There are a few possible workarounds: 
1. Move the question box outside of the hands-on box
2. Move the tip outside of the question box
3. Just forget about the snippet and change instruction to something like `You can also "just" rerun (by clicking the rerun icon {% icon galaxy-refresh %} on the tool output).. `

Do you have a preference?

**Comment by ColineRoyaux** [comment]
Thank you @shiltemann ! Any solution works for me, maybe the third one as it seems to be the simplest

**Review by shiltemann — DISMISSED** [review]

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
ok, should be fixed now :+1: thanks!

**Comment by ColineRoyaux** [comment]
Thank you so much for your help !

**Comment by yvanlebras** [comment]
Thank you Saskia !

**Pull request merged**
