### PR TITLE
Add separate OSX environment

### LINKED ISSUE #3218: Issues running GTN website locally on Mac
Hi, I was having issues with `make serve` and ended up doing a fresh clone of this repo. But when running `make create-env` (as [here](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/running-jekyll/tutorial.html)) I get the error
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - gxx=9
  - gcc=9

make: *** [create-env] Error 1
```

I'm guessing as there's no gcc9 (or g++9) for Mac in conda here https://anaconda.org/conda-forge/gcc ? 

I'll try using GitPod in the meantime but does anyone know if/how I can get past this error?

### PR DESCRIPTION
**Pull request by hexylena**
Could someone with a mac test if this env resolves?

Fixes #3218

### CODE REVIEW

**Comment by shiltemann** [comment]
@bebatut are you still using a Mac? have moment to test this?

**Comment by bebatut** [comment]
Not my work one but at home yes. I tried last - week:
- the environment built
- but the serving failed

I forgot to report there. I will do it tonight

**Comment by bebatut** [comment]
The error: 

```
% make serve-quick
find: _site/training-material: No such file or directory
find: _site/training-material/*/*/slides/*: No such file or directory
find: _site/training-material: No such file or directory
cat metadata/swagger.yaml | python bin/yaml2json.py > api/swagger.json
Traceback (most recent call last):
  File "/Users/bebatut/Documents/projects/galaxyproject/training-material/bin/yaml2json.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
make: *** [api/swagger.json] Error 1
```

I could solved it by adding `${ACTIVATE_ENV} && \` to `api/swagger.json` command:

```
api/swagger.json: metadata/swagger.yaml
	${ACTIVATE_ENV} && \
	cat metadata/swagger.yaml | python bin/yaml2json.py > api/swagger.json
```

**Comment by shiltemann** [comment]
does this look good to go now @bebatut?

**Review by shiltemann — APPROVED** [review]

**Pull request merged**
