### PR TITLE
Create histories_Sharing and publishing histories.md

### PR DESCRIPTION
**Pull request by anayo-hub**

### CODE REVIEW

**Comment by anayo-hub** [comment]
@annefou @beatrizserrano please I'm waiting for a review

**Review by beatrizserrano — COMMENTED** [review]
Hi @anayo-hub, thanks for contributing! Please take a look at [this tutorial](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#faqs-snippets) that explains what FAQs are useful for.

Some general comments: the file name is important, the content of the FAQ should be clear and concise numbered steps (if possible). You can get some inspiration by looking at other similar FAQs :)

**Comment by anayo-hub** [comment]
@annefou please I have made some changes, I hope this is in line.

**Comment by anayo-hub** [comment]
@annefou  @beatrizserrano please I'm waiting for a review, i have made the necessary changes

**Comment by annefou** [comment]
> @annefou @beatrizserrano please I'm waiting for a review, i have made the necessary changes

Sure. Be patient. We are all very busy and do our best to answer to all the different questions.

**Comment by beatrizserrano** [comment]
I'm closing this because it's already covered in the FAQ mentioned by @annefou. Thank you @anayo-hub!

**Pull request closed without merging**
