### PR TITLE
Refine new AIV tutorial based on first training experience

### PR DESCRIPTION
**Pull request by wm75**

### CODE REVIEW

**Comment by wm75** [comment]
Thanks @kciy for spotting the copy/paste error at the fastp step before the training!
Will fix more issues here as they get discovered.

**Review by shiltemann — APPROVED** [review]

**Comment by wm75** [comment]
Thanks @shiltemann for the reminder. I had this last point on my list of fixes: bamtools split by ref messes up the order of the resulting collection if you run it with an explicit selection of refs as we discovered during the workshop.

I'm currently investigating how to fix this best at the tool level, but until then this is a simple fix for the tutorial.

**Comment by wm75** [comment]
Guess these are all the hotfixes for now.

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
wait, did you want to remove the `enable: false` here too?

**Comment by wm75** [comment]
Lets leave it disabled for a little while still. I've also learnt quite a bit about typically asked questions in the field and will rephrase a couple of things in a separate PR.

**Pull request merged**
