### PR TITLE
Add two more Mastodon accounts (and a matrix id)

### PR DESCRIPTION
**Pull request by wm75**
cause who wouldn't want to profit from https://mstdn.science/@gtn/110628391201479353 :-)

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
hah :D wondered if it would be motivating

**Comment by hexylena** [comment]
@hrhotz you're also welcome to join in

**Comment by hrhotz** [comment]
Thanks for the heads-up
I will add my accounts within the next few days

**Comment by hrhotz** [comment]
done, see: https://github.com/galaxyproject/training-material/pull/4256

**Pull request merged**
