### PR TITLE
hicexplorer workflow

### PR DESCRIPTION
**Pull request by polkhe**
corrected workflow

@joachimwolff

### CODE REVIEW

**Comment by bebatut** [comment]
ping @joachimwolff

**Comment by bgruening** [comment]
ping @joachimwolff

**Comment by bgruening** [comment]
@joachimwolff can you fix this. Would be nice to deploy it to get real life testing.

**Comment by joachimwolff** [comment]
Workflow is working. Thanks a lot @polkhe.

**Pull request merged**
