### PR TITLE
added workflow for the tutorial on tal1 binding site identification

### PR DESCRIPTION
**Pull request by polkhe**
added workflow for the tutorial on chip-seq:tal1 binding site identification

- could not use `Intersect intervals` to find unique peaks (option only for overlapping)

### CODE REVIEW

**Comment by bebatut** [comment]
@malloryfreeberg Can you check this workflow? Thanks!

**Comment by malloryfreeberg** [comment]
@bebatut sorry for the delay. I will check this out this week!

**Comment by bebatut** [comment]
@malloryfreeberg Do you think we can merge this one?

**Comment by malloryfreeberg** [comment]
I imported the workflow into Main and ran into a few issues:
```
Please review the following issues, possibly resulting from tool upgrades or changes.
Step 50: plotFingerprint
No value found for 'Bam file'. Using default: ''.
Step 62: multiBamSummary
No value found for 'Bam file'. Using default: ''.
Step 63: plotFingerprint
No value found for 'Bam file'. Using default: ''.
Step 75: plotCorrelation
Multiple values provided but parameter colorMap is not expecting multiple values. Using default: 'RdYlBu'.
Step 78: computeMatrix
No value found for 'Score file'. Using default: ''.
An invalid option was selected for sortRegions, 'keep', please verify. Using default: 'descend'.
Step 83: plotHeatmap
Multiple values provided but parameter colorMap is not expecting multiple values. Using default: 'RdYlBu'.
```
The `plotFingerprint` tool, for example, is v2.2.2.0 in the workflow but v2.5.0.0 on Main (updated May 2017), and thus is breaking the links between the input and the `plotFingerprint` tool.

I don't remember what our policy is on supporting workflows running in Main versus running in the Docker image that comes with the tutorial. @bebatut @polkhe was this workflow tested using Main or Docker?

**Comment by bebatut** [comment]
The given tutorial is now hidden and out of date.

**Pull request closed without merging**
