### PR TITLE
Import of RO-Crate / By Covid training materials for Smörgåsbord

### PR DESCRIPTION
**Pull request by hexylena**
- All five currently available materials have been imported
- All licensed under Apache-2.0
- Two of these are notebook-compatible, one is bash (great) and another python
- for the python notebook I've added automatic support for bash cells to allow e.g. pip-installing packages, it works okish.
- updated contributor profile page for funding agencies
- Over 300 contributors in the GTN with this PR.

xref https://github.com/gallantries/video-library/pull/78 ping @stian @pauldg @simleo

### CODE REVIEW

**Comment by hexylena** [comment]
@shiltemann if you have time to look at this and merge it? It adds a new topic "FAIR Data, Workflows, and More" under the "data science survival kit" heading. Kate is going to add some more fair training materials under that heading in the future.

**Comment by simleo** [comment]
We need to add the Apache-2.0 license to https://github.com/by-covid/gtn before this is merged. @pauldg are you ok with that?

**Comment by pauldg** [comment]
Yes, I'm okay with that

**Review by shiltemann — APPROVED** [review]
This looks great, thanks all! 

Approving this now, let us know when it's ready to merge from your side (e.g. after you've added the license you mentioned?)

**Comment by simleo** [comment]
> Approving this now, let us know when it's ready to merge from your side (e.g. after you've added the license you mentioned?)

[Done](https://github.com/by-covid/gtn/commit/06b36e61bc9425ec5bf6f1cd7819d979a83cfa45). Ready to merge.

**Pull request merged**
