### PR TITLE
Workflow for non-dip

### PR DESCRIPTION
**Pull request by MoHeydarian**
Adding workflow for non-diploid variant analysis tutorial.

### CODE REVIEW

**Comment by bebatut** [comment]
@wm75 could you check this workflow? thanks a lot

**Comment by wm75** [comment]
To make this more robust (e.g. for automated testing with zenodo uploads), it may be a good idea to set the read group ID and sample names explicitly at the bwa-mem steps. If you have them autodetected they will be determined from the dataset name, and that will be different as soon as you upload via link. This will affect the final output, i.e., will break testing.

**Comment by wm75** [comment]
@MoHeydarian are you sure these changes belong here? Looks like you forgot to check out a new topic branch first.

**Comment by MoHeydarian** [comment]
@wm75 correct, I did not intend to push anything to the GTN branch. Apologies for the confusion.

**Pull request closed without merging**
