### PR TITLE
Contribute Models - AI4Life Training Material

### PR DESCRIPTION
**Pull request by cfusterbarcelo**
# Contribute Models

New training material for contributing with models to the [bioimage.io](https://bioimage.io/#/). Slides based on the documentation available [here](https://bioimage.io/docs/#/contribute_models/README).

Also some corrections to the previous slides have been made.

### CODE REVIEW

**Comment by hexylena** [comment]
Looks fine from a technical perspective, do you @cfusterbarcelo and @beatrizserrano have any colleagues you want to be added as "maintainers" for this topic? We'd be happy to grant you the power to merge your own PRs, so you can do it without our involvement :)

**Review by hexylena — APPROVED** [review]

**Comment by beatrizserrano** [comment]
> Looks fine from a technical perspective, do you @cfusterbarcelo and @beatrizserrano have any colleagues you want to be added as "maintainers" for this topic? We'd be happy to grant you the power to merge your own PRs, so you can do it without our involvement :)

Thanks a lot for your help @hexylena. I think that for now, we can keep it as is (unless @cfusterbarcelo has someone around that could be a maintainer) and keep you posted if this changes :)

**Comment by hexylena** [comment]
@beatrizserrano then shall I leave these PRs for you to merge? :)

**Comment by beatrizserrano** [comment]
> @beatrizserrano then shall I leave these PRs for you to merge? :)

yes, I can review and merge!

**Comment by hexylena** [comment]
fantastic :)

**Pull request merged**
