### PR TITLE
Topic embeds, topics by tag

### PR DESCRIPTION
**Pull request by hexylena**
@nomadscientist what do you think? This something you could put in an iframe on the singlecell homepage?

It uses the GTN's existing layout engine of course so you get the Tags (do you hate those?) and it won't fit *as* nicely since we use different fonts/etc (but you could match our font.), but otherwise this might give you something that would let you keep https://usegalaxy-eu.github.io/index-singlecell.html updated

Not wide | wider 
-- | ---
Screen Shot 2023-10-05 at 14 26 28 | Screen Shot 2023-10-05 at 14 26 35

### CODE REVIEW

**Comment by nomadscientist** [comment]
This is fucking amazing

**Comment by nomadscientist** [comment]
I like the tags (and plan to organise the tags on the single cell tutorials soon anyway) so no, this is good, and particularly the narrow looks great

**Comment by hexylena** [comment]
The workflow search

Screenshot 2023-10-05 at 16-25-31 Galaxy Training Cross UseGalaxy  Workflow Search

Also available as an embed

```
/workflows/embed.html?query=...
```

**Comment by hexylena** [comment]
Ok, should be ready to go. Would appreciate that whoever merges this tests it briefly (do topic pages load right? by-tag topic pages like covid?)

**Comment by hexylena** [comment]
@nomadscientist you wanna hit merge? I think I've tested enough locally

**Review by nomadscientist — APPROVED** [review]

**Pull request merged**
