### PR TITLE
Set diversity toturial to draft until finalized

### PR DESCRIPTION
**Pull request by paulzierep**
Its still needs a update before usable, so set to draft for now

### CODE REVIEW

**Review by bebatut — DISMISSED** [review]

**Comment by bebatut** [comment]
Can you also try to fix the linting errors in this PR? They will impact every PRs

**Comment by shiltemann** [comment]
ok, I fixed the error that was causing the build failure (missing comma in bib file) in main :+1:

**Review by bebatut — APPROVED** [review]

**Comment by bebatut** [comment]
is it ready @paulzierep ?

**Comment by paulzierep** [comment]
@shiltemann @bebatut fixed all lintings and links and set to draft, mind if I merge this one ?

**Comment by paulzierep** [comment]
thanks @bebatut now for the actual work

**Pull request merged**
