### PR TITLE
Badge support for training-compatible instances

### PR DESCRIPTION
**Pull request by erasche**

### CODE REVIEW

**Comment by erasche** [comment]
@bebatut in order to now have to parse external data sources I needed to annotate *all* instances, including unsupported ones. This makes the metadata file much larger, but means that 100% of the necessary information is in one place.

**Comment by erasche** [comment]
Ok @bebatut finally this should be "ok".

1. no duplication with your work
2. (thus) no network requests needed other than fetching badges.
3. can be run separately from your script. I keep going back on whether or not this is the "best" way, but this way at least we have the option to run it on a different machine / in a different deployment way.

**Comment by erasche** [comment]
auswahl_059

**Comment by erasche** [comment]
ping @bebatut ready.

**Comment by erasche** [comment]
rebased as well https://github.com/galaxyproject/training-material/pull/587#issuecomment-348539842

**Comment by willdurand** [comment]
😎

**Pull request merged**
