### PR TITLE
Updating Get Data slides

### PR DESCRIPTION
**Pull request by mblue9**
ping @hexylena @shiltemann @mvdbeek have started updating the slides, if you have any comments let me know, happy to change anything.

### CODE REVIEW

**Comment by shiltemann** [comment]
thanks @mblue9! I can review this today. It's still marked WIP, were you going to add more content or is this good from your side? :)

**Comment by hexylena** [comment]
Moving some email discussion here:

> if I can get time I was thinking I could try to update the “upload logic” diagram (here: https://galaxyproject.org/tutorials/upload/) to add in where Rule Builder and Collections fit for a visual overview of knowing which method to use (I could put them under the  branch “Are there many datasets -> Yes” ??). Do you know of a diagram tool for that kind of thing?

That's a great idea! @jmchilton did some great work in the Galaxy Architecture slides using plantuml to make flowcharts from text files.

I can make a quick example that you could build on maybe?

**Comment by hexylena** [comment]
Update: I made... something. with plantuml and I've decided that it might be a bit of a struggle to use for this specific use case (i.e. could not find any diagrams that closely enough matched what I wanted.)

So feel free to make it in powerpoint or inkscape or whatever works for you.

**Comment by mblue9** [comment]
I will have a look at creating the diagram this week if I can get the chance and can add that later. But this could be reviewed now @shiltemann. 
One thing I had issues with is sizing some screenshots.

**Comment by shiltemann** [comment]
> One thing I had issues with is sizing some screenshots.

@mblue9 You can size images like: `.image-25[]`

(the number represent % of the width of the slide) ..not all numbers work, but here you can see the options: https://github.com/galaxyproject/training-material/blob/master/assets/css/slides.css#L105  I will do some resizing in my review too, feel free to let me know which ones you had problems with

**Comment by shiltemann** [comment]
thanks @mblue9!

**Comment by mblue9** [comment]
ah great I was trying things like {:width="60%"}
and great that you added in how to get the files in post Filezilla with ftp I meant to do that but forgot!

**Pull request merged**
