### PR TITLE
Update tool integration slides

### PR DESCRIPTION
**Pull request by nsoranzo**
- Update several screenshots
- Drop Docker slides
- Misc fixes

### CODE REVIEW

**Review by hexylena — DISMISSED** [review]
These are great!

**Review by bgruening — APPROVED** [review]
Our UI looks better and better :)

**Comment by nsoranzo** [comment]
I think the linting failure is unrelated?

**Comment by hexylena** [comment]
it is, indeed. I'll fix it in this PR and then merge it.

**Review by hexylena — APPROVED** [review]

**Pull request merged**
