### PR TITLE
[FAQ] Added FAQ for 'exceeds memory allocation' in job failure

### PR DESCRIPTION
**Pull request by garimavs**
This PR is a part of the issue: _Move FAQs to the GTN_ ([Determining the job failure type](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type)) of the [Galaxy Hub Repository](https://github.com/galaxyproject/galaxy-hub)

Though there is a reference to PR #3378. Once the PR gets merged, I'll update the link here.
 
Kindly suggest any improvements or amendments.
Thanks to @jennaj for helping me with the content.

### CODE REVIEW

**Review by jennaj — CHANGES_REQUESTED** [review]
Please modify the last two "Solutions" the same as for this one: https://github.com/galaxyproject/training-material/pull/3407#issuecomment-1106006660

**Review by jennaj — CHANGES_REQUESTED** [review]
Please modify the last two "Solutions" the same as for this one: https://github.com/galaxyproject/training-material/pull/3407#issuecomment-1106006660

The name of the FAQ should also be updated. Use naming format similar to this one (all of this type should use a standardized name since all go together. https://github.com/galaxyproject/training-material/pull/3421

**Comment by garimavs** [comment]
I renamed the names and will update the link once the PRs are merged.

**Review by jennaj — APPROVED** [review]
The links here are different from others like this one: https://github.com/galaxyproject/training-material/pull/3320/commits/cd6f812f6ceb52f1b80f900bd266e7ef99404272

Not sure if that matters.

**Pull request merged**
