### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by ksuderman**
Minor fix, the button is labelled *Upload*, at least on Main.

### CODE REVIEW

**Comment by hexylena** [comment]
I've found one more, but it doesn't seem I can push to your fork. In the future if you can check the box on the right that says maintainers can push it helps us. Would you mind making this addition to your PR?

```diff
diff --git a/topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.md b/topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.md
index a5037309a1..961f0a980e 100644
--- a/topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.md
+++ b/topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.md
@@ -152,7 +152,7 @@ We will use this information to build a collection of FASTA files from our query
 >    >
 >    > This could additionally be copied and pasted if you need to do the same set of operations on multiple metadata inputs that are similarly formatted.
 >    {: .comment}
-> 7. Click `Build` and wait for your list of FASTA files to appear.
+> 7. Click `Upload` and wait for your list of FASTA files to appear.
 {: .hands_on}
```

**Comment by ksuderman** [comment]
The "Allow edits by maintainers" button is checked so I don't know why you can't push edits.  However, I made the suggest change.

**Comment by hexylena** [comment]
Weird! Ok, thanks for doing it :)

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
thanks so much @ksuderman

**Pull request merged**
