### PR TITLE
Galaxy intro slides

### LINKED ISSUE #79: Fill the introduction slide deck on Galaxy Introduction
Hi,

The [introduction slide deck of Galaxy](https://github.com/bgruening/training-material/blob/master/Introduction/slides/index.html) needs to be filled.
I think it could be nice to use [ideas from this slide deck](https://github.com/bgruening/training-material/blob/master/Introduction//tmp/Introduction_to_Galaxy_Uni.pdf)

Thanks

Bérénice

### PR DESCRIPTION
**Pull request by nsoranzo**
This will fix #79.

This also:
- converts `Introduction/slides/options_for_using_galaxy.html` to Remark and updates it
- adds `Introduction/slides/galaxy-intro-get-data.html`

### CODE REVIEW

**Comment by nekrut** [comment]
@nsoranzo I just finished this https://galaxyproject.org/tutorials/g101/ . Perhaps you can reuse peices

**Comment by nsoranzo** [comment]
@nekrut Thanks, I'll take a look, but we are working on introductory slides, not tutorial.

**Comment by nsoranzo** [comment]
The 3 slide decks in `Introduction/slides/` should be ready for review.

**Comment by bgruening** [comment]
@nekrut do you want to review, we are heading for pizza!

**Comment by bgruening** [comment]
Great work! Thanks a lot guys!

**Comment by pajanne** [comment]
Thanks for organising the hackathon in Cambridge!

**Pull request merged**
