### PR TITLE
Added workflow to Deep Learning Tutorial

### PR DESCRIPTION
**Pull request by kxk302**

### CODE REVIEW

**Comment by kxk302** [comment]
@anuprulez Here is the PR for addition of the workflow to Deep Learning tutorial.

**Review by anuprulez — CHANGES_REQUESTED** [review]

**Comment by anuprulez** [comment]
Thank you @kxk302. I found these minor issues.

**Comment by kxk302** [comment]
> Thank you @kxk302. I found these minor issues. Apart from these, the workflow looks great!

Thank you @anuprulez! Added the labels for input data.

**Comment by anuprulez** [comment]
@kxk302 Looks good to me :+1:

**Review by hexylena — APPROVED** [review]

**Comment by kxk302** [comment]
Thank you all!

**Pull request merged**
