### PR TITLE
New training material - Metabolomics > LCMS pre-processing

### PR DESCRIPTION
**Pull request by melpetera**
This Pull Request is about a new tutorial focussing on LC-MS data pre-processing for untargetted metabolomics.

This work is not fully ready yet but we have a training tomorrow where we need this so I make the pull request now knowing that it is not fully ready yet (quite a few things to do, especially concerning the complementary slides). 

I did not managed to make it in time for now, but wish to have something cleaner around the middle of this month.

### CODE REVIEW

**Comment by shiltemann** [comment]
Hi @melpetera, thanks! If you need this merged by tomorrow but it is not ready yet, you can add `enabled: false` to the metadata, that way the materials can be accessed via url, but they won't show up in the tutorial list until they are ready.

**Comment by lecorguille** [comment]
@shiltemann Thanks for the trick.
But at least before merging, I will remove the picture header and add title to the slides.

**Comment by lecorguille** [comment]
The images have been cropped (and squash)

**Comment by melpetera** [comment]
Thanks a lot @shiltemann and @lecorguille 
With the tests going green, do you think it would be possible to have a merge before tomorrow 8AM? (Our training is in the morning.)
Thank you a lot for your help and time.

**Pull request merged**
