### PR TITLE
Fixes to 10x workflow

### PR DESCRIPTION
**Pull request by mtekman**
Added strandedness explanation, updated barcodes, zenodo record based on recommendations from @hrhotz 

This incorporates fixes mentioned:
- https://github.com/galaxyproject/training-material/pull/1600
- https://github.com/galaxyproject/training-material/issues/1601

### CODE REVIEW

**Comment by hrhotz** [comment]
General Question: The data (i.e.: the fastq files) is provided under "https://creativecommons.org/licenses/by/4.0/" by 10X. As far as I know, the barcode files are part of the software, aren't-they? Is the software also distributed under  'CC BY 4.0' ?

**Comment by mtekman** [comment]
As far as I understand, these files come with cell ranger and so are distributed with the cell ranger license which is MIT

https://github.com/10XGenomics/cellranger/blob/master/LICENSE

**Comment by hrhotz** [comment]
I am not an expert on open source license, especially, I am always confused wrt the hierarchy between them: If the barcode files are distributed under "MIT", is it then allowed to re-distribute them under  'CC BY 4.0'  on zenodo?

**Comment by mtekman** [comment]
I think it would be enough to serve both licenses in the Zenodo url, but we probably wouldn't need to mention it in the tutorial. Would that work?

**Comment by nsoranzo** [comment]
@hrhotz You can mix MIT-licensed files with stuff under any other license, as long as you distribute the MIT license file with them.

**Comment by hrhotz** [comment]
@nsoranzo Thank You for providing a solution!

**Comment by mtekman** [comment]
@hrhotz good spot, will fix

**Comment by mtekman** [comment]
@hrhotz so I updated the Zenodo link to include an MIT license, and added a link to CC. In the material I changed the cell numbers, and added a section about whitelist barcodes.

**Pull request merged**
