### PR TITLE
Improving the reference based Transcriptomics tutorial

### PR DESCRIPTION
**Pull request by bernt-matthias**
I'm currently working on this tutorial. Lets see if we an make some progress here:

https://github.com/galaxyproject/training-material/issues/519 should be solved by my first commit. 

I discovered the following issues where comments would be welcome: 

https://github.com/galaxyproject/training-material/issues/552
https://github.com/galaxyproject/training-material/issues/544
https://github.com/galaxyproject/training-material/issues/531

### CODE REVIEW

**Comment by nsoranzo** [comment]
It was also proposed to use featureCounts instead of htseq-count.

**Comment by bernt-matthias** [comment]
I see: as in the de-novo tutorial. What would be the pro/cons? 

Somehow I like the idea to cover more than one tool in the different tutorials (having in mind that the tutorials serve also as human operated Galaxy/Tool tests).

**Comment by bernt-matthias** [comment]
I also was wondering what the `Filter` tool is?

**Comment by nsoranzo** [comment]
> What would be the pro/cons?
> Somehow I like the idea to cover more than one tool in the different tutorials (having in mind that the tutorials serve also as human operated Galaxy/Tool tests).

featureCounts was much faster with equivalent results, don't know with the latest versions. A comparison is at http://bioinformatics.cvr.ac.uk/blog/featurecounts-or-htseq-count/

> I also was wondering what the Filter tool is?

I suppose the one shipped with Galaxy with tool id `Filter1` and full name/description "Filter data on any column using simple expressions".

**Comment by bgruening** [comment]
My preferred tutorial would be. Star for mapping, featureCount for counting, replacing David with potentially goseq.

**Comment by bernt-matthias** [comment]
One question regarding data collections. I tried to process all paired samples as list of pairs and the others as list, which works fine until DeSeq2. The problem is that it seems impossible to select the data sets corresponding to the factors within such a list. Also breaking the lists (btw is there a better way than unhiding the actual data sets) seems not helpful, since the automatic naming does not allow to identify the factors anymore. Also tags seem to be no option since they are lost when trim galore is run on such a list -- and factor selection by tag in a list seems not possible .. (I guess tags are still in development).

**Comment by nsoranzo** [comment]
Maybe @mvdbeek can help with the tag question here?

**Comment by mvdbeek** [comment]
> The problem is that it seems impossible to select the data sets corresponding to the factors within such a list.

Right, what I do is creating a collection per factor (you can do this after the fact with "Filter List from contents of a file"). This will keep the element identifiers.

> factor selection by tag in a list seems not possible .. (I guess tags are still in development).

It is in some input boxes, but not in the multi-input list at the moment.

**Comment by bernt-matthias** [comment]
I finally got goseq running (maybe you have some comments): 
- I obtained go data with `BioMart Ensembl server` 
- Gene length data was obtained with Gene `length and gc content` (using BioMart did not work since the Transcript length (including UTRs and CDS) results in a table having duplicate gene entries)
- Differentially expressed gene file was obtained with `Compute an expression on every row`  and `cut`

**Comment by mvdbeek** [comment]
@bernt-matthias that looks right to me. @mblue9 did some work on goseq in https://github.com/galaxyproject/tools-iuc/pull/1523 to be able to fetch go categories in goseq, so you could skip the first step if the annotations for your species are among human, mouse, fruitfly or zebrafish.

**Comment by bernt-matthias** [comment]
The PR looks great. I will check if the new version is in the TS when I start writing.

**Comment by bebatut** [comment]
@bernt-matthias I will close this PR. We updated the tutorial with #691 and changed the `tour.yaml` file
Let me know if I miss a change that should be added to the tutorial

**Pull request closed without merging**
