### PR TITLE
tour for clipseq

### PR DESCRIPTION
**Pull request by polkhe**
@bebatut tour for transcriptomics

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @polkhe 
@Florian-H-Lab could you check this tour? thank you

**Comment by Florian-H-Lab** [comment]
sure

**Comment by bebatut** [comment]
thank you a lot!
Do you know the browser extension (Galaxy tourbuilder) to run a tour?

**Comment by Florian-H-Lab** [comment]
Yeah I already used it.

**Comment by bebatut** [comment]
Recent changes have been made to the tutorial. This tour is probably out of date.
@heylf what do you think?

**Pull request merged**
