### PR TITLE
Update ansible-galaxy for 2021

### PR DESCRIPTION
**Pull request by hexylena**
xref https://github.com/galaxyproject/admin-training/issues/99

### CODE REVIEW

**Comment by abretaud** [comment]
I'm testing the same tutorial atm, I may have a few little corrections soon

**Review by shiltemann — APPROVED** [review]
looks good!

**Comment by abretaud** [comment]
There's this other pr which is linked to this one: https://github.com/usegalaxy-eu/ansible-gie-proxy/pull/4

**Comment by hexylena** [comment]
@abretaud I've pushed a new version of that role. Just use that when you pr to update the GxIT training with the new aws credential method.

**Pull request merged**
