### PR TITLE
add section on upgrade procedures

### PR DESCRIPTION
**Pull request by erasche**
From @qiagu's comments in gitter

### CODE REVIEW

**Comment by nsoranzo** [comment]
Nice! What about how to keep Galaxy updated while on a release branch?

**Comment by erasche** [comment]
> Nice! What about how to keep Galaxy updated while on a release branch?

if you're tracking galaxy / release_xx.yy, is there anything special to do? Other than just "run playbook regularly"? Or maybe I misunderstood :)

**Comment by nsoranzo** [comment]
> if you're tracking galaxy / release_xx.yy, is there anything special to do? Other than just "run playbook regularly"? Or maybe I misunderstood :)

I wasn't sure that was enough to update the git branch, maybe mention it at the end of the new section?

**Comment by nsoranzo** [comment]
@erasche Feel free to merge if you are OK with my latest commit.

**Pull request merged**
