### PR TITLE
[FAQ] Added FAQ regarding input problems faced in job failures

### PR DESCRIPTION
**Pull request by garimavs**
This PR is a part of the issue: _Move FAQs to the GTN_ ([Determining the job failure type](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type)) of the [Galaxy Hub Repository](https://github.com/galaxyproject/galaxy-hub)

Though this PR, can't be worked upon as it has reference from PR #3379 #3380 #3381 #3393 
Once the above-mentioned PR gets merged, I'll update the links here.

Kindly suggest any improvements or amendments.
Thanks to @jennaj for helping me with the content.

### CODE REVIEW

**Review by jennaj — CHANGES_REQUESTED** [review]
Let's push this as-is. Can cross link later to more sub-FAQs in several places (since also sourced from the same original Hub FAQ -- and it has many breakouts). 

Should create a distinct issue to update this FAQ with the information above ("add crosslinks to >FAQ name< (link) and assign it to me. 

Could consider doing the same for the other sub-FAQs. Be specific about what should be linked -- FAQ finalized name + text to add link to + PR for that FAQ. Ok if not perfect. Is difficult to crosslink before publishing for most of these in the same group.

**Review by jennaj — APPROVED** [review]
Once the issues are created for the logical FAQs crosslinks (to be addressed later), anyone else can approve this. Very very good start for this content. Note: The existing crosslinks are great.

**Review by jennaj — CHANGES_REQUESTED** [review]
Opps - not approving until issues created.

**Comment by garimavs** [comment]
> Let's push this as-is. Can cross link later to more sub-FAQs in several places (since also sourced from the same original Hub FAQ -- and it has many breakouts).
> 
> Should create a distinct issue to update this FAQ with the information above ("add crosslinks to >FAQ name< (link) and assign it to me.
> 
> Could consider doing the same for the other sub-FAQs. Be specific about what should be linked -- FAQ finalized name + text to add link to + PR for that FAQ. Ok if not perfect. Is difficult to crosslink before publishing for most of these in the same group.

Sorry, but I lost you here @jennaj 😅 

1) Is there a way to link FAQs through their names because I have been manually updating the links in the content of the FAQ for my whole contribution period?
2) Should I go with creating the issue, or a member from the community look at it?

**Comment by jennaj** [comment]
Yes, create an issue ticket in this same repo for the "to-do".

Include what FAQ, what text in that FAQ, and what the link should point to later. Can just be "crosslink this" for the last one.

Consider naming all of the "cross link to-do" issue tickets the same: 

"Add FAQ crosslink for ...." 

The "..." part can be generalized but distinct between issues tickets.

Then anyone can approve this PR without more changes and it will be considered done for now.

We can address the issues later. Many cross links will be needed across FAQs, but let's try to not lose the context we already know. 

Thank you!!

**Comment by garimavs** [comment]
I have created issue #3424 for the above-mentioned, will update the links once the PRs get merged.

**Review by annefou — DISMISSED** [review]

**Review by jennaj — APPROVED** [review]

**Review by jennaj — APPROVED** [review]

**Comment by jennaj** [comment]
The FAQ links are different in this one versus others like: https://github.com/galaxyproject/training-material/pull/3320/commits/cd6f812f6ceb52f1b80f900bd266e7ef99404272

Not sure is that matters or not.

**Comment by garimavs** [comment]
> The FAQ links are different in this one versus others like: [cd6f812](https://github.com/galaxyproject/training-material/commit/cd6f812f6ceb52f1b80f900bd266e7ef99404272)
> 
> Not sure is that matters or not.

I have been using this format in all the FAQs so far, and they have been working well. If @beatrizserrano or @annefou prefer the other way around, I could change it.

**Pull request merged**
