### PR TITLE
Formatting fixes to the scanpy tutorial

### PR DESCRIPTION
**Pull request by mtekman**
AnnData 0.7.4 no longer works for Import or Manipulate, though it did at most two weeks ago.

@mvdbeek  is patching it as we speak https://github.com/galaxyproject/tools-iuc/pull/3483

Surprisingly no links need to be updated, as all the relevant versions are correctly linked in the source material.... 
This is just a formatting fix PR then

### CODE REVIEW

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
So, no tool update? If so this is fine to go.

**Comment by mtekman** [comment]
Thanks -- and yeah it's strange that the user ran into an issue [this morning](https://gtnsmrgsbord.slack.com/archives/C01FQ9RLLF2/p1613457316041600), since the correct version of the tool was correctly specified...

No idea what the actual issue was

**Comment by hexylena** [comment]
it can be they're not using the webhook. We should encourage that more :/

**Comment by mtekman** [comment]
Oh for the tool update Marius is patching it - once it's patched and tested with the workflow, we can update the links again

Edit: Aaaah, that might have been it!

**Comment by mvdbeek** [comment]
Yeah, would be good to know how many people are using the webhook.

**Comment by mtekman** [comment]
If it's not that many, then maybe it would be good to disable the latest Anndata for tomorrow....

**Comment by hexylena** [comment]
Unfortunately no stats on webhook usage. I can PR something to add a tracking campaign for those visits though, it would be nice to have.

**Pull request merged**
