### PR TITLE
Added workflow diagram

### PR DESCRIPTION
**Pull request by Arhodes-NCBI**
Added workflow diagram to tutorial

### CODE REVIEW

**Comment by hexylena** [comment]
It looks like the image might be missing here?

**Comment by Arhodes-NCBI** [comment]
> It looks like the image might be missing here?

I put it in the images page in the topic: training-materials/topics/galaxy-interface/images/ SARF_Workflow_Overview.png

Did I do this incorrectly in the tutorial.md?

**Comment by hexylena** [comment]
I'm sorry, I misread! I thought it was a new image you were adding, not referring to a previous one.

**Comment by Arhodes-NCBI** [comment]
> I'm sorry, I misread! I thought it was a new image you were adding, not referring to a previous one.

Yes, I added the image in the last pull request, but wanted to make sure I had the path right before adding the link.  I have just added the link in this pull request.  I hope that works.

**Comment by hexylena** [comment]
I modified the link a bit, we use relative paths usually, so `../../images/<your image>`. and merged it. Looks good! :)

**Comment by hexylena** [comment]
it'll be deployed in ~20 minutes or so.

**Comment by Arhodes-NCBI** [comment]
The hazards of copy-paste from my notes, sorry about that!

**Pull request merged**
