### PR TITLE
remove unnecessary newline character from awk program in clipseq tuto…

### PR DESCRIPTION
**Pull request by pavanvidem**
…rial

### CODE REVIEW

**Review by lldelisle — APPROVED** [review]
Good catch, thanks.

**Comment by lldelisle** [comment]
Do you want me to merge it now?

**Comment by pavanvidem** [comment]
> Do you want me to merge it now?

Yes, please. Thanks!

**Comment by lldelisle** [comment]
> > Good catch, thanks.
> 
> Got a bug report in the EU server. I wonder if the tutorial ever worked with that.

Probably not...

**Pull request merged**
