### PR TITLE
For every topic a working Docker image

### PR DESCRIPTION
**Pull request by bedroesb**
Updated the docker image links and pushed a new docker image for every topic based on the latest version of GTN.

### CODE REVIEW

**Comment by bedroesb** [comment]
The topic *computational chemistry* already had a docker image `docker_image: "scientificomputing/bridge"`  in the metadata.yaml file. This will now be replaced with an updated workflow central docker image.

**Comment by bedroesb** [comment]
@bgruening Although I found out that not all tools are installed based on the workflows (I am working on an issue/PR about this), this will not affect this PR towards the links to the docker images itself.

**Comment by simonbray** [comment]
Hi @bedroesb @bgruening thanks a lot for working on this. How can these images be updated when new tutorials are added?

**Comment by bedroesb** [comment]
It would be nice to have a Jenkins Job that builds these images every month, when a new GTN release is released

**Comment by bedroesb** [comment]
Until a few months ago I did it manually every month, but since I am working from home and don't want to put to much stress on my home pc, they are getting a bit out of sync...

**Comment by nsoranzo** [comment]
A GitHub workflow could also be used.

**Comment by bedroesb** [comment]
I already tried that but the builds take to long / or to big in size -> transcriptomics is more than 2h + around 20gb

**Pull request merged**
