### PR TITLE
added tour, tools, workflow

### PR DESCRIPTION
**Pull request by polkhe**
Missing methyldackel tool on toolsched

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @polkhe!
The tests are failing. Can you check, please?

**Comment by bebatut** [comment]
@joachimwolff and @dpryan79, can you check?

**Comment by polkhe** [comment]
@bebatut done :)

**Comment by joachimwolff** [comment]
It is in the toolshed under its old name 'PileOMeth' https://toolshed.g2.bx.psu.edu/repository?repository_id=d32aec850d519e76

**Comment by bebatut** [comment]
@joachimwolff and @dpryan79 is the content okay for you?

**Comment by dpryan79** [comment]
@bebatut Looks nice! You might add a small note in the methylation bias part mentioning that biases of less than 5% can be ignored. You're always going to get a bit of wiggle on those graphs and 5% higher/lower is well within the range of biological insignificance.

**Comment by bebatut** [comment]
ping @polkhe. Can you add @dpryan79 comment, please?

**Comment by polkhe** [comment]
@bebatut added remark

**Comment by bebatut** [comment]
The tests are failing because Zenodo is down for now :(

**Comment by bebatut** [comment]
It is green! Thanks @polkhe

**Pull request merged**
