### PR TITLE
Added bernandez to  CONTRIBUTORS.yaml

### PR DESCRIPTION
**Pull request by bernandez**
Added bernandez as a contributor to the Galaxy Community.

### CODE REVIEW

**Comment by beatrizserrano** [comment]
@bernandez I think that this list is alphabetically sorted, could you follow that order? Thank you

**Comment by bernandez** [comment]
@beatrizserrano please can you have a look to see if I placed the details correctly?.Thanks :)

**Comment by bernandez** [comment]
Hi @annefou please can you help have a look at this PR.

**Comment by beatrizserrano** [comment]
@hexylena any idea why this is failing? I added Samantha already so that shouldn't fail I think

**Comment by hexylena** [comment]
It'd need to be rebased. But since it got this far in the build process it's probably fine to merge.

**Review by beatrizserrano — APPROVED** [review]

**Comment by beatrizserrano** [comment]
ok, let's see if that works, thanks @hexylena

**Pull request merged**
