### PR TITLE
Galaxy map

### PR DESCRIPTION
**Pull request by hexylena**
Fixes https://github.com/galaxyproject/training-material/issues/1055

Implements a "Galaxy Trainer Map" by simply annotating trainer locations in the `CONTRIBUTORS.yaml`. Please feel free to add your location and willingness to train! This is announced in a news item, and can be previewed below:

image

The 'country' field is currently unused, but maybe it's useful? Implemented for @lldelisle per our discussion in small scale admins

### CODE REVIEW

**Comment by lldelisle** [comment]
Thank you so much for this PR! Yes, I think it is useful to get the country to make a quick search in the yaml.

**Comment by lldelisle** [comment]
Should we add a metadata for 'possible trainer'?

**Comment by hexylena** [comment]
We could? Initially I thought having this metadata indicated "possible trainer", but you are correct, that is maybe a separate field semantically. Ok, we add that too.

**Comment by hexylena** [comment]
image

**Comment by hexylena** [comment]
@lldelisle what information should I add for you? I feel lonely in this PR ;)

**Comment by bgruening** [comment]
Can we take people from here: https://www.google.com/maps/d/edit?mid=1r8LJy6la-JeIrg23aZjpwVNjJDE&ll=2.486940839176235%2C0&z=2

Or ask them?

**Comment by hexylena** [comment]
@bgruening there are only two humans in there, dave and jen. All of the rest I guess need to get added to galaxy-hub where missing. I will file the issue.

**Review by shiltemann — APPROVED** [review]

**Pull request merged**
