### PR TITLE
Small RNA-seq tutorial update

### PR DESCRIPTION
**Pull request by malloryfreeberg**
ping @bebatut 

This PR contains major updates to the small RNA-seq tutorial including:
- Overhaul of tutorial.md: new dataset implemented, new workflow tools used, updated screenshots
- Creation of sRNA-seq directory in /images that contains just images for sRNA-seq tutorial (for more clear organization)
- Update of metadta.yaml file
- Update of tools.yaml file (please use this version one as it contains the correct tools)
- Added two workflows (Parts 1 and 2)

Also, this tutorial is more appropriate for the transcriptomics topic, not sequence-analysis.

Thanks!

### CODE REVIEW

**Comment by bebatut** [comment]
I will work on it to fix the conflicts and move it to transcriptomics

**Comment by malloryfreeberg** [comment]
Merci bien!

**Comment by bgruening** [comment]
@malloryfreeberg can you please add `Key points`. I think this is the only thing that is missing besides Vis.

Thanks.

**Comment by malloryfreeberg** [comment]
@bgruening `key_points` are listed in both the topic-level metadata.yaml and the tutorial-level metadata.yaml files. Is there somewhere else they need to go?

```
key_points:
- "Analysis of small RNAs is complex due to the diversity of small RNA subclasses."
- "Both alignment to references and transcript quantification approaches are useful for small RNA-seq analyses."
```

Working on viz now :)

**Comment by bgruening** [comment]
Mh, it's not listed in the webpage. I will look into this.

**Comment by malloryfreeberg** [comment]
@bgruening The Questions, Objectives, and title on the `tutorial.md` page are also not rendered on the website :/ These items are definitely all listed in both the opic-level `metadata.yaml` and the tutorial-level `metadata.yaml` files.

**Comment by bgruening** [comment]
Fixed in https://github.com/galaxyproject/training-material/commit/e9644d1fdb381b8e60d54094ac5e5b4cbc2ac36f :)

**Comment by malloryfreeberg** [comment]
Fixed with 1 line... Thanks @bgruening !!

**Pull request merged**
