### PR TITLE
GeneSeqToFamily tutorial

### PR DESCRIPTION
**Pull request by anilthanki**

### CODE REVIEW

**Comment by bebatut** [comment]
Hi @anilthanki  we have changed the way we organize metadata in this repository: I have updated your PR. The metadata are now at the top of the `tutorial.md` or `slides.html` files

**Comment by Delphine-L** [comment]
Hi @nsoranzo and  @anilthanki , I worked on phylogeny and gene families before, do you mind If I contribute to this tutorial?

**Comment by anilthanki** [comment]
Hi @Delphine-L please feel free to contribute also this is an old tutorial so it needs an update anyway

**Comment by erasche** [comment]
Hi @Delphine-L, we've assigned you since you indicated interest, let us know if you have time for working on this :)

**Comment by shiltemann** [comment]
Closing this 5 year old PR due to inactivity. Please feel free to re-open or create a new PR @anilthanki and/or @Delphine-L if you still want to add this tutorial

**Pull request closed without merging**
