### PR TITLE
Change the license to CC BY 4.0

### PR DESCRIPTION
**Pull request by nsoranzo**
See https://wiki.creativecommons.org/wiki/License_Versions for the list of changes in version 4.0 .

Hopefully we can get the explicit approval of all the contributors.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Ping @erxleben @MoHeydarian @mwolfien @friedue @tnabtaf @oinizan @jgoecks

**Comment by nsoranzo** [comment]
I'd like to also have :+1: from @joachimwolff @odoppelt @slegras @fmareuil @loraine-gueguen @Stortebecker @ValentinMarcon @kilpert @pavanvidem @cmonjeau @vdda

**Comment by nsoranzo** [comment]
Pinging again @erxleben @MoHeydarian @mwolfien @friedue @oinizan @jgoecks @joachimwolff @odoppelt @fmareuil @kilpert @vdda

**Comment by kilpert** [comment]
ok

**Comment by MoHeydarian** [comment]
Great!

**Comment by nsoranzo** [comment]
Last ping @oinizan @joachimwolff @vdda, would be nice to have your approval.

**Comment by joachimwolff** [comment]
Ok

**Comment by oinizan** [comment]
ok

**Comment by nsoranzo** [comment]
Thanks everyone!

**Pull request merged**
