### PR TITLE
[Update] Pre-processing of 10X Single-Cell RNA Datasets

### PR DESCRIPTION
**Pull request by mtekman**
This is a fix to the tutorial based on the the new STARsolo wrapper that was released last week and refreshed over the weekend https://github.com/galaxyproject/tools-iuc/pull/3380

This will be used for the GTN, and the video for this will be recorded soon. I was unfortunately unable to get the `make install` to create a working server environment (ruby issue related to libxml2-devel, but nothing I could pinpoint or resolve) and so I could not see how this physically looks.

If it's not too much trouble, is there any way to get a fast review on this and a quick look to see if it builds and looks okay @shiltemann ?

Apologies for the last minuteness of this

### CODE REVIEW

**Comment by shiltemann** [comment]
@mtekman sure, will look at this today, thanks!

**Comment by shiltemann** [comment]
for your issue, does this help?

image

If not, and you find a fix later, please add it to this box (in contributing tutorial)

**Review by shiltemann — APPROVED** [review]
ok, this all looks good to me locally :+1: thanks a lot for the updates @mtekman!

**Comment by mtekman** [comment]
Thanks for the review and merge !!

> for your issue, does this help?
> 
> image
> 
> If not, and you find a fix later, please add it to this box (in contributing tutorial)

sadly wasnt this -- I even tried installing every xml2 library under the sun -- no dice... If I find a solution I'll add it to the README

**Pull request merged**
