### PR TITLE
remove single cell tag from tutorials

### PR DESCRIPTION
**Pull request by nomadscientist**
I've learned it's bad practice to label a tag the same as the actual page, so let's remove it! Woo!

### CODE REVIEW

**Comment by pavanvidem** [comment]
Also, remove from the Spanish version? There are some linting issues, mainly due to incorrect levels of headings. Otherwise, looks good.

**Review by hexylena — COMMENTED** [review]
Made more sense when they were in transcriptomics, now that they're in their own category this looks like an improvement!

Would you mind fixing some of the heading level issues while you're here?

**Comment by nomadscientist** [comment]
> Also, remove from the Spanish version? There are some linting issues, mainly due to incorrect levels of headings. Otherwise, looks good.

Only because we aren't upkeeping them (still waiting on that grant to come through :-P)
But I'm not killing the pages so Spanscriptomics still lives...

But also Jurgi will create a better automated system (hopefully) so all hope is not lost for the Spanish translations

**Comment by nomadscientist** [comment]
> Made more sense when they were in transcriptomics, now that they're in their own category this looks like an improvement!
> 
> Would you mind fixing some of the heading level issues while you're here?

Done!

**Comment by nomadscientist** [comment]
@hexylena I can't figure out the latest linting error...

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
>  I can't figure out the latest linting error...

ähm, you find the best failure modes, ¿thank you? for flagging them for us to fix lol

**Comment by hexylena** [comment]
Ok it's due to having `tags:` rather than `tags: []` but that should be caught earlier in the linting process, not this late. But our schema validation library apparently doesn't check types properly, so `nil` was allowed for a `sequence`. So I guess we'll be more careful about how we handle tags access and that'll fix it.

**Review by hexylena — APPROVED** [review]

**Comment by nomadscientist** [comment]
I am a magic beast at finding new ways to screw up
Thank you fantastic GTN overlord!

**Pull request merged**
