### PR TITLE
Funannotate tapas update

### PR DESCRIPTION
**Pull request by abretaud**
Small changes to the funannotate tuto before recording https://github.com/gallantries/video-library/issues/38
First, an updated version of eggnog-mapper => with the old version the "funannotate annotate" was not able to parse the output and include it in the final gff3 file

### CODE REVIEW

**Comment by abretaud** [comment]
Ah yes wonderful! I'll do it when I'm done updating the workflow

**Comment by hexylena** [comment]
merci!

**Comment by abretaud** [comment]
This one's ready I think, the tutorial works fine on usegalaxy.fr and .eu (after fighting with interproscan!)
I've tried to add a workflow test, but the test-data dir is >1Gb... I guess there's no way to use data from a remote url in the test?

**Comment by abretaud** [comment]
Switched back to wip: I'll adapt the workflow test based on https://github.com/galaxyproject/iwc/blob/main/workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-ivar-analysis/pe-wgs-ivar-analysis-test.yml#L9

**Review by gallardoalba — APPROVED** [review]

**Pull request merged**
