### PR TITLE
Marine omics new tuto

### PR DESCRIPTION
**Pull request by Marie59**
Hi all !
This is new earth-system tutorial on the Marine Omics topic. This tuto shows how to use 3 tools:
- Prodigal
- InterProScan
- Sanntis

The last tool sanntis was recently added to galaxy. This workflow was build with the help of @SantiagoSanchezF.
@SantiagoSanchezF should normally add some details on what we are doing in this workflow (on the scientific side). Plus, the data (fasta nucleotide file) used for this example should normally soon be on zenodo (or some other stable repo).
While waiting for that I'll put this PR on draft mode.

### CODE REVIEW

**Comment by Marie59** [comment]
On a similar topic I notice that the RO-Crate export tutorial is not up to date 
On this tuto I did a tip box on how to export a ro-crate do you want me to try to update a bit the initial RO-Crate export tutorial ?

**Comment by SantiagoSanchezF** [comment]
Hi all!

Many thanks for contributing to make this happen.

@Marie59, I had a look a the tuto and is amazing. I'm really pleased with it.

Hopefully, the following contributions will help to make it a bit better:

## Nucleotide FASTA file

I added the same FASTA that is provided in SanntiS' repo for test. Find it in https://doi.org/10.6084/m9.figshare.24356782.v1 (download link https://figshare.com/ndownloader/files/48574534)

This file is, intentionally, a very small fraction of a genome (spanning exactly 1 BGC), and it's main purpose is to quickly check that all the pieces of the workflow are working. 

Let me know if a file with these characteristics is suitable for a tuto, or a full genome/contig would be more appropriate. Also if hosting it on Figshare works

## Sci. description on steps in the workflow

### Prodigal Gene Predictor
Prodigal is a tool that predicts protein-coding genes from DNA sequences. It takes a nucleotide FASTA file as input and identifies regions that are likely to code for proteins. The output is a protein FASTA file where each sequence represents a predicted protein. Some of these sequences end with an asterisk (*), which marks the end of a complete protein sequence identified by Prodigal. This asterisk is added when Prodigal detects a full protein-coding region that ends with a stop codon. Sequences without an asterisk either represent partial proteins or do not end in a typical stop codon.

#### SanntiS for building a Genbank file
This step combines the original nucleotide sequences with the cleaned protein sequences to create a GenBank format file. This format is widely used for storing and organising information about DNA sequences and their annotations. In this step, the DNA sequences and their corresponding coding regions are transformed into a format that is suitable for SanntiS.

#### Regex Find And Replace
The asterisks at the end of some protein sequences are informative but can cause issues with some analysis tools. In this step, we remove these asterisks to produce a clean protein FASTA file, making it ready for further analysis.

### InterProScan
InterProScan is a tool that helps identify and predict the functions of proteins by comparing them to known databases. This tool analyses the protein sequences and produces an output file containing detailed information about the possible functions, domains, and families associated with these proteins.

### SanntiS for annotating biosynthetic gene clusters
SanntiS is a tool specifically designed to detect and annotate biosynthetic gene clusters (BGCs). It uses neural networks trained on InterPro signatures to achieve high accuracy in identifying BGCs in both genomic and metagenomic datasets [1](https://doi.org/10.1101/2023.05.23.540769). A significant benefit of using SanntiS is that your results will be comparable with a large number of datasets, including over 5,000 marine metagenomic assemblies archived in the [MGnify](https://www.ebi.ac.uk/metagenomics)  resource. This tool provides valuable insights into the biosynthetic potential of organisms or environmental samples. The final output is a GFF file containing detailed BGC annotations, which can be used for further analyses or applications.

## Extra comment
Just a minor observation. The official spelling of the tool is 'SanntiS', I saw a couple entrues in the text using the 'Sanntis' spelling.


Let me know if anything else is needed from my side!

**Comment by Marie59** [comment]
@shiltemann I don't really understand why the workflow part is not working properly. Do you know why ?

**Comment by shiltemann** [comment]
@Marie59 the linter is failing because the workflow does not have a test. There are some instructions on how to do this here: http://localhost:4002/training-material/faqs/gtn/gtn_workflow_testing.html

If you need this to be merged soon we can also ignore it for now and you can update the workflow later

**Comment by Marie59** [comment]
> training-material/faqs/gtn/gtn_workflow_testing.html

But I did that ... Maybe it's because it's not named right ? I already followed the instruction to have a workflow test and I have the file here topics/ecology/tutorials/marine_omics_bgc/workflows/Marine-Omics-identifying-biosynthetic-gene-clusters-tests.yml with the folder test-data that goes with it

**Comment by shiltemann** [comment]
@Marie59 ah ok, I didn't look closely enough, I will have another look then :+1:

**Comment by shiltemann** [comment]
Hi @Marie59 ok, tests pass now. I think (?) the problem was it was expecting the test yaml file to have the same base name as the workflow file. I also removed some spaces from your test files which also gave another error.

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
ok, looks good from a technical point of view. Is it good to go from your side?

**Comment by Marie59** [comment]
> ok, looks good from a technical point of view. Is it good to go from your side?

Yes on my side it's good too now that I had santiago's review. It can be merged I think ;)

**Comment by shiltemann** [comment]
ok great :+1:  thanks a lot for your tutorial! :tada:

**Pull request merged**
