### PR TITLE
Add citations to scRNA galaxy papers

### PR DESCRIPTION
**Pull request by mtekman**
Add 2020 singlecell paper, and the 2019 paper.
   Mention the singlecell portal in relevant materials

### CODE REVIEW

**Review by hexylena — COMMENTED** [review]
Congrats on the paper!

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
the build error is an ongoing issue we're solving, not worried about it but it won't be deployed until we get that solved, sorry.

**Comment by mtekman** [comment]
> the build error is an ongoing issue we're solving, not worried about it but it won't be deployed until we get that solved, sorry.

Unrelated to this PR: 
- There is a workshop tomorrow that I was going amend some of the version links for some of the scanpy tools. I take it that this would not be possible? At the moment things just appear to work as they are with the current versions, so it's not at all a pressing issue

**Comment by hexylena** [comment]
It's since fixed, Saskia found a workaround and builds are succeeding again
so just PR any changes you want! 🎉

ons. 17. mar. 2021, 12:45 skrev Mehmet Tekman ***@***.***>:

**Comment by mtekman** [comment]
Fast and awesome as always, thanks @shiltemann @hexylena !

**Pull request merged**
