### PR TITLE
add a couple tool IDs

### PR DESCRIPTION
**Pull request by hexylena**

### CODE REVIEW

**Comment by hexylena** [comment]
@gallardoalba would you mind reviewing this quickly?

**Comment by gallardoalba** [comment]
> @gallardoalba would you mind reviewing this quickly?

Sure!

**Comment by gallardoalba** [comment]
> @gallardoalba would you mind reviewing this quickly?

Hi @hexylena, it looks fine, but the link toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/jbrowse/1.16.9+galaxy0 doesn't work. Not sure if this is a problem.

**Comment by hexylena** [comment]
Hi @gallardoalba it should work when viewed from within galaxy following [this format](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#tool-links).

**Review by shiltemann — APPROVED** [review]

**Pull request merged**
