### PR TITLE
Computational Chemistry tutorial and slides

### PR DESCRIPTION
**Pull request by chrisbarnettster**
Create slides and tutorial for computational chemistry tools.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks a bunch! Can you fix the two merge conflicts, we will review this asap.

**Comment by bgruening** [comment]
@chrisbarnettster do you know if the included images fall under an open license, so that we can re-use them?

**Comment by chrisbarnettster** [comment]
> @chrisbarnettster do you know if the included images fall under an open license, so that we can re-use them?

Great question.  A few are renders, screenshot of the terminal or the galaxy site and should be fine.
Others are from papers  - is it better then to link directly to the publishers website?

Potential issues with - 
- F6.large.png
- ja-2011-06842j_0011.jpeg
- motion_times_1-s2.0-S1471489210001463-gr1_lrg.jpg
- NCI_CCG_Genetics_Infographic_v12_top.__v100684792_httpswww.cancer.govabout-cancercauses-preventiongeneticsgenes-proteins-infographic.png
- scruct_logo.png

**Comment by bgruening** [comment]
You could check the Journal guidelines. In some cases we can simply use them in other we might need to redraw them or link out to the original one. But keep in mind that linking out is sub-optimal as we have training happening without internet connection (so offline training material).

**Comment by chrisbarnettster** [comment]
see new PR #1378

**Pull request closed without merging**
