### PR TITLE
Add plain text slides

### LINKED ISSUE #2494: Video/slide accessibility improvements
During a discussion about Galaxy a11y, https://twitter.com/DogGeneticsLLC/status/1381999606268059650 it was pointed out that we should make access to the markdown more prominent. (Perhaps we can render a plain-text without the html, but with the title slide/followup/etc?)

- [x] link to markdown from video page
- [x] link to markdown from slides themselves ('view as plain text' on cover slide?)
- [x] make a nicer view of markdown with the metadata templated out. (e.g. [this content](https://github.com/galaxyproject/training-material/blob/main/topics/epigenetics/tutorials/atac-seq/slides.html#L2))
- [x] check for alt-text for images since we have not been doing that on slides yet (yikes!)

Additionally this link was mentioned, useful for our workshop guidelines.
https://user2021.r-project.org/participation/accessibility/

### PR DESCRIPTION
**Pull request by hexylena**
This adds a plain-text slides layout which is automatically generated for every slide deck. This format should be significantly more accessible by not requiring javascript/keyboard navigation to read. 

Fixes #2494

The additional benefit of this is that missing alt-text, which could not be caught by our remark slides/checker, will now be caught! (So, this PR should take a while to pass while we fix all of the previous missing text.)

image

And here is how it looks:

image

### CODE REVIEW

**Comment by martenson** [comment]
htmlproofer complains a lot, is that expected here?

**Comment by hexylena** [comment]
Yes, it is. That's the point of this PR, to catch the 9000 times we put images into slides without alt text / with possibly broken links. This PR will take a long time to get passing :(

**Comment by hexylena** [comment]
Only 533 images left to caption. :sob: 

```
$ ag '!\[\]' -c | cut -f 2 -d: | sum-lines
533
```

**Comment by gallardoalba** [comment]
> This adds a plain-text slides layout which is automatically generated for every slide deck. This format should be significantly more accessible by not requiring javascript/keyboard navigation to read. Fixes #2494
> 
> The additional benefit of this is that missing alt-text, which could not be caught by our remark slides/checker, will now be caught! (So, this PR should take a while to pass while we fix all of the previous missing text.)
> 
> image
> 
> And here is how it looks:
> 
> image

It is a pretty nice feature. Since the speaker notes are included, perhaps it would be appropriate to encourage their inclusion as a way of expanding the information provided in the slides. I think such information can help to enrich this new feature.

**Review by gallardoalba — COMMENTED** [review]
It seems that there's a problem with the footnotes. 

Screenshot from 2021-07-13 16-27-35

**Comment by hexylena** [comment]
Unfortunately the footnote issue happens with all of the classes, so image
widths as well, it's seen on a lot of slides :/

I don't know how to solve that, I'm not sure there is a way without
reimplementing part of the remarkJS slide parser to strip out these classes
somehow, or something similar

Op di 13 jul. 2021 16:32 schreef Cristóbal Gallardo <
***@***.***>:

**Comment by hexylena** [comment]
Ready for review, whoever wants to review my 500+ image captions :grimacing:

**Comment by hexylena** [comment]
I've made some additional, unrelated (well, not really, this PR was about a11y) changes for accessibility, I learned to use a screen reader recently (because I had a light sensitive migraine) so made some improvements to make the GTN read a bit better under Android's TalkBack.

**Comment by hexylena** [comment]
added license in tutorial header to help it be more explicit for folks. Additionally it'll improve our screenshots, I really liked how EBI did it:

image

And here's ours:

image

**Review by shiltemann — APPROVED** [review]
wow! so much alt text! thanks a lot @hexylena!

**Comment by bebatut** [comment]
Thanks for that @hexylena. 

I wanted to check on the website how it looks like but I could not see the link to the plain text slides:

image

Another question: should we write a post to advertize this feature?

**Comment by hexylena** [comment]
@shiltemann had some concerns about visual clutter (especially when you have slides/video/plain text) it became a lot of icons. It's now here (and invisibly for screen readers before the dropdown at all.)

image

**Comment by hexylena** [comment]
> Another question: should we write a post to advertize this feature?

it got lost in another branch, I've written something.

**Comment by bebatut** [comment]
> @shiltemann had some concerns about visual clutter (especially when you have slides/video/plain text) it became a lot of icons. It's now here (and invisibly for screen readers before the dropdown at all.)
> 
> image

Perfect :)

**Comment by shiltemann** [comment]
and also linked to from the cover slide of each slide deck btw

**Pull request merged**
