### PR TITLE
Create histories_sharing-with-individual-user.md

### PR DESCRIPTION
**Pull request by desmond-jasper**

### CODE REVIEW

**Comment by desmond-jasper** [comment]
@annefou please i have made a pull request here

**Comment by desmond-jasper** [comment]
@beatrizserrano i would love for a review here, thanks.

**Comment by annefou** [comment]
I have the feeling this FAQ is already covered by [Sharing your History](https://training.galaxyproject.org/training-material/faqs/galaxy/histories_sharing.html)

**Comment by desmond-jasper** [comment]
i was to work on it, and mine is more channeled to sharing with individual users only.
@annefou i have not contributed for the first time.

**Comment by annefou** [comment]
> i was to work on it, and mine is more channeled to sharing with individual users only. 

I think it is covered by the FAQ I mentioned. So maybe the migration would simply to update galaxy-hub and point to this FAQ.

**Comment by beatrizserrano** [comment]
I'm closing this because it's covered already in the FAQ mentioned by @annefou. Thanks @desmond-jasper!

**Pull request closed without merging**
