### PR TITLE
Fixes for the "Basics of machine learning" tutorial

### PR DESCRIPTION
**Pull request by nsoranzo**
- Fix datatype of library files. The `sklearn_svm_classifier` only supports `tabular` files.
- Add tool ids to hands-on sections.
- Fix accessibility of a link.
- Misc small fixes/improvements.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@hexylena If this is not taken care automatically (and you are able to), it would be good to also fix the datasets' datatype (from tsv to tabular) on the EU data library: https://usegalaxy.eu/libraries/folders/F6c313b15da419682/page/1

**Comment by bgruening** [comment]
I changed the datatype. Thanks for pointing it out @nsoranzo

**Review by bgruening — APPROVED** [review]

**Comment by nsoranzo** [comment]
Thanks @bgruening ! One more thing that would be useful is to hide 2 old versions of the "Support vector machines (SVMs) for classification" tool, which come up when searching for e.g. `svms`. The versions to hide would be:
- toolshed.g2.bx.psu.edu/repos/bgruening/svm_classifier/svm_classifier/0.9
- https://usegalaxy.eu/tool_runner?tool_id=svm_classifier (locally installed?)

Thanks!

**Comment by bgruening** [comment]
Thanks @nsoranzo. This should now be fixed. Sorry it took that long.

**Pull request merged**
