### PR TITLE
added workflow for MSI imaging 1

### PR DESCRIPTION
**Pull request by subinamehta**

### CODE REVIEW

**Comment by bgruening** [comment]
ping @foellmelanie

**Comment by foellmelanie** [comment]
Thanks a lot @subinamehta, workflow looks great. If you have more feedback, please let me know.

**Comment by bedroesb** [comment]
Nice addition! Just a small comment: shouldn't the workflow be placed in a workflows folder?

**Comment by subinamehta** [comment]
Yes, I am planning to put in the workflows folder. But having a hard time finding the location. I am trying to update the links that are failing in the proteomics training network. Could you please send me a link where I can add the workflow, please!

**Comment by bedroesb** [comment]
What do you mean with links? I think placing the added workflow in a directory called ./workflows will enable the scripts to see the workflow. ( I am especially talking for the scripts  building containers/installing dependencies for tutorials)

**Comment by subinamehta** [comment]
I created a new pull request with workflow folder

**Pull request merged**
