### PR TITLE
Add translation support

### PR DESCRIPTION
**Pull request by bebatut**
To fix (at least partially): #404 

A dropdown menu to select the language is added in the topic menu and on the top of the tutorial:

screen shot 2018-11-13 at 16 51 52

screen shot 2018-11-13 at 17 04 03

The non english links redirect to Google translate. The hands-on boxes are not translated.

### CODE REVIEW

**Comment by shiltemann** [comment]
\o/

**Comment by bebatut** [comment]
I fixed the links to Google translate for other languages than french and add a split dropdown menu:

screen shot 2018-11-13 at 18 03 44

**Comment by manabuishii** [comment]
COOL!!

**Comment by bgruening** [comment]
Muha, magic! Biohackathon for the win!

**Pull request merged**
