### PR TITLE
Transcriptomics: changing the slides and fixing some parameters in the ref_based tutorial

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I worked on the RNA-Seq slides to try to make clearer the objectives of RNA-Seq:
- Addition of some images
- Rearrange some slides

I also fixed some missing/wrong parameters in the ref-based tutorial

Bérénice

### CODE REVIEW

**Comment by nsoranzo** [comment]
The `Intron` label in topics/transcriptomics/images/RNA-Seq-alignment.png seems to refer to an exon.

**Comment by bebatut** [comment]
Good point. I can fix that

**Comment by nsoranzo** [comment]
Also: ` topics/transcriptomics/images/transcript_discovery.png/svg` don't seem to be used.

**Comment by bebatut** [comment]
@nsoranzo I removed the 3 images I finally did not integrate in the slides

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
