### PR TITLE
Implement automated linting

### PR DESCRIPTION
**Pull request by hexylena**
This replaces all of our custom linting with a single big `lint.rb` script that nearly everything. This is pretty boring on it's own, but it's made extremely useful by the automated PR review comments which are now possible!

Did you forget a `%` in your icon reference?

image

Or maybe you linked to the GTN rather than the specific tutorial like we'd prefer:

image

All of this is now done automatically, freeing up reviewer time to focus on the actual tutorial contents, rather than the GTN formatting.

### CODE REVIEW

**Comment by hexylena** [comment]
If you're working in VSCode it also works with the Problems tab, and will list all of the linting issues with your file :heart_eyes: 

image

**Comment by hexylena** [comment]
I'm opening this for review, importantly it only applies to *changed* files. So even though there's 1.6k "problem", it's set to only complain "on files changed in a PR" so it should be safe to merge today.

Fixes #2687

**Comment by hexylena** [comment]
```
    404 "GTN:001" - no_toc
     11 "GTN:002" - embedded youtube videos (warning, not error)
     39 "GTN:003" - using external links when internal would have worked
     52 "GTN:004" - DOIs that could have been `{% cite %}`
    151 "GTN:005" - hyperlinks with titles like "here" (as in click 'here')
    321 "GTN:006" - broken `{% ... %}` where one of the `{` or `%`s is missing. This seems to be mostly false positives due to doing things like `{% include {{ page.dir }}collab.md %}`
    131 "GTN:009" - bad tool links
    392 "GTN:018" - Most of these are false positives due to data olympics templating out tool IDs, but the rest are real.
```

**Comment by hexylena** [comment]
This will be a great contributor friendly project, if someone wants to make contributions for their hacktoberfest

image

**Review by Slugger70 — APPROVED** [review]

**Comment by bgruening** [comment]
🎆

**Pull request merged**
