### PR TITLE
Add Proteomics topic maintainers

### PR DESCRIPTION
**Pull request by shiltemann**
@foellmelanie, @PratikDJagtap and @subinamehta have kindly agreed to be topic maintainers for Proteomics topic, thanks!! :tada: 

@martenson could you add them to the @galaxyproject/training-proteomics team?

### CODE REVIEW

**Comment by shiltemann** [comment]
While I'm here, please let me know if you are still happy to be listed as topic maintainers here @bgruening @Stortebecker @blankclemens

**Comment by blankclemens** [comment]
> While I'm here, please let me know if you are still happy to be listed as topic maintainers here @bgruening @Stortebecker @blankclemens

Thank's for asking, I removed myself as a maintainer.

**Comment by shiltemann** [comment]
@blankclemens thank /you/ for having been a maintainer for this topic and all your contributions to the GTN!

**Comment by martenson** [comment]
@shiltemann done, sorry for the delay

**Comment by Stortebecker** [comment]
@shiltemann You may remove me as a maintainer. Thanks! 
@foellmelanie But do ask me please, if you have questions about something I created.

**Comment by shiltemann** [comment]
@Stortebecker will do, and thanks for all your contributions to this project!

@martenson thanks!

**Review by hexylena — APPROVED** [review]

**Comment by shiltemann** [comment]
:tada: :tada:

**Pull request merged**
