### PR TITLE
Initial version of the Upgrading Galaxy tutorial

### PR DESCRIPTION
**Pull request by Slugger70**

### CODE REVIEW

**Comment by Slugger70** [comment]
Had a stab at it. Let me know what you think.

**Comment by hexylena** [comment]
I think it's brilliant, there's a couple small formatting things i'll fix up, but it's good!

**Review by hexylena — APPROVED** [review]

**Comment by Slugger70** [comment]
There are a couple of instances where I couldn't remember how long releases are supported for.. I've marked them with **XXX** (One at the start and one at the end..)

How long do we support releases for?

**Comment by hexylena** [comment]
a year

**Pull request merged**
