### PR TITLE
Updated RabbitMQ version to one that worked for me and added a tip ab…

### PR DESCRIPTION
**Pull request by martinwolst**
…out the RabbitMQ-Erlang version issues. This is my first pull request to Galaxy training!

### CODE REVIEW

**Comment by hexylena** [comment]
We can accept this for now (welcome, we're glad to have you! thanks for the fab first contributino!) 

but we're hopeful to replace this soon with the RabbitMQ role of UseGalaxy.eu (@mira-miracoli if you have time/energy to show us how to do it with role?)

see https://github.com/usegalaxy-eu/ansible-rabbitmq/issues/1 for more details

**Review by hexylena — APPROVED** [review]

**Comment by mira-miracoli** [comment]
Sure, I will put it on my to-do list ;)

**Comment by hexylena** [comment]
Danke!!

**Comment by mira-miracoli** [comment]
This role [https://galaxy.ansible.com/usegalaxy_eu/rabbitmq](https://galaxy.ansible.com/usegalaxy_eu/rabbitmq) is depricated, We should delete it or mark it in GitHub, too.

Currently we are only maintaining [this](https://galaxy.ansible.com/usegalaxy_eu/rabbitmqserver) role.
It runs in docker, therefore it should have no dependency issues. It is the role we are also using in our [infrastructure-playbook](https://github.com/usegalaxy-eu/infrastructure-playbook)
It has a playbook [example](https://github.com/usegalaxy-eu/ansible-rabbitmq/tree/main/playbook_example), which I did not test recently, but it should work.

**Pull request merged**
