### PR TITLE
Lint for broken tool links

### PR DESCRIPTION
**Pull request by hexylena**
I've discovered a number of broken tool links.

```
topics/proteomics/tutorials/metaquantome-function/tutorial.md:100	https://toolshed.g2.bx.psu.edu/view/galaxyp/metaquantome_db/7c45aa1c9464
topics/proteomics/tutorials/metaquantome-function/tutorial.md:143	https://toolshed.g2.bx.psu.edu/view/galaxyp/metaquantome_sample/49a957fb353a
topics/proteomics/tutorials/metaquantome-taxonomy/tutorial.md:108	https://toolshed.g2.bx.psu.edu/view/galaxyp/metaquantome_db/7c45aa1c9464
topics/proteomics/tutorials/metaquantome-taxonomy/tutorial.md:151	https://toolshed.g2.bx.psu.edu/view/galaxyp/metaquantome_sample/49a957fb353a
```

@subinamehta could you please tell me what the correct tool IDs are?

### CODE REVIEW

**Comment by subinamehta** [comment]
https://toolshed.g2.bx.psu.edu/view/galaxyp/metaquantome_sample/c7745841de24
https://toolshed.g2.bx.psu.edu/view/galaxyp/metaquantome_db/85b8866f06d7

**Comment by subinamehta** [comment]
Hi Helena,

The tool just got updated, so I added that here.

Thanks,

Subina

**Comment by hexylena** [comment]
Hi Subina,

Those are the urls for the repositories. Do you have the tool IDs?

e.g. `toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_filter/metaquantome_filter/2.0.0-0`
**not** `https://toolshed.g2.bx.psu.edu/view/galaxyp/metaquantome_filter/99450519d727`

(especially the correct tool version component, not the repository revision id)

**Comment by hexylena** [comment]
This guide covers how to find the ID for a tool, if you have questions. https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#how-to-find-these-ids

**Comment by subinamehta** [comment]
https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_sample/metaquantome_sample/2.0.0-0

https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_db/metaquantome_db/2.0.0-0

**Comment by subinamehta** [comment]
toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_db/metaquantome_db/2.0.0-0

toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_sample/metaquantome_sample/2.0.0-0

**Comment by hexylena** [comment]
Perfect, thanks!

**Comment by hexylena** [comment]
This PR also uses the warnings features of github actions to annotate the tutorial output, helping contributors

image

**Review by shiltemann — APPROVED** [review]

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
thanks @hexylena!

**Pull request merged**
