### PR TITLE
Update maker workflow

### PR DESCRIPTION
**Pull request by gallardoalba**
This PR includes the following modifications:

- Add best practices information
- Update _gffread_ tool version to  2.2.1.2 (previous version, 2.2.1.1. is not available in usergalaxy.org)
- Update _fasta statistics_ tool to 1.0.1 (previous version, 1.0.0, is not available in usegalaxy.org)

### CODE REVIEW

**Review by abretaud — APPROVED** [review]
Cool, thanks a lot!!

**Comment by hexylena** [comment]
oh! you added the authorship/institution information <3 I was just going to ask for that.

**Comment by gallardoalba** [comment]
> oh! you added the authorship/institution information <3 I was just going to ask for that.

Yes, I'm going to include it in the IWC; I'm looking for very small test datasets :)

**Comment by hexylena** [comment]
Awesome!

**Review by hexylena — APPROVED** [review]

**Pull request merged**
