### PR TITLE
Added GalaxyP tutorial workflows

### PR DESCRIPTION
**Pull request by Stortebecker**
Hejhej,

I added workflows for the existing tutorials "Database Handling" and "Protein ID (using SG/PS)", completely with description and images. 

Cheers, Flo

### CODE REVIEW

**Comment by bgruening** [comment]
@Stortebecker can you name the images *_*_*.png. Not sure why the ending is capital letter always and dashes are ok, but can be error prone. I think it is better to just use `_`.

**Comment by Stortebecker** [comment]
Done.

**Comment by bgruening** [comment]
And merged!

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
