### PR TITLE
Moving FAQ - Updating user information

### PR DESCRIPTION
**Pull request by Melkeb**

### CODE REVIEW

**Comment by jennaj** [comment]
This is good

**Comment by Melkeb** [comment]
Thanks for the comments. Forgot Password is not included in this FAQ because it looked like a different issue that updating/ changing user preferences. I will add common phrases on the FAQ that people might search for.

**Comment by Melkeb** [comment]
I updated the area, and included "email changes" in a sentence as well as information about updating current account at the bottom of the FAQ.

**Review by beatrizserrano — APPROVED** [review]
This PR looks good to me, so unless I'm missing something (@shiltemann @hexylena), we could merge :) Thank you @Melkeb 🎉

**Pull request merged**
