### PR TITLE
Change the concatenate tool ID from cat1 to tp_cat

### PR DESCRIPTION
**Pull request by yvanlebras**
as only this one accept the multiple selection

### CODE REVIEW

**Review by bgruening — DISMISSED** [review]

**Comment by yvanlebras** [comment]
Sorry @bgruening it appears I dismiss your review through a commit..... Can you rereview please? Really sorry for extra work...

**Review by bgruening — APPROVED** [review]

**Comment by yvanlebras** [comment]
Thanks !!! Can start communicating about !

**Comment by martenson** [comment]
testing CI migration

**Comment by yvanlebras** [comment]
It seems there is travis issues linked to missing gtn files others than ecology related. Can we merge or not?

**Comment by yvanlebras** [comment]
@martenson Hope all is ok on your side. Is this normal this reopening and Travis issues ?

**Comment by yvanlebras** [comment]
... and I just see that "available in these Galaxies" dont cite usegalaxy.eu but now it is ready on it ;)

**Comment by hexylena** [comment]
I'm merging, travis is being weird lately but this looks fine.

**Comment by yvanlebras** [comment]
Thank you Helena !

**Comment by martenson** [comment]
@yvanlebras no it is not common, sorry for taking your PR hostage and creating the confusion. I should've created a test PR for my purposes. Apologies.

**Pull request merged**
