### PR TITLE
De novo rad seq

### PR DESCRIPTION
**Pull request by polkhe**
- added tour

- screenshot has wrong parameters (0.5 instead of 0.75 etc.)

### CODE REVIEW

**Comment by bebatut** [comment]
ping @yvanlebras

**Comment by bgruening** [comment]
ping @yvanlebras - I know you are in RAD-seq mode ;)

**Comment by yvanlebras** [comment]
https://software.broadinstitute.org/software/igv/AlignmentData is ok
https://www.broadinstitute.org/igv/ is ok too
http://software.broadinstitute.org/software/igv/ is ok too

the same for: 

https://software.broadinstitute.org/software/igv/Sashimi
https://www.broadinstitute.org/software/igv/third_party_tools#_blank 
https://www.broadinstitute.org/software/igv/sites/cancerinformatics.org.igv/files/images/igv_desktop_callouts.jpg
https://www.broadinstitute.org/software/igv/batch
http://software.broadinstitute.org/software/igv/UserGuide
https://www.broadinstitute.org/software/igv/Sessions
https://www.broadinstitute.org/software/igv/?q=ToolBar
http://software.broadinstitute.org/software/igv/download

**Comment by bgruening** [comment]
Thanks @polkhe and @yvanlebras!

**Pull request merged**
