### PR TITLE
Add GTN video library connection

### PR DESCRIPTION
**Pull request by shiltemann**
For events like Smorgasbord and GCC2021, we have accumulated a large collection of videos for the GTN tutorials.

As part of the current BioHackathon, @hexylena, myself and the Gallantries team have been working on collecting these videos in a [GTN Video Library](https://github.com/gallantries/video-library/). (complete with [Course Builder](https://gallantries.github.io/video-library/course-builder) for easily creating your own training events!!!)

This PR detects if videos exist for a certain tutorial, and adds a link to them to the overview box. 
image

And preview of the video library pages
gtn-videolib

TODO:
- [x] Use the video library API to update json on build-time
- [x] Finalize the video library pages before merging this.
- [x] News Post
- [x] Nightly deploys to stay in sync with updates to the video library

- These videos will link to the archived versions of the tutorial closest to their creation date
- If we have multiple videos of the same tutorial, they will all be listed on the video library page

### CODE REVIEW

**Comment by millen2223** [comment]
I didn't know what is more suitable place to ask this question but I like creating videos and it seems like a project that improves GTN video's performance. Can I try record a demo screencast for a link to be added here https://galaxyproject.org/learn/interval-operations/#intersect ? Is any help in recording screencasts welcomed? Will it make any sense?

**Comment by Chinonyemildred** [comment]
Yippee!!! The video library is coming to life😁😁😁

**Comment by shiltemann** [comment]
@millen2223 the page you link to is not part of the GTN, so I am perhaps not the best person to answer your question. Did you already have an idea of what you would like to demo in your screencast?

**Comment by millen2223** [comment]
@shiltemann thank you for your reply! I see, I will look if anyone opened issues beyond this repo after I solve an issue I am stuck with at the moment:(. One idea was to make a small intro of a tool, then show example/s mentioned in tutorials. For instance, showing a task that can be solved with this tool. "Finding Overlapping intervals with the peak regions" could the first one.

**Comment by hexylena** [comment]
Should we remove the video library content from the GTN since we're including it on buildtime? It's an annoying tradeoff a bit :/

**Review by hexylena — APPROVED** [review]

**Review by hexylena — APPROVED** [review]

**Comment by shiltemann** [comment]
:tada: :tada:

**Comment by Chinonyemildred** [comment]
Amazing!! 🎉🎉🎉🎉🎉

**Pull request merged**
