### PR TITLE
[WIP] Add tutorial for differential exon usage

### PR DESCRIPTION
**Pull request by bebatut**
Still to do
- [x] Add Zenodo link when update finished
- [ ] Test the tutorial
- [ ] Fix issues like in #544
- [ ] Add workflow

### CODE REVIEW

**Comment by shiltemann** [comment]
@bebatut what is the status of this 4 year old PR? still planning on finishing it? need help? close? :)

**Comment by bebatut** [comment]
@pavanvidem do you think the differential exon usage tutorial would be useful ?

**Comment by pavanvidem** [comment]
I think we can close this. There is already a very detailed [alternative splicing analysis tutorial](https://github.com/galaxyproject/training-material/tree/main/topics/transcriptomics/tutorials/differential-isoform-expression).

**Comment by bebatut** [comment]
Great. I close it. Thanks for the answer @pavanvidem

**Pull request closed without merging**
