### PR TITLE
[Ecology] Changes sdm tut

### PR DESCRIPTION
**Pull request by shiltemann**
This recreates the PR from https://github.com/galaxyproject/training-material/pull/2964, but since the user has deleted their GitHub account, I cannot fix the merge conflicts or make changes on the original PR

ping @yvanlebras since you were going to test this

description from original PR:

> I noticed an error with the column number 51 on the Cut section, the column option that worked for me was 54. I also noticed BISON was linked to gbif, so I changed that to their current url, however BISON does have a notice their website that they will be going dark this year and merging to gbif.us, so I wasn't sure if that should be kept or not.

> I also noticed a few spelling and grammar errors so I changed them.

### CODE REVIEW

**Comment by yvanlebras** [comment]
THANK YOU very much Saskia! And thank you to the ""ghost"" contributor! Will try to look at it next week! The requested changes are not trivial, I need to verify it in details! Cheers!

**Comment by shiltemann** [comment]
@yvanlebras going through old PRs and saw this one again, any more thoughts/input?

**Review by yvanlebras — APPROVED** [review]

**Comment by yvanlebras** [comment]
THANK YOU Saskia! This is ok for me, but I think we need to come back to the GxIT as it seems to me it is not working properly if I remember a recent feedback

**Comment by hexylena** [comment]
we'll merge it now and maybe we can address the gxit separately (I think theres's an issue)

**Pull request merged**
