### PR TITLE
Update rnaseq mouse few small edits

### PR DESCRIPTION
**Pull request by mblue9**
Another few little things we spotted today, if anyone could merge this before our workshop tomorrow would be great 🙏

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@mblue9 I can not remove the trailing newline as it seems. Can you try to remove it?

**Comment by mblue9** [comment]
Yep will do! Have a couple more small edits to add too.

**Comment by mblue9** [comment]
Am done, hopefully this passes 🤞

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Hope that is in time. Good luck!

**Comment by mblue9** [comment]
Yes it is, thanks a lot!

**Pull request merged**
