### PR TITLE
Added translation to the news page on...translations

### PR DESCRIPTION
**Pull request by nomadscientist**

### CODE REVIEW

**Review by hexylena — DISMISSED** [review]

**Comment by hexylena** [comment]
do you want to make it the first part of the news item? Rather than the second?

**Comment by nomadscientist** [comment]
> do you want to make it the first part of the news item? Rather than the second?

Good idea! Done

**Review by hexylena — APPROVED** [review]

**Review by hexylena — APPROVED** [review]

**Comment by shiltemann** [comment]
Nice!

**Comment by nomadscientist** [comment]
Thanks!!!

**Pull request merged**
