### PR TITLE
change 4 lines of bioblend dev tutorial

### PR DESCRIPTION
**Pull request by cat-bro**
There's a possible paste error at step 5 of the example of writing a bioblend method.  @simonbray could you please check if this is the right change?

### CODE REVIEW

**Comment by cat-bro** [comment]
At the very last step of this tutorial galaxy is run locally with a master api key.  A bioblend test is run with pytest on the localhost galaxy using the master key.  This didn't work for me, it failed with `BootstrapAdminUser' object has no attribute '_sa_instance_state'`.  The test did work when I used the api key of a user I had created on the localhost galaxy.  I've never run tests this way so I'm not sure if it should have worked with the master key.

**Review by simonbray — APPROVED** [review]

**Comment by simonbray** [comment]
I thought I fixed this already, but apparently not - thanks @cat-bro!

> At the very last step of this tutorial galaxy is run locally with a master api key. A bioblend test is run with pytest on the localhost galaxy using the master key. This didn't work for me, it failed with `BootstrapAdminUser' object has no attribute '_sa_instance_state'`. The test did work when I used the api key of a user I had created on the localhost galaxy. I've never run tests this way so I'm not sure if it should have worked with the master key.

Which test were you running?

**Comment by cat-bro** [comment]
`tests/TestGalaxyWorkflows.py::TestGalaxyWorkflows::test_show_versions`.  I also tried `tests/TestGalaxyWorkflows.py::TestGalaxyWorkflows::test_get_workflows`.

**Comment by simonbray** [comment]
How are you getting the admin key? For me those tests are passing.

**Comment by mvdbeek** [comment]
> I've never run tests this way so I'm not sure if it should have worked with the master key.

The master api key doesn't correspond to a real user and can't for instance access or create histories, create workflows etc.

**Comment by cat-bro** [comment]
@simonbray, the issue I've described is only in the context of running the final part of this tutorial, after the 'Running the tests directly' header https://training.galaxyproject.org/training-material/topics/dev/tutorials/bioblend-dev/tutorial.html#running-the-tests-directly

**Comment by shiltemann** [comment]
Thanks @cat-bro!!

**Pull request merged**
