### PR TITLE
Add < otatadeabigail > as contributor

### PR DESCRIPTION
**Pull request by otatadeabigail**
I'm an Outreachy applicant and I'm hoping to make positive contributions.

### CODE REVIEW

**Comment by otatadeabigail** [comment]
Okay and Thank you!

**Comment by otatadeabigail** [comment]
It's correct and up to date

**Comment by bebatut** [comment]
The change does not appear here. Did you make a new commit? Did you push your changes?

**Comment by otatadeabigail** [comment]
What do I need to do now please? Sorry for the inconvenience, 😔

**Pull request merged**
