### PR TITLE
Update the contributor tutorial to add planemo

### PR DESCRIPTION
**Pull request by bebatut**
and also
- Remove the templates (duplicates with planemo)
- Add planemo to the env file (waiting now for the next Planemo release. ping @jmchilton  :smile:)

### CODE REVIEW

**Comment by jmchilton** [comment]
[Planemo 0.55.0](https://pypi.org/project/planemo/) is now available, let me know what is broken and we can try to fix it.

**Comment by erasche** [comment]
I guess we need to conda-ify this latest planemo?

**Comment by bebatut** [comment]
I am on it 😄

**Comment by bgruening** [comment]
Newest planemo is now available as conda pkg. I will restart the tests.

**Pull request merged**
