### PR TITLE
Add Citation.cff, make our news feed fancier, add top tool listing

### PR DESCRIPTION
**Pull request by hexylena**
Based on discussion with @abelsiqueira on mastodon https://tech.lgbt/@hexylena/109828518841278832 we can and should use a citation.cff, and that by providing the preferred citation, anyone who goes to copy it will receive the bib from the paper so, that works quite nicely for us.

Additionally we make the xml feed a bit prettier thanks to me seeing https://github.com/galaxyproject/galaxy-hub/issues/1857 and getting distracted on a sidequest.

### CODE REVIEW

**Comment by hexylena** [comment]
This also implements a WIP GA4GH TRS endpoint, meaning whenever all the big three are on 23.0, we'll be able to offer "Click to run" workflow buttons which is SUPER COOL.

**Comment by bgruening** [comment]
OMG, OMG, OMG! :1st_place_medal:

**Comment by hexylena** [comment]
@bgruening seems to be passing, want to hit merge and we can test if it really works? ;)

**Review by bgruening — APPROVED** [review]

**Review by shiltemann — APPROVED** [review]

**Comment by bgruening** [comment]
haha, lets see if it really works with ORG :)

**Comment by hexylena** [comment]
damn, ok, my weird hack didn't quite work. I'll try again tomorrow.

**Pull request merged**
