### PR TITLE
enabled video in the option for using galaxy tutorial

### PR DESCRIPTION
**Pull request by Alaa-Elghamry**
I was going through the tutorial of adding automatic video to slides and I created one for the " option for using galaxy "  tutorial

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @Alaa-Elghamry.
To really be able to create a video out of this slide deck, all slides should have speaker notes as explained [here](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/slides-with-video/tutorial.html#enabling-video)

**Comment by hexylena** [comment]
We'd love it if you could write those @Alaa-Elghamry ! Just imagine you are giving these slides as a presentation to an audience, and write down what you would say on each slide.

**Comment by Alaa-Elghamry** [comment]
of course! I would be happy to help but I'm not sure I fully understand
where to write my speaker notes though
I tried the tutorial but I just don't get the idea
it would be great if you could explain that to me

**Comment by bebatut** [comment]
You can speaker notes directly with the slides. See the documentation here: https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-slides/slides.html#18

**Pull request closed without merging**
