### PR TITLE
Implement redirect using JekyllRedirectFrom

### PR DESCRIPTION
**Pull request by bebatut**

### CODE REVIEW

**Comment by erasche** [comment]
It's generating bad redirects, hmm.

```
<meta http-equiv="refresh" content="0; url=http://0.0.0.0:4000/training-material/topics/transcriptomics/tutorials/scrna-preprocessing/tutorial.html">
```

not sure how to fix that

**Comment by bebatut** [comment]
I am not sure to understand what you see here as bad redirect. I tried locally and it worked

**Comment by erasche** [comment]
This was written in the `_site` folder, if that's deployed, I think it will redirect to the user's computer?

**Comment by erasche** [comment]
I was wrong, this is ready to merge. I'm sorry

**Pull request merged**
