### PR TITLE
Change the way the reports server is called

### PR DESCRIPTION
**Pull request by vazovn**
The reports uwsgi is now called by _module:_

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
This looks good, thanks for figuring that out!

**Comment by hexylena** [comment]
Feel free to add yourself to the contributors to the tutorial since you found and fixed a bug.

**Comment by hexylena** [comment]
Marking as WIP pending further updates on the issue.

**Comment by hexylena** [comment]
Hey @vazovn did you make any progress here?

**Comment by vazovn** [comment]
NO, unfortunately not. I sent a direct message to Nate and am waiting for some answer. Since you said this feature is not widely used, I do not think it is reasonable to invest more time into this. I am using gxadmin


Nikolay


===============
Nikolay Vazov, PhD
Department for Research Computing, University of Oslo
________________________________

**Comment by hexylena** [comment]
found some time because I'm sure people will hit this / have issues next week.

so the reports doesn't start, complaining of the mountpoint:

```
Jan 19 10:58:10 gat-0.eu.training.galaxyproject.eu uwsgi[723332]: invalid mountpoint: galaxy.webapps.reports.buildapp:uwsgi_app()
```

which feels odd since the mountpoint is there

```
Jan 19 10:58:10 gat-0.eu.training.galaxyproject.eu uwsgi[723332]: added /srv/galaxy/server/lib/ to pythonpath.
Jan 19 10:58:10 gat-0.eu.training.galaxyproject.eu uwsgi[723332]: invalid mountpoint: galaxy.webapps.reports.buildapp:uwsgi_app()
...
Jan 19 10:58:10 gat-0.eu.training.galaxyproject.eu systemd[1]: Failed to start Galaxy Reports.
ubuntu@gat-0:~/galaxy$ tail /srv/galaxy/server/lib/galaxy/webapps/reports/buildapp.py
...
def uwsgi_app():
    return galaxy.webapps.base.webapp.build_native_uwsgi_app(app_factory, "reports")
```

**Comment by vazovn** [comment]
Well, exactly. The reports module would not start with the line starting with


mount: ...


I replaced it with


module: ...


just as if I were starting galaxy and not reports.


But then how do we show to the proxy server where the location "/reports" is?


As I said - curl at 127.0.0.1:9001 works fine, yet the service (reports) become inaccessible fro the outside


NIkolay


===============
Nikolay Vazov, PhD
Department for Research Computing, University of Oslo
________________________________

**Comment by hexylena** [comment]
Ok, I'm really not sure what went wrong for you then.

https://gat-0.eu.training.galaxyproject.eu/reports/ it works for me?

```
location /reports/ {
    uwsgi_pass           127.0.0.1:9001;
    uwsgi_param          UWSGI_SCHEME $scheme;
    include              uwsgi_params;
}
```

and 

```
uwsgi:
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map: /static/style=/srv/galaxy/server/static/style/blue
    static-map: /static=/srv/galaxy/server/static
    static-map: /favicon.ico=static/favicon.ico
    master: true
    virtualenv: /srv/galaxy/venv
    pythonpath: /srv/galaxy/server/lib
    mount: /reports=galaxy.webapps.reports.buildapp:uwsgi_app()
    manage-script-name: true
```

so with *mount*. According to https://docs.galaxyproject.org/en/master/admin/nginx.html?highlight=proxy%20prefix#serving-galaxy-at-a-url-prefix that's how you call it if you need a subpath.

Since this works as-is on a training machine, I'm going to close this for now, it must be something else wrong on your server :(

**Pull request closed without merging**
