### PR TITLE
Topic: Data Science Survival Kit + GTN notebook Support

### PR DESCRIPTION
**Pull request by hexylena**
## GTN Jupyter Notebook Support

The best learning experience for students when covering topics like Python and R and similar is that they run the training materials directly as notebooks. We have a couple tutorials already which function like this, e.g. https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/scrna-JUPYTER-trajectories/tutorial.html which has as an initial step loading an ipynb file into Jupyter.

image showing markdown, gtn, and rendered notebook side-by-side

This takes this a step further, and allows tutorial authors to write content in GTN Markdown, have it render nicely in the GTN, and, **automatically generates a notebook** using [notedown](https://github.com/aaren/notedown) converting it directly into a reasonably ok looking notebook. Importantly the student can then run through each cell and test things out.

It automatically generates the links to mybinder.org which will let students click and immediately start running the notebook, as well as instructions on Jupyter in Galaxy.

screenshot of tutorial showing box linking to notebooks

*Current drawbacks*

The main current drawback of this approach is it necessitates removing and output preview from the markdown, which is a bit sub-optimal. However, given the ease of "launch on mybinder", I don't think this is a huge drawback, and it is something that @shiltemann and I have discussed and we think we have a plan forward to knit back the output, time and energy permitting.

ping @fpsom xref #2764 

## Bash Lessons
This builds on https://github.com/swcarpentry/shell-novice/ 

This is a thing now :) a bash tutorial in the GTN converted to a notebook which can automatically run on EU/Org(?) + mybinder.

I like that setup for the 'workshop' will just be "Open the notebook and get started" because we can have it run setup for us:

image

This is @gallantries work. Fixes https://github.com/gallantries/organisation/issues/2

### CODE REVIEW

**Comment by hexylena** [comment]
We've got some styling now!

image

**Comment by hexylena** [comment]
There's really a long section on `cd` and `pwd` which I considered to remove until I read this twitter thread and no, we're keeping it. https://mobile.twitter.com/simonw/status/1440725351949213700

**Comment by yvanlebras** [comment]
ok hmmm, it looks like amazing but I don't understand all the stemps there ;) My poor little brain.... If I want to test this [lesson ](https://github.com/galaxyproject/training-material/blob/e05bf616969f2eef82f0955d2aefba210d2f3e10/topics/introduction/tutorials/cli-basics/tutorial.md) for example, how should I start ? I don't think I have to launch a jupyter notebook on Galaxy directly on my own... I see on your previous messages you are mentioning the use of binder and potential links with Galaxy.org and/or .eu. So if I am not wrong, here you already have 2 tutorials who can benefit from autmatic creation of dedicated jupyter notebook from each md tuto file ? And then, you/we/someone/Justin Bieber will see how to propose something like a "BUTTON" to launch the notebook in Galaxy through binder ? (sorry if I am totally out of scope, I try... ;) )

**Comment by hexylena** [comment]
> ok hmmm, it looks like amazing but I don't understand all the stemps there ;) My poor little brain.... If I want to test this lesson for example, how should I start ? I don't think I have to launch a jupyter notebook on Galaxy directly on my own... I see on your previous messages you are mentioning the use of binder and potential links with Galaxy.org and/or .eu. So if I am not wrong, here you already have 2 tutorials who can benefit from autmatic creation of dedicated jupyter notebook from each md tuto file ? And then, you/we/someone/Justin Bieber will see how to propose something like a "BUTTON" to launch the notebook in Galaxy through binder ? (sorry if I am totally out of scope, I try... ;) )

Here are the compiled notebooks for your convenience :) Just upload to Jupyter on UseGalaxy.eu and check if they work and look OK! Or if they need changes

[cli-basics.ipynb.txt](https://github.com/galaxyproject/training-material/files/7236470/cli-basics.ipynb.txt)
[cli-advanced.ipynb.txt](https://github.com/galaxyproject/training-material/files/7236472/cli-advanced.ipynb.txt)

**Comment by hexylena** [comment]
The more advanced testing method is:

- install notedown
- build the GTN
- check that the notebooks render + work OK. (either locally with jupyter or on eu)

**Comment by yvanlebras** [comment]
cool!

image

It could be cool to upload the notebooks into a Galaxy history then deploy a jupyterlab instance "from an existing jupyter notebook" selecting the notebook from history instead of launching a fresh new notebook on Galaxy then upload into jupyterlab jupyter notebooks... But it doesn't seems to work now...

**Comment by yvanlebras** [comment]
It seems there is something (a picture?) who doesn't suceed to load just before the `The file system is made up of a root directory that contains sub-directories titled bin, data, users, and tmp` sentence.
image

**Comment by yvanlebras** [comment]
same here

**Comment by hexylena** [comment]
Images missing is a known bug, won't be fixed until we merge the branch :/

**Comment by hexylena** [comment]
> It could be cool to upload the notebooks into a Galaxy history then deploy a jupyterlab instance "from an existing jupyter notebook" selecting the notebook from history instead of launching a fresh new notebook on Galaxy then upload into jupyterlab jupyter notebooks... But it doesn't seems to work now...

I just tested, yeah, jeez, that's annoying, since you can still load in the data + view it. 

image

**Comment by yvanlebras** [comment]
> 
> 
> > It could be cool to upload the notebooks into a Galaxy history then deploy a jupyterlab instance "from an existing jupyter notebook" selecting the notebook from history instead of launching a fresh new notebook on Galaxy then upload into jupyterlab jupyter notebooks... But it doesn't seems to work now...
> 
> I just tested, yeah, jeez, that's annoying, since you can still load in the data + view it.
> 
> image

hmm that's a new issue.. As my point was that executing a Jupyter lab reusing a jupyter notebook already on the history doesn't work. Here, it is worth... it seems we can't upload a jupyter notebook :( but maybe this is due to the formatting of the notebooks as it was working months ago...

**Comment by hexylena** [comment]
It's due to the specific formatting of these notebooks, I think. We render
all of the markdown portions into HTML, in order to get our styling
working. And galaxy rejects it

Yvan Le Bras ***@***.***> schrieb am Di., 28. Sept. 2021,
14:48:

**Comment by shiltemann** [comment]
This is really cool!

I've added the notebooks to supporting materials list
image

And moved the topic into its own category, since the tutorials are different than most of the other scientific topics.

image

We should think about which existing R tutorials to move here (if any)

**Review by shiltemann — APPROVED** [review]
Looks great! Will merge once tests pass

Thanks to @bazante1 for reviewing/testing the content of the tutorials!

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
whoo! :tada:  thanks @hexylena!

**Comment by hexylena** [comment]
Thanks @shiltemann! This is fantastic.

**Pull request merged**
