### PR TITLE
Add maintainer teams as codeowners

### PR DESCRIPTION
**Pull request by shiltemann**
We created GitHub teams for the maintainers of each topic (thanks @martenson & @erasche!). Adding them in CODEOWNERS file for automatic review requests to this team whenever changes are made to their topic. 

All maintainers should now also have the ability to approve and merge pull requests (and please feel free to do so for your topic!)

ping @galaxyproject/training 

P.S. Please let us know if you are no longer able to be a maintainer for a topic (or if you would like to volunteer to become a maintainer)

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
Hi there! I will no longer be able to be a maintainer for topics :( I think I'm only a maintainer for the small RNA tutorial. Hopefully someone else can take over and keep the tutorial up-to-date! <3

**Comment by shiltemann** [comment]
@malloryfreeberg thanks for having been a maintainer and all your great contributions!! 

(I removed you from the maintainers list and @martenson can remove you from the GitHub team so that you won't receive these pings anymore)

**Comment by malloryfreeberg** [comment]
@shiltemann Sorry I can't be of more help! I'm just not doing this kind of bioinformatics anymore and am not up-to-date on the latest way to do these types of analyses.

**Comment by martenson** [comment]
removed from both topics, thanks!

**Comment by shiltemann** [comment]
@malloryfreeberg no worries! we're just very grateful for all you've done!

**Pull request merged**
