### PR TITLE
microbial annotation (start of)

### PR DESCRIPTION
**Pull request by AnnaSyme**
many gaps in here, just getting start of it up so I can see if I am on the right track. no images/zenodo/docker yet.

### CODE REVIEW

**Comment by bgruening** [comment]
Thats a great start!!! Can you please name this file `.md` at the end?

**Comment by bgruening** [comment]
@AnnaSyme should me merge this as a good start or do you let us know when we should review this.

**Comment by AnnaSyme** [comment]
@bgruening I think I will add more to it first, thanks. I'll close this pull request and send a new one when I've added more.

**Comment by bgruening** [comment]
You can leave it open, but let's label it as WIP (Work in progress) :)

**Pull request closed without merging**
