### PR TITLE
De novo RNAseq update

### PR DESCRIPTION
**Pull request by MoHeydarian**
This update includes:
- exchanging Cuffmerge for Stringtie-merge and GFFCompare
- updating figures and screenshots downstream of GFFCompare
- using a further downsampled subset of the original data. Only reads from 16 loci of interest to hematopoiesis are included in this version
- created a new Zenodo entry for further downsampled data
- added workflow for pipeline
- added link to feedback form 

This tutorial still needs a slide deck to complement the tutorial and  workflow, along with the Dockerfile and tools.yaml (thanks @daltis20012009!).

### CODE REVIEW

**Comment by shiltemann** [comment]
Hi @MoHeydarian 
I updated this tutorial a bit to fit in the new structure of the repo (and some fixes for better rendering of the boxes etc), please make sure everything is still ok, and let me know if you think this is ready :)

perhaps you could add some take home messages  (`key_points`) to the metadata?

**Comment by shiltemann** [comment]
thanks @malloryfreeberg, is this ready to merge now? :)

**Comment by MoHeydarian** [comment]
Hi @shiltemann,
Thanks for the changes. I swapped out one image in the Deseq2 section. Looks ready to merge.

Thanks @malloryfreeberg for the keypoints description.

**Comment by shiltemann** [comment]
Thanks @MoHeydarian, @malloryfreeberg  :) I like the feedback form btw, should we add it to the template and put it underneath every tutorial? where does the information go currently when user submits feedback?

**Comment by MoHeydarian** [comment]
Yes, I like the idea of having a link to the feedback form on every tutorial. It allows us to get feedback on quality and have some indication that the tutorials are being used. 

I made the form so the responses go to my account, this was meant to be temporary so we can have something there. I think we should start a generic Google account for the GTN that will host the feedback form and responses. What do you think?

In the meantime, anyone who wants access to edit the form and view responses, please email me with their Google email address.

**Comment by shiltemann** [comment]
sounds good to me, would you be willing to set up a generic account like that? :)

**Comment by MoHeydarian** [comment]
Yes. We now have GalaxyTrainingNetwork_at_gmailDOTcom

What is the best way to distribute the pw to GTN members? A BoF at GCC2017? :)

**Comment by shiltemann** [comment]
great, thank you! once this new account is hosting the form we can add it to all tutorials, GCC would be good place to shared credentials, sure :) in the meantime, shall I merge this with or without the link to the form (which will still go to your personal account)?

**Comment by MoHeydarian** [comment]
I just switched ownership of the form to the GalaxyTrainingNetwork account. I believe we are good to merge!

Thanks Saskia!

**Comment by shiltemann** [comment]
perfect! thanks!

**Pull request merged**
