### PR TITLE
Support mathematical expressions written in LaTeX

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I added support for mathematical expressions written in LaTeX: they will be rendered using [MathJax](https://www.mathjax.org/)

Bérénice

### CODE REVIEW

**Comment by shiltemann** [comment]
cool! :) ..I tried to add an example math expression to the tutorial, but it was not working for me locally, what am I doing wrong?

**Comment by shiltemann** [comment]
hmm, this is what my console says: https://www.mathjax.org/cdn-shutting-down/

**Comment by shiltemann** [comment]
(but even with one of the suggested updated links it does not work for me)

**Comment by bebatut** [comment]
@shiltemann Strange!
I added an example in the content tutorial. Can you check if it correctly rendered, please?
Otherwise, can you send me a snapshot of how it is rendered?

**Comment by shiltemann** [comment]
ok, it works now, may have been a script blocker orso on my end, sorry for the confusion, looks great :)

should we switch to the cloudflare link https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js as suggested in t https://www.mathjax.org/cdn-shutting-down/ ?

**Comment by bebatut** [comment]
I switched!

**Comment by shiltemann** [comment]
great, thanks!

**Comment by bgruening** [comment]
You both just rock! Can't follow with all the good stuff here!

**Pull request merged**
