### PR TITLE
Covid-19 analyses topic -> Virology

### PR DESCRIPTION
**Pull request by bedroesb**
This PR serves as a starting point for the Covid-19 analyses/ workflows found on https://covid19.galaxyproject.org/ .

I am planning to add everything that is on https://covid19.galaxyproject.org/ but for the text itself I will need the help of other people. I know that @lynnlangit  already proposed to help.

This topic will include 6 tutorials. @hexylena and @shiltemann how do you think we can work on this the best way? 

@bgruening This is only the backbone, will add more as soon as possible.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Could this be part of https://github.com/virtual-biohackathons/covid-19-bh20/wiki (and of https://github.com/virtual-biohackathons/covid-19-bh20/wiki/Workflows#galaxyprojectsars-cov-2 in particular) ?

**Comment by bgruening** [comment]
ping @wm75

**Comment by bgruening** [comment]
Thanks @bedroesb awesome start! Hopefully, we have this done for the hackathon @nsoranzo!

**Comment by nsoranzo** [comment]
Cool, in case we will find something else to work on!

**Comment by wm75** [comment]
Hmm, I like the idea, but as much as I can see the point of having these tutorials bundled under one topic, such a structure seems to collide with how the GTN material is organized in general.
If you look at the other topic, they are all analyses techniques, not biological research areas.

Following that structure the different parts of https://covid19.galaxyproject.org/ should rather live in different existing topics (like Assembly and Variant Analysis. One could put a covid-19 label on all individual tutorials to make them more findable.

I understand that this may seem less attractive at first, but I think not just duplicating the info available at https://covid19.galaxyproject.org/, but presenting the same concepts in restructured form could also be seen as a reason why you'd want to have this in the GTN in the first place.

Just my personal view. Maybe @shiltemann @hexylena @bebatut disagree with me?

**Comment by hexylena** [comment]
I agree wholeheartedly with @wm75. I wrote my own response but his is more clear.

I understand that y'all are doing this because y'all want visibility; the ability to link to the gxy/training/virology and have everything in one place, but you've got that on numerous other places already and where you do want to link to the training materials you can re-use something like is on https://usegalaxy-eu.github.io/index-rna.html#training for the interim.

I would rather see a solution like tagging things covid19 and fixing the search (preferrably TeSS integration, otherwise LunrJS et al) to allow searching across topics properly. In the future when we do curricula (as part of gallantries), we can use that as well.

**Comment by bedroesb** [comment]
This PR was made specifically to have this discussion. I heard that there was interest in `in depth` tutorials for the covid-19 analyses, but did not yet see any movement around it here on GTN. Happy to see now what the visions are.

**Comment by hexylena** [comment]
@bedroesb great that you want to contribute these, super exciting. Thanks for being open to alternate structures :)

**Comment by frederikcoppens** [comment]
What is best from the user point of view ? The visibility should serve that.

I agree fixing the search is the more scalable option, but this might not be easily done in the way you want / need. I'm not up-to-date with the trajectories in TeSS, not sure this is a viable option at this point (development effort will now go to other things in those teams, quite sure of that). 

A topic is indeed somewhat unconventional, which kind of fits the times, but might be easiest to make them findable as a set. Yes, we'll probably need to refactor over time to a more scalable approach.

**Comment by shiltemann** [comment]
This PR: https://github.com/galaxyproject/training-material/pull/1943 should provide search functionality across topics, and supports sharing an overview of all covid19-tagged tutorials by url, e.g. `https://training.galaxyproject.org/search?query=covid19`

**Comment by hexylena** [comment]
Looks like it is live @shiltemann https://training.galaxyproject.org/search?query=covid19 :)

**Comment by shiltemann** [comment]
closing this since the search option should provide the desired functionality, thanks all for the discussion!

**Pull request closed without merging**
