### PR TITLE
Updated prokka workflow to newest tool versions

### PR DESCRIPTION
**Pull request by almahmoud**
Updated tool versions to `prokka 1.14.5` and `jbrowse 1.16.5+galaxy6`. Workflow created from history in Galaxy 20.01

### CODE REVIEW

**Comment by bedroesb** [comment]
please add "tags": [	 
    "genome-annotation"	 
  ] to solve the travis build problem.

**Comment by almahmoud** [comment]
Done. Thank you!

**Comment by shiltemann** [comment]
looks good @almahmoud! could you resolve the conflict? (let me know if you need help with that)

**Comment by almahmoud** [comment]
Done! Thank you!!

**Comment by bedroesb** [comment]
@almahmoud Sorry for the Travis error again. Since #1724 and #1715  it is mandatory for a workflow on GTN to have the correct tags and annotation (This started during this PR). I am planning to update planemo this week so it has the same linting capabilities and you can test it easily in advance. The only thing you have to add is to the annotation attribute is the title of the tutorial (like in the original workflow):

```json
"annotation": "Genome annotation with Prokka"
```

Sorry for these details, but we hope that if these workflows are than added to an instance, people will find them back easier.

**Comment by almahmoud** [comment]
Thanks for all the reviews. Wondering if any other changes are needed or if we can get this merged!

**Pull request merged**
