### PR TITLE
Clip-Seq tutorial: Updated cutadapt instructions from v1.6 to v4.0

### PR DESCRIPTION
**Pull request by tuncK**
Adaptation for the change in the graphical interface over time, supposed to perform the same action with same results.

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
Welcome @tuncK, nice to see you here :)

Please do not delete the gemfile and the swagger one.

**Comment by tuncK** [comment]
I am actually not deleting/modifying them intentionally, Dr. Jekyll (make serve) crashes on 1st attempt, subsequent attempts succeed but this is the by product. Yet to figure out why.

**Comment by bgruening** [comment]
This is true, just do not commit those changes. Its how the Makefile works imho.

**Review by bgruening — APPROVED** [review]
Very cool, thanks @tuncK Please add yourself as a contributor to the repo.

**Pull request merged**
