### PR TITLE
Moving FAQ - Adjusting identifiers or input source for any mixed sourced data

### PR DESCRIPTION
**Pull request by Melkeb**
This FAQ is part of [Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/). Even after separating the FAQs this content is still too long :(

### CODE REVIEW

**Comment by beatrizserrano** [comment]
> This FAQ is part of [Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/). Even after separating the FAQs this content is still too long :(

Indeed, I'd like @jennaj to look at it, she may have ways to summarize or remove non-relevant information

**Comment by jennaj** [comment]
Let's drop this section. People can find the information in Galaxy Help plus there are ways to get this fixed. 

Change these FAQ sections in the hub source webpage to point to the "Galaxy FAQs" with a single replacement link (top level "Galaxy FAQs", not a specific FAQ) and we can consider it a "done" FAQ.

You effort is appreciated, and this should count

**Review by annefou — APPROVED** [review]
Thanks for adding the issue. I think it is all good.

**Comment by annefou** [comment]
Sorry for the confusion. 
My comment was about the fact that your effort should count! 
Let's close this issue and thank you for your effort.

**Pull request closed without merging**
