### PR TITLE
svg from ascii

### PR DESCRIPTION
**Pull request by astrovsky01**
Versions of all ascii figures in the original presentation have been recreated as svg files.

### CODE REVIEW

**Comment by erasche** [comment]
1. Would you mind moving your images into the `topics/transcriptomics/images/` folder?
2. Do you plan to update the slides as well?

**Comment by mtekman** [comment]
Hey @astrovsky01 thanks for doing this!

Can you please put the image folder into the `training-material/topics/transcriptomics/images/` directory?

**Comment by mtekman** [comment]
@erasche I can update the slides, I only asked @astrovsky01 to update the graphics

**Comment by erasche** [comment]
Sounds good!

**Comment by astrovsky01** [comment]
@erasche did you mean contributors to the presentation or to galaxy training? Because, if the presentation, yes please. If training, I don't feel like I did quite enough yet to be on the contributors overall just yet.

**Comment by erasche** [comment]
@astrovsky01 whichever you're comfortable with. This is a useful contribution and we're happy to have you added to the overall list too.

**Comment by mtekman** [comment]
@astrovsky01 every review and every contribution matters -- I'm adding you whether you want to be or not :+1:

**Comment by astrovsky01** [comment]
@erasche if you think so, then I'll join the contributors list. Thanks!

**Comment by mtekman** [comment]
Nice I'll add you to the next commit with the changes added into the slides

**Comment by mtekman** [comment]
@astrovsky01 @erasche I was not able to commit to this PR so I forked off master and made another PR.

**Comment by astrovsky01** [comment]
Just got the email. I'll close this pr.

**Pull request closed without merging**
