### PR TITLE
Add<Enchanteur14>as contributor

### PR DESCRIPTION
**Pull request by Enchanteur14**
I would like to work on the UI of this page, this is because I had an issue navigating though and some other persons must have had the same issue. It is not very user friendly, I raised an issue on it and it can be found here: https://github.com/galaxyproject/galaxy/issues/12862

### CODE REVIEW

**Comment by hexylena** [comment]
Hi @Enchanteur14 that is a Galaxy issue (not a Galaxy Training Network issue) and thus we cannot be very helpful there :(  You can work on it, but it will require a lot of javascript knowledge to make changes to that interface.

**Comment by Enchanteur14** [comment]
Oh ok I understand... I thought is something a UI designer would implement first before the front end developer

**Comment by hexylena** [comment]
UI Suggestions are always welcome! We don't have anyone who only has the job of UI designer so I did not even consider it, but if you have suggestions for making that UI better please share them :)

**Comment by Enchanteur14** [comment]
Ok I'll drop my suggestions on the UI soon

**Pull request closed without merging**
