### PR TITLE
Pulsar to py3k

### PR DESCRIPTION
**Pull request by hexylena**
:us::fireworks::us::fireworks:

### CODE REVIEW

**Comment by hexylena** [comment]
https://github.com/galaxyproject/ansible-pulsar/pull/6 needs to be merged / tagged 1.0.0 (breaking changes)

**Comment by hexylena** [comment]
This almost works, pending the issues with requests currently being debugged.

**Comment by Slugger70** [comment]
Are we not using the pip install so as to get the latest changes Marius was working on?

**Comment by hexylena** [comment]
> Are we not using the pip install so as to get the latest changes Marius was working on?

no, per some discussion it was removed from the role, figuring that we could just use the proper release procedure, but I guess we'll need to use a workaround here.

**Comment by natefoo** [comment]
We can pip install from git+https github, right?

**Comment by hexylena** [comment]
Should be. If not i get to back out my changes in ansible-pulsra.

**Comment by hexylena** [comment]
```
pulsar_package_name: git+https://github.com/galaxyproject/pulsar@commit#egg=pulsar-app
```

**Pull request merged**
