### PR TITLE
Replace site.url by site.baseurl

### PR DESCRIPTION
**Pull request by bebatut**
To limit errors of htmlproofer, particularly when new content is added (as mentioned in #546)

### CODE REVIEW

**Comment by bebatut** [comment]
I am not sure it will really work... I need to check a bit more

**Comment by bebatut** [comment]
I made some extra changes:
- Replace all the `site.url` by `site.baseurl`
- Split the URL into `site.url` (with https://galaxyproject.github.io/) and `site.baseurl` (with "/training-material")
- Update the tests, the pdf generation, ... to fit to that

Now, it should not depend on if sth is already on the main website (specially for the tests during addition of new tutorials) and it makes also easy to deploy on a fork for example (not always referring to the main website)

**Comment by shiltemann** [comment]
looks good @bebatut ..if I understand correctly you will now have to navigate to `localhost:4000/training-material` when running this locally right? could you update tutorial `create-new-tutorial-jekyll` to reflect this?

**Comment by bebatut** [comment]
@shiltemann I updated the tutorials too! Thanks for spotting it!

**Comment by bebatut** [comment]
Thanks @shiltemann

**Pull request merged**
