### PR TITLE
[Introduction] Short intro to Galaxy slides

### PR DESCRIPTION
**Pull request by shiltemann**
I often find myself wanting a shorter and simpler introductory slide deck for the audiences I teach, so I've added such a slide deck to the "Short intro to Galaxy" tutorial (I hope that's ok @AnnaSyme!)

TODO:
 - [x] Add speaker notes suitable for video conversion

### CODE REVIEW

**Review by hexylena — DISMISSED** [review]
This is a fantastic improvement! I love this so much more than the current intro slide deck.

- short & concise sentences, way better for diverse learners
- the gifs are lovely
- the organisation is much better with the flow of "find a tool, run, see results, workflow, visualise."

The normal intro slides can definitely be overwhelming for some of our users

**Comment by AnnaSyme** [comment]
Great idea!

**Comment by shiltemann** [comment]
@hexylena could you check the speaker notes for suitability for video conversion?

**Review by hexylena — APPROVED** [review]
The audio all sounds good! I think it's ready to go for tomorrow.

I'll work on a couple bugs on my end and we'll enable the video for this one soon :)

**Pull request merged**
