### PR TITLE
Moved FAQ Need more space for my work

### PR DESCRIPTION
**Pull request by andreasSune**

### CODE REVIEW

**Comment by beatrizserrano** [comment]
Thanks @andreasSune. I'm afraid that this is a group of FAQs rather than just one, and they have been covered already (or at least most of them if I remember correctly). Sorry :(

**Comment by annefou** [comment]
@andreasSune This is probably a bit confusing because we did not know at the beginning how to handle groups of FAQs. We agreed later on that the best is to move FAQs one by one but probably failed to communicate it clearly. Sorry for that.

**Comment by andreasSune** [comment]
Thanks @beatrizserrano and @annefou . Can i work on another FAQ to make a new pull request? 
For example, these ones : [Preparing and using a Custom Reference Genome or Build](https://galaxyproject.org/learn/custom-genomes/)
[Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/)
[Extended Help for Differential Expression Analysis Tools](https://galaxyproject.org/support/diff-expression/)
They have not been moved yet.

**Comment by beatrizserrano** [comment]
> Thanks @beatrizserrano and @annefou . Can i work on another FAQ to make a new pull request? For example, these ones : [Preparing and using a Custom Reference Genome or Build](https://galaxyproject.org/learn/custom-genomes/) [Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/) [Extended Help for Differential Expression Analysis Tools](https://galaxyproject.org/support/diff-expression/) They have not been moved yet.

sure, you can! just make sure that it's not covered already in any other FAQ and that there's no PR open :)

**Comment by andreasSune** [comment]
Hi, @beatrizserrano , @annefou . Please can you review this PR [https://github.com/galaxyproject/training-material/pull/3419](https://github.com/galaxyproject/training-material/pull/3419) ??

**Pull request closed without merging**
