### PR TITLE
Fix another yml

### PR DESCRIPTION
**Pull request by abretaud**
Just as #2225 with another yml (tested now, no new similar pr hopefully)

### CODE REVIEW

**Comment by hexylena** [comment]
How are you testing? Is there something we should add to the linting?

**Comment by abretaud** [comment]
I'm testing with https://github.com/galaxyproject/training-material/blob/master/bin/mergeyaml.py
I could add a GA step to run it, sure
(which I use to update data libs on my instance using something derived from https://github.com/usegalaxy-eu/shared-data/)

**Comment by hexylena** [comment]
That'd be ace! Cheers!

**Comment by hexylena** [comment]
We can probably make the linter be less strict, for what it's worth? Or, if it's easier, if `bin/merge-yaml` crashes when running, then, we could just use that as the test?

**Comment by abretaud** [comment]
Yes, I hoped for a cleaner output with yaml-lint, but it's not doing what I want apparently... I will switch to the merge script yep

**Comment by abretaud** [comment]
Ready, you might want to squash my mess ;)

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
thanks for adding this!

**Pull request merged**
