### PR TITLE
Refactor CSS to more look like the "Hub"

### PR DESCRIPTION
**Pull request by willdurand**
Hi there!

I did a complete CSS redesign (and a bit of HTML too) to match the Galaxy Hub look and feel. It is deployed here: http://williamdurand.fr/training-material/, so you can test it. Emoji (like `:stuff:`) are not rendered as I used `gh-pages` to build the website (neither Travis) but it is working.

I tried to come up with the smallest CSS possible (well, SASS actually but it is built-in in Jekyll). Therefore, all the credits go to Bootstrap. It is now fully responsive and should be slightly more readable. I changed the color scheme for the tutorial boxes with @bebatut and the help of http://paletton.com.

The PR gets pretty big, next chunk will be about replacing the Emoji icons in the "tutorial boxes" to FontAwesome icons, and then maybe redesign other parts. Let me know what you would like to do next!

🔥 Test it at: http://williamdurand.fr/training-material/

---

The logo (top left corner) was updated in https://github.com/galaxyproject/training-material/pull/463/commits/2481e59f46b81d91f320dc3b3ad7136209e58be5.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @willdurand!

@galaxyproject/training can you please vote here if you think this is good to go and an improvement to the old style.

**Comment by martenson** [comment]
💯

**Comment by jxtx** [comment]
For maintainibility, could we share a single set of base stylesheets between hub and here (and may end even Galaxy itself)?

**Comment by willdurand** [comment]
> For maintainibility, could we share a single set of base stylesheets between hub and here (and may end even Galaxy itself)?

The base stylesheet is Bootstrap I guess. See the [`main.scss`](https://github.com/willdurand/training-material/blob/refactor-css/assets/css/main.scss) file, it is very specific to the tutorials.

**Comment by martenson** [comment]
@jxtx That would probably mean bringing LESS to the build process to hub and here?

**Comment by jxtx** [comment]
There is definitely stuff that is custom, but if we based it off the existing Galaxy styles then the bar sizes would match, fonts, base colors, etc.

**Comment by jxtx** [comment]
(Also, I don't t care about less vs sass, we should just use one thing everywhere).

**Comment by willdurand** [comment]
Yup, this can be done later anyway, especially if it involves Galaxy and Hub. The idea was to get rid of the old CSS and making the website a bit more appealing/responsive.

**Comment by jxtx** [comment]
Fine with merging this now, but let's keep going!

**Comment by nsoranzo** [comment]
Looks sleek! I noticed a couple of issues:
- I found a few "500 Internal Server Error", e.g. http://williamdurand.fr/training-material/topics/assembly/
- the "hat" logo is now used for "Hands-on", while previously a similar "hat" logo was used for "Slides", maybe that can be confusing?

**Comment by willdurand** [comment]
@nsoranzo GitHub is having troubles again (for the 500)

**Comment by willdurand** [comment]
> the "hat" logo is now used for "Hands-on", while previously a similar "hat" logo was used for "Slides", maybe that can be confusing?

Yes. New logo for slides is the one from Slideshare, which seems to make more sense that the hat. Do you think we should switch back to the previous logos?

**Comment by nsoranzo** [comment]
> Yes. New logo for slides is the one from Slideshare, which seems to make more sense that the hat. Do you think we should switch back to the previous logos?

Don't know, mainly raising the point for discussion. Maybe a mouse logo for the tutorial?

**Comment by willdurand** [comment]
This is a good point! Here are all the available icons: http://fontawesome.io/icons/ 😸

**Comment by bgruening** [comment]
What about http://emojipedia.org/female-teacher/

**Comment by willdurand** [comment]
I had that in mind too but read in #304 that FontAwesome should be preferred.

**Comment by martenson** [comment]
For training site we can afford to expand to other icon libraries I believe.

**Comment by bebatut** [comment]
In the navbar, the emoji will look weird. I thought it would be better not having 2 different icons for same things and having icons in the navbar adds a visual hint

**Comment by nsoranzo** [comment]
@willdurand What about http://fontawesome.io/icon/laptop/ for tutorials?

**Comment by jxtx** [comment]
For getting the styles more uniform, all sites could start with this as a base: https://github.com/jxtx/galaxy-bootstrap

That's where the styles in Galaxy proper came from. It needs to be updated and packaged with all the modern stuff, but there it can produce a bootstrap.min.css with Galaxy styles ready to use.

**Comment by willdurand** [comment]
Just replaced the navbar logo with a better one :)

**Comment by bebatut** [comment]
ping @galaxyproject/training: we would like to have more feedbacks 😄

**Comment by shiltemann** [comment]
I like it! thanks a lot @willdurand :)

**Comment by willdurand** [comment]
(rebased)

**Comment by bgruening** [comment]
I think this was open long enough and I haven't heard any negative things - also counting the :+1: here is a clear `merge this` - and here we go!

Thanks @willdurand and all others for feedback. Keep the PRs coming!

**Pull request merged**
