### PR TITLE
attempt to fix heroku review apps deployment

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by martenson** [comment]
The build log seems fine, this might actually be us hitting unverified account heroku limit. I will see what I can do with it.

**Comment by martenson** [comment]
someone with better Ruby knowledge might need to have a look here

**Comment by willdurand** [comment]
Well, I think it makes sense since https://github.com/galaxyproject/training-material/pull/750 removed `Gemfile` and `Gemfile.lock` and bundler support.

Heroku does not know which stack to use or tools to install. I think the `Gemfile`/`Gemfile.lock` as well as Bundler support should be re-added because there is no reason not to have them.

**Comment by martenson** [comment]
I was curious why gemfile is not in the tree.

**Comment by willdurand** [comment]
> I was curious why gemfile is not in the tree.

Yeah, hopefully it was a mistake and not the cause of some install errors so that we can re-add these files soon.

**Comment by martenson** [comment]
this has been remedied via https://github.com/galaxyproject/training-material/pull/1485

**Pull request closed without merging**
