### PR TITLE
Papercuts training Understanding Galaxy history system updated

### PR DESCRIPTION
**Pull request by gallardoalba**
All figures have been updated to adjust the training to the new color scheme and the incorporated modifications.

### CODE REVIEW

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/training-material/issues/2074

@gallardoalba there is a merge conflict.

**Comment by gallardoalba** [comment]
@bgruening solved (I think)

**Comment by bgruening** [comment]
Yes thanks!

**Review by bgruening — COMMENTED** [review]
* list-pairs.png looks way different, wrong image?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
fixes #2074

**Comment by bgruening** [comment]
Thanks @gallardoalba!

**Pull request merged**
