### PR TITLE
Suggestion based on #2970 issue

### PR DESCRIPTION
**Pull request by millen2223**
@hexylena I added css property to make contributors-badge be aligned with other contributors

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
This looks good @millen2223! Thanks for such a quick easy fix.

Github tells me you're a first time contributor, would you like to add your name to the CONTRIBUTORS.yaml file in the GTN?

**Comment by millen2223** [comment]
@hexylena thank you! yes, I'd like to:)

**Comment by shiltemann** [comment]
> @hexylena thank you! yes, I'd like to:)

You can add it to this PR, or make a separate PR where you add yourself to the `CONTRIBUTORS.yaml` file, up to you

And thanks for the fix!

**Comment by millen2223** [comment]
@shiltemann, thank you! I didn't know that I can add it here, I will try

**Pull request merged**
