### PR TITLE
New training material - Ai4Life

### PR DESCRIPTION
**Pull request by cfusterbarcelo**
# Ai4Life Training Mateiral

### Example Slide Deck
These slides have been removed. 

### BioImage Model Zoo: Advanced models in one-click
Contains the slides or training material to get into the BioimageModelZoo. Changed to appear on the GTN website automatically. 

### Welcome to the BioImage Model Zoo
New slides for getting to know the [bioimage.io website](https://bioimage.io/#/). 

**Note:** I can't get the video to be automatically generated from the slides. I've been testing it but I can't find what is wrong. 

## Others
Fix invalid path error in Git when checking out repository in Windows (":" is not an allowed character).

### CODE REVIEW

**Comment by hexylena** [comment]
> Note: I can't get the video to be automatically generated from the slides. I've been testing it but I can't find what is wrong.

how are you trying to do this? The process should be 100% automatic once it's merged into this repository, no action should be required (unless you just want to preview the video).

**Comment by cfusterbarcelo** [comment]
> > Note: I can't get the video to be automatically generated from the slides. I've been testing it but I can't find what is wrong.
> 
> how are you trying to do this? The process should be 100% automatic once it's merged into this repository, no action should be required (unless you just want to preview the video).

Hi! I just write the `video: true` at the beginning of the slides as indicated. I am using GitPod to preview it before doing the pull request and I can't see the videos. Thanks!

**Review by hexylena — COMMENTED** [review]
Overall this looks great! We can merge this and the video should be recompiled tomorrow at noon.

**Comment by hexylena** [comment]
> Hi! I just write the video: true at the beginning of the slides as indicated. I am using GitPod to preview it before doing the pull request and I can't see the videos. Thanks!

Ok, in that case it is expected that the video is not available :) Compiling the video takes 5-10 minutes, and requires access to our AWS keys to generate the audio components. Thus they are only generated for merged PRs.

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
@cfusterbarcelo videos are now live:

- https://training.galaxyproject.org/videos/watch.html?v=ai4life/tutorials/welcome-bioimageio/slides
- https://training.galaxyproject.org/videos/watch.html?v=ai4life/tutorials/getting-started/slides

Currently we randomly pick a voice every time the video is updated, but if there's one you find you like, we can ensure that the video always renders with that voice. (There's currently no "gallery" of the voices, I'll see if I can fix that tomorrow.)

if you want to re-upload to youtube or elsewhere you're of course welcome to :)

- https://training.galaxyproject.org/videos/topics/ai4life/tutorials/getting-started/slides.mp4
- https://training.galaxyproject.org/videos/topics/ai4life/tutorials/welcome-bioimageio/slides.mp4

**Pull request merged**
