### PR TITLE
Improve Navigation to view tutorial materials in other languages.

### PR DESCRIPTION
**Pull request by Chinonyemildred**
I have been able to input the explanatory line and edited the CTA, and more! to More Languages as decided in Issue #3002 

I found it a little difficult to add an icon to the config.yml file, @hexylena  can you please add it, so I can add the icon to the navigation bar as we decided.

### CODE REVIEW

**Comment by hexylena** [comment]
I've pushed the icon to your branch! Now you can use `{% icon translations %}`

(And at the end when the PR is done I will revert the change to `api/swagger.json` since that is automatically generated and does not need to be included in the repo.)

**Comment by Chinonyemildred** [comment]
I tried to edit it here on github but I couldn't do a live preview to see how it looked. So I canceled the changes. I'll work on it in gitpod instead.

**Comment by Chinonyemildred** [comment]
I couldn't work on it because I fell sick. I've added it now and it works great.

What do you think?

**Comment by Chinonyemildred** [comment]
Are the changes good to go? :)

**Comment by hexylena** [comment]
I'm sorry I'll get a chance to look at it tomorrow @Chinonyemildred, it was a busy day! Overall I'm sure it's fine, and I'll make any remaining changes need and get it in tomorrow :)

**Comment by Chinonyemildred** [comment]
Okay, that works great. Thank you!❤

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
Ok this generated a complex merge conflict. I will look at it tomorrow :( but it is ready to go from my side.

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
Fantastic, thanks so much @Chinonyemildred !

**Comment by Chinonyemildred** [comment]
Thank you @hexylena!

**Pull request merged**
