### PR TITLE
Update short introduction tutorial with interface changes

### PR DESCRIPTION
**Pull request by bebatut**

### CODE REVIEW

**Comment by wm75** [comment]
Would it be simpler and avoid merge conflicts to contribute to #3858 ?

**Comment by bebatut** [comment]
I would need the changes for tomorrow's workshop. And it seems there is not much overlap

**Comment by wm75** [comment]
Makes sense. I'll leave this up to @hexylena then.

**Comment by hexylena** [comment]
it's fine. I don't have energy to deal with finishing #3858 in the next few hours, so, I guess merge this and I'll deal with the conflicts then.

**Review by hexylena — APPROVED** [review]

**Comment by bebatut** [comment]
Sorry for adding to your workload @hexylena

**Comment by hexylena** [comment]
All good, no worries. I guess we need to find a more long-term sustainable plan for handling these updates as the UI team makes changes every release.

**Pull request merged**
