### PR TITLE
[WIP] New tutorial for small RNA-seq analysis

### PR DESCRIPTION
**Pull request by stephanierobin**
Hi,
Here is a first draft of a new tutorial for small RNA-seq analysis using mirDeep2 to detect new miRNA in small RNA-seq data and miranda to identify miRNA targets in a reference genome. 
Stéphanie

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @stephanierobin! Let us know if you need any help 😃

**Comment by shiltemann** [comment]
@stephanierobin This PR is now quite old, please let us know if you are still planning on working on it. If not, I will close it for now, but you are always welcome to submit a new PR with your tutorial!

**Comment by stephanierobin** [comment]
Hi @shiltemann You're right, this PR is very old, and I can't work on it at the moment. It would be better to close it, and I will submit a new PR when I have time to do it. Thanks for your reminder !

**Comment by shiltemann** [comment]
@stephanierobin thanks for your quick reply! Will close it for now then :)

**Pull request closed without merging**
