### PR TITLE
Galaxy 101: replace Select first lines tool

### PR DESCRIPTION
**Pull request by gallardoalba**
This PR replaces the tool [Replace first lines](https://usegalaxy.eu/root?tool_id=Show beginning1) by [Replace first lines (head)](https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_head_tool/1.1.0). The reason is that the first tool doesn't work in usegalaxy.eu.

### CODE REVIEW

**Comment by gallardoalba** [comment]
Not sure why it is failing, could you have a look @hexylena?

**Comment by hexylena** [comment]
@beatrizserrano I think this one is for you :) 

```
[/] key 'box_type:' is required
```

Must be missing from one of the FAQs

**Comment by hexylena** [comment]
It's fine otherwise, we'll merge and let @beatrizserrano fix the missing box type in another pr.

**Review by hexylena — APPROVED** [review]
thanks for updating the WF!

**Pull request merged**
