### PR TITLE
News Post: Galaxy Administrator Time Burden and Technology Usage

### PR DESCRIPTION
**Pull request by vladvisan**
We mentioned creating a GTN news post once the slides are finished.
Technically this post would be more useful to new/prospective admins than to the existing ones that will be notified.
However, this will still be useful for word of mouth.

### CODE REVIEW

**Comment by vladvisan** [comment]
I see the linting fails with this message: "./news/_posts/2024-07-19-Galaxy-Administrator-Time-Burden-and-Technology-Usage.md has errors
  [/contributions/data] key 'data:' is undefined."

However, on my local instance it does recognise the "data" (provider) keyword:

image

**Comment by hexylena** [comment]
>  [/contributions/data] key 'data:' is undefined."

yes, it was missing from the schema. I've added it.

>  Technically this post would be more useful to new/prospective admins than to the existing ones that will be notified.
> However, this will still be useful for word of mouth.

definitely!! this'll be great :) It'll go out on our mastodon + bluesky accounts when it's merged. Thanks for writing this up!

**Review by hexylena — DISMISSED** [review]
Merci !

**Review by hexylena — APPROVED** [review]
just moved the post to today

**Comment by vladvisan** [comment]
Thank you Helena

**Pull request merged**
