### PR TITLE
Heroku revival

### PR DESCRIPTION
**Pull request by martenson**
This reintroduces the gemfiles to support ruby-standard deployment on Heroku.

Heroku will deploy with these limitations:

- it has to be pull request
- source and target branch both have to be from this repository for automatic deploy
- for deploying forks the launch has to be explicitly allowed through Heroku console that @erasche @bebatut @shiltemann and @martenson have access to
- atm we have limit of 5 concurrent deployments (I'll try to change that)
- deployments self-destroy after a day (configurable)

### CODE REVIEW

**Comment by martenson** [comment]
Jekyll is very stubborn in using Gemfile when it detects it, I have found no configuration option to ignore it, so as a part of `make serve` and `make detached-serve` I've added commands to mv the gemfile(lock) away which preserves the original conda-stack behavior of building things,

**Comment by erasche** [comment]
@martenson, ok to merge?

**Comment by martenson** [comment]
@erasche ok to review, I think it'll work

**Comment by erasche** [comment]
:tada:

**Pull request merged**
