### PR TITLE
Add script to check contributors

### PR DESCRIPTION
**Pull request by hexylena**
Wrote this as a break between papers, it will check the git log of a given file for the contributors which could be missing.

There is commonly the case of a user using multiple emails, and so this script can read from a local map of emails → usernames.

We could just add these extra emails to the yaml file, but given my personal perspective on the issue, I think maybe it's fine just to have a local map since not so many people might be running this to find missing contributors. (E.g. I know if I have old emails addresses that were included as commits, I'm not sure I want those in a more public contributors.yaml file and I'm sure I'm not alone.)

@bebatut

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @erasche 
How does it work? Do we need to run it manually? If yes, how?

**Comment by erasche** [comment]
@bebatut yes you need to run it manually, it was a privacy tradeoff vs keeping a long list of alternate emails for that user publicly.

you can run with `ruby bin/check-contributors.rb path/to/tutorial.md` (or slides.html). If there are missing emails you can build a small (local) `private-contrib-map.yaml` with 

```
---
some-email: username
```

**Comment by erasche** [comment]
Ok, wrote some documentation and did something more standard.

**Comment by shiltemann** [comment]
thanks @hexylena !

**Pull request merged**
