### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by gmauro**
There are two "split file" tool

### CODE REVIEW

**Comment by simonbray** [comment]
@gmauro, thanks a lot. Is this your only comment on the tutorial or can this be merged already?

**Comment by gmauro** [comment]
Wait for a few minutes, I am finishing it

**Comment by gmauro** [comment]
@simonbray About an hour to complete it. That's all from me. Well done.

**Comment by simonbray** [comment]
Thanks @gmauro, very much appreciated!

**Pull request merged**
