### PR TITLE
usegalaxy migration

### PR DESCRIPTION
**Pull request by bgruening**
xref: https://github.com/galaxyproject/training-material/issues/545

### CODE REVIEW

**Comment by bgruening** [comment]
ready to be reviewed

**Comment by shiltemann** [comment]
thanks a lot @bgruening ! 

..there are several steps in these tutorials that say to import a data library file/workflow/history with direct links to main (e.g. [here](https://github.com/galaxyproject/training-material/blame/d7bf9332b6fcf0e56f4e571f4a272954da580a92/topics/variant-analysis/tutorials/non-dip/tutorial.md#L41) ) which I guess we should change too

**Comment by bgruening** [comment]
@shiltemann yes. All the data needs also be uploaded to Zenodo. Question is if this should be done in this PR or can be done in a following one. This is is currently one reorganizing what is already there.

**Comment by bebatut** [comment]
I should be ready to be merged in the current state. @bgruening, @shiltemann ?
I will open few issues once we merged this one (that does not only concern it)
- Put the data on Zenodo
- Removing all the mention to any data library with a link
- Replacing all screenshots of the tools by parameter list

**Pull request merged**
