### PR TITLE
Edits in contribution tutorials

### PR DESCRIPTION
**Pull request by bedroesb**
Since #1724 and #1715 it is mandatory for a workflow on GTN to have the correct tags and annotation. I hope this is more clear now in the documentation for future contributors.

### CODE REVIEW

**Comment by shiltemann** [comment]
@bedroesb thanks!!

the tags and annotation can also be added in the workflow editor on Galaxy, that might be a bit more user-friendly way? maybe you could mention both options?

image

**Comment by bedroesb** [comment]
That's great idea!

**Comment by simonbray** [comment]
Hi, is there something I need to do here?

**Comment by hexylena** [comment]
@simonbray one of the computational chemistry workflows was renamed, as a code-owner you got pinged. If this is fine for you just approve :)

**Comment by bedroesb** [comment]
@simonbray Originally I disabled the workflow folder with the workflow since the workflow contains tools from the testtoolshed. But because of #1664 there were suddenly 2 workflow [folders](https://github.com/galaxyproject/training-material/tree/master/topics/computational-chemistry/tutorials/cheminformatics). Are there any plans to update the tools so they are not from the testtoolshed?

**Comment by simonbray** [comment]
@bedroesb, I created a PR for one of the workflows: https://github.com/galaxyproject/training-material/pull/1766.

As for the NAMD tools used in the `md-simulation-namd` tutorial, I am not sure if there is any plan to get them into the main toolshed. Maybe @chrisbarnettster can comment on this.

**Comment by bedroesb** [comment]
I think now that adding the tags and annotation is better in the workflow editor anyway instead of editing it later in a text editor... This PR can not yet be merged because I also added the planemo workflow linting., but this is not yet merged on the planemo side #https://github.com/galaxyproject/planemo/pull/998

**Comment by bgruening** [comment]
@bedroesb how do we proceed here? Waiting for the new linting before we merge this one?

**Comment by bedroesb** [comment]
@bgruening I personally think that this can be merged, and the changes that will be made by the new linting can than overwrite the parts that are needed? Or the opposite around is also fine for me. The documentation changes will stay anyway.

**Comment by hexylena** [comment]
Looks good to me, thanks @bedroesb

**Pull request merged**
