### PR TITLE
tiny edits to LOTUS2

### PR DESCRIPTION
**Pull request by bgruening**
!!! DELETE THIS BEFORE SUBMITTING!!! It's just a checklist to help you :)

1. Give your pull request a **good title**
    - e.g. "Fix typo in ansible-galaxy tutorial" or "Add new transcriptomics tutorial covering a new sequencing technology"
2. Describe your changes in detail, list anything you still need some help with or things that are still TODO
3. Check that your images are allowed to be re-hosted by the GTN!
4. Not ready for review yet? Make it a **Draft** pull request
   - Once you are done making changes, choose **Ready for Review**
   - Then the automated tests will run and we will know to review and merge it

### CODE REVIEW

**Comment by bgruening** [comment]
@paulzierep sorry, I just had a few tiny edits.

**Comment by bgruening** [comment]
Also "- LotuS is a metagenomics tool for identifying species and OTUs and ASVs from sequencing data" here is a AND too much? Isn't it?

**Review by paulzierep — APPROVED** [review]
Ah thanks !

**Comment by paulzierep** [comment]
> Also "- LotuS is a metagenomics tool for identifying species and OTUs and ASVs from sequencing data" here is a AND too much? Isn't it?

`LotuS is a metagenomics tool for identifying OTUs or ASVs from sequencing data`

would be ideal imo

**Comment by bgruening** [comment]
I have added your setence.

**Pull request merged**
