### PR TITLE
Introduce auto generated screenshots in rule-based uploader

### PR DESCRIPTION
**Pull request by OlegZharkov**
Replace screenshots by images produced by selenium in https://github.com/galaxyproject/ci-testing
The corresponding selenium tests are marked in https://github.com/galaxyproject/galaxy/pull/11171 and https://github.com/galaxyproject/galaxy/pull/10911

Please deploy locally and assure that all screenshots are correct.

### CODE REVIEW

**Comment by hexylena** [comment]
Hey @OlegZharkov super exciting! Would you mind reverting your changes to the Gemfile and Gemfile.lock please

**Comment by OlegZharkov** [comment]
> Hey @OlegZharkov super exciting! Would you mind reverting your changes to the Gemfile and Gemfile.lock please

I actually did, it's a Github Bug. I did force push my changes, here's [new diff](https://github.com/galaxyproject/training-material/compare/master...OlegZharkov:s3_automation?expand=1)

However it's not updating this PR. Do I really have to create a new PR?

**Comment by hexylena** [comment]
Looks like a caching issue and the cache has already expired, the diff looked incorrect the first time I opened it, and correct just now.

**Comment by hexylena** [comment]
But you've already opened a new one so we can move discussion there.

**Comment by OlegZharkov** [comment]
> Looks like a caching issue and the cache has already expired, the diff looked incorrect the first time I opened it, and correct just now.

definitely not a browser cache. I tried to open in incognito, didn't help.
I wanted to close-reopen this PR and it didn't allow me to re-open because it was forced-pushed... so yeah, I kinda had to open the new one :sweat_smile:

**Pull request closed without merging**
