### PR TITLE
Remove emojis or replace them with icons

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by shiltemann** [comment]
thanks a lot @nsoranzo! 

..there seem to be a couple jemoji used in the slides as well (`_layouts/tutorial_slides.html`), could you replace those as well?

**Comment by nsoranzo** [comment]
@shiltemann Done, thanks for noticing!

**Comment by erasche** [comment]
I think I'm seeing some more now that I'm looking properly?

E.g. lots of `:notebook:` in topics/variant-analysis/tutorials/diploid-variant-calling/tutorial.md

grafik

**Comment by nsoranzo** [comment]
@erasche This is a disabled tutorial I've merged into the dip tutorial in PR https://github.com/galaxyproject/training-material/pull/1041 .

**Comment by shiltemann** [comment]
perfect, thanks @nsoranzo!

**Comment by nsoranzo** [comment]
> Ah it's referenced from the introductory slides (slide 11) under 'Detailed tutorial' which is how I got to it.

@erasche Fixed in https://github.com/galaxyproject/training-material/pull/1041/commits/cd8aaee70ee63a695b82e8d2b7a5336897aff358

**Pull request merged**
