### PR TITLE
New Bacterial isolation species contamination checking tutorial

### PR DESCRIPTION
**Pull request by bebatut**
Hi, 

This PR adds a new tutorial for checking expected species and contamination in bacterial isolate, based on work by @pimarin
I then update the learning pathway for AMR gene detection to add a new module there.

I put this tutorial in ecology. I was not sure exactly where to put it.
@shiltemann, @hexylena, @yvanlebras what do you think?

### CODE REVIEW

**Comment by hexylena** [comment]
ecology feels quite strange, microb* would almost be better.

**Comment by bebatut** [comment]
We have microbiome now but it is 1 isolate here, not really a microbiome.
Sequence-analysis otherwise?

**Comment by bebatut** [comment]
I do not understand the linting issue also...

**Comment by hexylena** [comment]
The linting error is for the krona plot, you did not name it `krona*.html` so the linting checked it. Could you please update `.github/workflows/ci.yml` to include the exception? (I should synchronise it with the makefile but i've been lazy.)

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
@yvanlebras can you check this so we can merge it? :) (or do you hvae a student who is knowledgeable and can check it?)

**Pull request merged**
