### PR TITLE
metaproteomics minor improvements

### PR DESCRIPTION
**Pull request by bernt-matthias**
Added a tools file for the metaproteomics tutorial. 

Missing is still the entry for "Split Tabular Columns" - I did not know which tool the corresponds to. 

I was wondering if there is way to specify visualizations that need to be installed/configured. For this tutorial the required Unipept Tree viewer seems not to work by default.

### CODE REVIEW

**Comment by bgruening** [comment]
@bebatut do you know where the tool "Split Tabular Columns" is living?

**Comment by bernt-matthias** [comment]
Fount the "Split Tabular Columns" and successfully completed the tutorial. 

Two questions from my side remain: 
- is searchgui necessary or is this included in the peptideshaker tool
- There is a tool query_tabular and a suite_query_tabular (same date in the toolshed). Which should be used?

**Comment by shiltemann** [comment]
the tool `query_tabular` is part of the suite `suite_query_tabular` (along with `filter_tabular` and `sqlite_to_tabular`). Seems you need 2/3 of these for the tutorial, so you can either install the suite and get all three, or explicitly install just the two tools you need.

**Comment by bgruening** [comment]
Thanks @bernt-matthias!

**Pull request merged**
