### PR TITLE
Export ro-crate-metadata.json for building RO Crates of the Workflows

### PR DESCRIPTION
**Pull request by hexylena**
Based on the example by @supernord, fyi @uwwint

This currently doesn't feel terribly complete, e.g. 

- no workflow is directly mentioned (we can point to a URL? how do we do that?), should that look like the example here? https://www.researchobject.org/ro-crate/1.1/workflows.html#complete-workflow-example
- Should we provide a zip? is that the useful artefact for WFH, or is the json fine (and it will lookup/fetch the galaxy workflow file itself)
- Not sure what we should do about the `version` field, that's... complicated to detect a good linear number over time. We could probably detect # of commits to that file and use that as the version, probably the safest to ensure changes are detected properly.
- and of course, how do we get that into WFH.

### CODE REVIEW

**Comment by supernord** [comment]
@uwwint - example https://github.com/AustralianBioCommons/create-gtn-rocrates/blob/33b5d4ef25beaa2434f195a1f5ed5da8862998c8/create-gtn-rocrates.py

**Comment by supernord** [comment]
And extracting `*.ga` workflow file contents https://github.com/AustralianBioCommons/create-gtn-rocrates/blob/33b5d4ef25beaa2434f195a1f5ed5da8862998c8/create-gtn-rocrates.py#L75-L87

**Comment by supernord** [comment]
And info on submitting RO-crates via API https://about.workflowhub.eu/developer/ro-crate-api/

**Comment by hexylena** [comment]
@supernord in this PR I, uh, throw away the python, and rewrite it in ruby here with the existing information available in internal datastructures. It should be producing essentially identical. But yes, said `.ga` files aren't mentioned in the current version that's exported

<details>
<summary>create-gtn-crates
</summary>

```bash
04:17:59 w-galaxy:[~/arbeit/galaxy/create-gtn-rocrates @main‽]$ cat ro_crates/assembly-assembly-quality-controlb94caf5d-794e-412d-b2db-8e51b01113dc/ro-crate-metadata.json 

    "@context": "https://w3id.org/ro/crate/1.1/context",
    "@graph": [
        {
            "@id": "./",
            "@type": "Dataset",
            "datePublished": "2023-06-01T07:11:21+00:00"
        },
        {
            "@id": "ro-crate-metadata.json",
            "@type": "CreativeWork",
            "about": {
                "@id": "./"
            },
            "conformsTo": {
                "@id": "https://w3id.org/ro/crate/1.1"
            }
        },
        {
            "@id": "#assembly-assembly-quality-control",
            "@type": [
                "File",
                "SoftwareSourceCode",
                "ComputationalWorkflow"
            ],
            "author": [
                {
                    "@id": "#b7bd540a-f9c3-4229-b09a-19945f2fcc48"
                },
                {
                    "@id": "#83bbf07b-ce1a-4565-b5af-57a8119bd5da"
                },
                {
                    "@id": "#77870d4f-175d-49fb-87eb-c5971ca49f9a"
                },
                {
                    "@id": "#43489223-7d5a-41e5-a453-750f912aa4de"
                },
                {
                    "@id": "#28ff69e1-3756-4e19-8f61-a1b343131a0d"
                }
            ],
            "license": "GPL-3.0-or-later",
            "name": "Genome Assembly Quality Control",
            "version": 0
        },
        {
            "@id": "#b7bd540a-f9c3-4229-b09a-19945f2fcc48",
            "@type": "Person",
            "name": "Erwan Corre"
        },
        {
            "@id": "#83bbf07b-ce1a-4565-b5af-57a8119bd5da",
            "@type": "Person",
            "name": "St\u00e9phanie Robin"
        },
        {
            "@id": "#77870d4f-175d-49fb-87eb-c5971ca49f9a",
            "@type": "Person",
            "name": "Anthony Bretaudeau"
        },
        {
            "@id": "#43489223-7d5a-41e5-a453-750f912aa4de",
            "@type": "Person",
            "name": "Alexandre Cormier"
        },
        {
            "@id": "#28ff69e1-3756-4e19-8f61-a1b343131a0d",
            "@type": "Person",
            "name": "Laura Leroi"
        }
    ]
}
```

</details>


<details>
<summary>this PR
</summary>

```
04:19:16 w-galaxy:[~/arbeit/galaxy/training-material @alpaca-scala‽]148$ cat _site/training-material/api/workflows/assembly-assembly-quality-control/main_workflow/ro-crate-metadata.json 
{
  "@context": "https://w3id.org/ro/crate/1.1/context",
  "@graph": [
    {
      "@id": "./",
      "@type": "Dataset",
      "datePublished": "2023-06-19 12:42:45 +0200"
    },
    {
      "@id": "ro-crate-metadata.json",
      "@type": "CreativeWork",
      "about": {
        "@id": "./"
      },
      "conformsTo": {
        "@id": "https://w3id.org/ro/crate/1.1"
      }
    },
    {
      "@id": "#assembly-assembly-quality-control",
      "@type": [
        "File",
        "SoftwareSourceCode",
        "ComputationalWorkflow"
      ],
      "author": [
        {
          "@id": "https://orcid.org/"
        },
        {
          "@id": "https://orcid.org/"
        },
        {
          "@id": "https://orcid.org/"
        },
        {
          "@id": "https://orcid.org/"
        },
        {
          "@id": "https://orcid.org/"
        }
      ],
      "license": "https://spdx.org/licenses/GPL-3.0-or-later",
      "name": "Genome Assembly Quality Control",
      "version": 1
    },
    {
      "@id": "https://orcid.org/",
      "@type": "Person",
      "name": "Erwan Corre"
    },
    {
      "@id": "https://orcid.org/",
      "@type": "Person",
      "name": "Stéphanie Robin"
    },
    {
      "@id": "https://orcid.org/",
      "@type": "Person",
      "name": "Anthony Bretaudeau"
    },
    {
      "@id": "https://orcid.org/",
      "@type": "Person",
      "name": "Alexandre Cormier"
    },
    {
      "@id": "https://orcid.org/",
      "@type": "Person",
      "name": "Laura Leroi"
    }
  ]
}
```

</details>

**Comment by hexylena** [comment]
> And info on submitting RO-crates via API https://about.workflowhub.eu/developer/ro-crate-api/

ok that makes it a bit more clear, cheers. So it does need a zip.

**Comment by hexylena** [comment]
Other questions:

- what all should be in the zip? just the .json + .ga ?
- should we be enumerating workflow input parameters in the ro-crate-metadata.json?

**Comment by fbacall** [comment]
> * what all should be in the zip? just the .json + .ga ?

Are there any other files such as a README for the workflow? If not, just those 2 is fine.

> * should we be enumerating workflow input parameters in the ro-crate-metadata.json?

You can but it's not necessary for WorkflowHub's sake, we can parse them from the .ga file.

WorkflowHub expects RO-Crates conforming to the workflow RO-Crate spec: https://about.workflowhub.eu/Workflow-RO-Crate/
so you'll need:

- `mainEntity` pointing to the `.ga` workflow file.
- `programmingLanguage` mentioning Galaxy as the workflow type.
- to flatten the JSON-LD (`author` under the workflow entity is not): https://www.w3.org/TR/json-ld/#flattened-document-form

You can check out e.g. https://workflowhub.eu/workflows/519/ro_crate?version=1 as an example of a valid workflow RO-Crate

FYI there is a gem for generating RO-Crates that may be useful: https://github.com/ResearchObject/ro-crate-ruby

**Comment by hexylena** [comment]
As a follow up to our emails yesterday @supernord, I've made the updates based on @fbacall's comment, during a meeting today. Please find an example crate here: [rocrate.zip](https://github.com/galaxyproject/training-material/files/12791754/rocrate.zip) Once unzipped it passes [ro-crate-validator-py](https://github.com/ResearchObject/ro-crate-validator-py/) @supernord made me aware of the license issue with WFH+this specific workflow, but we will wait for the next release of WFH.

@stain apologies, I worked on this PR during your WP meeting just now, but I think you'll be happy to see the result, so maybe it balances out ;)

@fbacall in the end we opted not to use the ruby library as our implementation was already half written and it felt like more work to integrate it, sorry. Separately, judging by your example crate, it looks like the WFHub potentially modifies the RO-Crate to add additional information? This made it a bit hard to pick out what was really the bare minimum, perhaps an example crate showcasing all the possibilities would be useful for other users implementing this like me. I'm pretty sure I've got the authors right, but they also aren't shown in https://about.workflowhub.eu/Workflow-RO-Crate/#ro-crate-metadatajson-example so I can't be fully certain.

**Review by shiltemann — APPROVED** [review]

**Pull request merged**
