### PR TITLE
[FAQ] edited reference genome

### PR DESCRIPTION
**Pull request by garimavs**
This PR is for issue no: #3439 

Kindly suggest any improvements or edits.

### CODE REVIEW

**Comment by garimavs** [comment]
There are some broken links here; it might be because the link was used elsewhere!
How may I proceed next @beatrizserrano @annefou

**Comment by beatrizserrano** [comment]
I don't think that renaming the files solves the issue. I actually don't understand where the issue is because all the `area` fields are spelled the same way, so it should appear, I think. Any ideas @shiltemann @hexylena?

**Comment by hexylena** [comment]
It's looking for 

> Could not find document 'faqs/galaxy/datasets_sorting_reference_genome.md' in tag 'link'. (ArgumentError)

There needs to be a file with exactly that name

**Comment by beatrizserrano** [comment]
isn't that because of the renaming of files?

**Comment by garimavs** [comment]
> It's looking for
> 
> > Could not find document 'faqs/galaxy/datasets_sorting_reference_genome.md' in tag 'link'. (ArgumentError)
> 
> There needs to be a file with exactly that name

This was the name of the previous file. But this PR is only for renaming those files only.

**Comment by hexylena** [comment]
> This was the name of the previous file. But this PR is only for renaming those files only.

then that means there are other files, somewhere else, referring to those FAQs you've renamed. Those references must be updated as well.

**Comment by hexylena** [comment]
```
$ grep 'faqs/galaxy/datasets_sorting_reference_genome.md' -R *
faqs/galaxy/datasets_troubleshooting_custom_genome.md
44:   - **How**: To sort, follow instructions for [Sorting]({% link faqs/galaxy/datasets_sorting_reference_genome.md %}) a Custom Genome.
```
looks like that file refers to the old name, please make sure they match.

**Comment by garimavs** [comment]
> ```
> $ grep 'faqs/galaxy/datasets_sorting_reference_genome.md' -R *
> faqs/galaxy/datasets_troubleshooting_custom_genome.md
> 44:   - **How**: To sort, follow instructions for [Sorting]({% link faqs/galaxy/datasets_sorting_reference_genome.md %}) a Custom Genome.
> ```
> 
> looks like that file refers to the old name, please make sure they match.

Thanks for mentioning it, I have updated the link there.

**Comment by beatrizserrano** [comment]
@hexylena I've done a rebase here with no conflicts in local, but GitHub says there are still 2 conflicting files. No clue 🤷🏻‍♀️

**Review by beatrizserrano — APPROVED** [review]

**Comment by beatrizserrano** [comment]
Thanks @garimavs, finally all the issues solved :)

**Comment by garimavs** [comment]
> Thanks @garimavs, finally all the issues solved :)

Thanks for the rebase @beatrizserrano! Will close the corresponding issue too.

**Pull request merged**
