### PR TITLE
[FAQ] Added FAQ for 'canceled by admin' or a cluster failure in job failure

### PR DESCRIPTION
**Pull request by garimavs**
This PR is a part of the issue: _Move FAQs to the GTN_ ([Determining the job failure type](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type)) of the [Galaxy Hub Repository](https://github.com/galaxyproject/galaxy-hub)

Kindly suggest any improvements or amendments.
Thanks to @jennaj for helping me with the content.

### CODE REVIEW

**Review by jennaj — CHANGES_REQUESTED** [review]
Same change as for other sub-FAQs: crosslink to Input problem and reword the text to match others in same class

**Comment by garimavs** [comment]
I renamed the names and will update the link once the PRs are merged.

**Review by jennaj — DISMISSED** [review]
Great -- the placeholder for the link is good

**Comment by jennaj** [comment]
Hopefully that is the correct commit type

**Comment by garimavs** [comment]
> Great -- the placeholder for the link is good

Once PR #3404 gets merged, I will get the links added, as it has references in every other job failure type!

**Review by beatrizserrano — APPROVED** [review]

**Pull request merged**
