### PR TITLE
Activate conda env in Makefile rule recipes

### PR DESCRIPTION
**Pull request by nsoranzo**
Also update conda env if it already exists when executing `make create-env` .

### CODE REVIEW

**Comment by bgruening** [comment]
Great. Thanks Nicola!

**Comment by nsoranzo** [comment]
Rebased for the jemoji removal.

**Comment by shiltemann** [comment]
ooh, super handy, thanks @nsoranzo! 

we can probably update the [contributing tutorial](https://galaxyproject.github.io/training-material/topics/contributing/tutorials/running-jekyll/tutorial.html#installation-of-the-requirements) about running the website locally then too, skip the instructions to activate the environment?

**Comment by bgruening** [comment]
Really timely ... we will use this tomorrow :)

**Pull request merged**
