### PR TITLE
Issues with epigenetics speaker notes

### PR DESCRIPTION
**Pull request by hexylena**
Hey @heylf @lldelisle do you have a chance to look at the speaker notes for the atac slides? I noticed earlier today they weren't building properly and after enabling them there seem to be some issues.

- every slide needs speaker notes, none can be skipped. just read the title if you have nothing to say
- I removed the first slide since it's somewhat redundant with the key points/cover slide.
- You have references in speaker notes which is not something that's possible. 
- I think the existing speaker notes need to maybe explain a bit more? They are the only part of the video that will be narrated, so they should probably discuss the bullet points covered.

I can disable the automated video for now if that's easier?

### CODE REVIEW

**Comment by lldelisle** [comment]
Sorry for that, it is my first slides... I will look at them.

**Comment by hexylena** [comment]
No problem! You can look at [the ansible slides](https://github.com/galaxyproject/training-material/blob/main/topics/admin/tutorials/ansible-galaxy/slides.html) for an example of pretty good slides.

**Comment by lldelisle** [comment]
@hexylena I am checking the speakernotes locally and I confirm you here.

**Comment by hexylena** [comment]
Yes, they look fantastic now. Thank you so much @lldelisle !

**Review by shiltemann — APPROVED** [review]
thanks a lot @lldelisle!

**Comment by lldelisle** [comment]
When I checked the video, it is like the voice does not read the objectives. Should I remove them?

**Comment by lldelisle** [comment]
Then everything is shifted: voice describing slide 5 with image of slide 4 etc...

**Comment by hexylena** [comment]
No, please keep them. It is a bug on our end.

**Comment by lldelisle** [comment]
OK thanks

**Pull request merged**
