### PR TITLE
CRISPR finalise

### PR DESCRIPTION
**Pull request by mblue9**
Few things to fix in slides

### CODE REVIEW

**Comment by mblue9** [comment]
Ready for review for Tapas if anyone can do it

**Comment by hexylena** [comment]
@mblue9 I'm looking at this and #3220 and wondering if there's not some organisation that might make more sense, than having both in their own section.

What would you think about renaming `genome annotation` to `genomics`? Would this fit appropriately under `genomics`, if we made a subtopic for genome editing?

**Comment by hexylena** [comment]
@mblue9 I'm working on this now! I'm made one small change, I'm replacing your `**C**lustered **R**egularly...` with `{CRISPR}`, and using the [built in abbreviation plugin.](https://training.galaxyproject.org/training-material/news/2021/05/25/abbreviations-tag.html) This should be more friendly for screen-readers, as some will read emphasized letters separately from the rest of the word.

It looks like you're missing some alt-text for a few of the images. This was not caught in the initial round of linting due to an issue in the plugin which I've now fixed. Could you please provide [alt text](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#guidelines-on-alt-vs-figcaption-text) there?

**Comment by mblue9** [comment]
Thanks for working on this @hexylena !

>@mblue9 I'm looking at this and https://github.com/galaxyproject/training-material/pull/3220 and wondering if there's not some organisation that might make more sense, than having both in their own section.

>What would you think about renaming genome annotation to genomics? Would this fit appropriately under genomics, if we made a subtopic for genome editing?

Yes that makes sense to me, should I go ahead and create a topic for genomics with subtopic genome-editing?

>@mblue9 I'm working on this now! I'm made one small change, I'm replacing your **C**lustered **R**egularly... with {CRISPR}, and using the [built in abbreviation plugin.](https://training.galaxyproject.org/training-material/news/2021/05/25/abbreviations-tag.html) This should be more friendly for screen-readers, as some will read emphasized letters separately from the rest of the word.

Great thanks!

>It looks like you're missing some alt-text for a few of the images. This was not caught in the initial round of linting due to an issue in the plugin which I've now fixed. Could you please provide [alt text](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#guidelines-on-alt-vs-figcaption-text) there?

Will do

**Comment by hexylena** [comment]
I can handle the reorganisation, no dramas.

**Comment by hexylena** [comment]
Question: are you planning more CRISPR tutorials? (We've had some internal discussion about the rearranging and struggling to find a good solution, I was too optimistic.)

**Comment by mblue9** [comment]
>Question: are you planning more CRISPR tutorials? (We've had some internal discussion about the rearranging and struggling to find a good solution, I was too optimistic.)

I don't currently have plans for more. Was just looking at TN-seq tutorial and that's a similar concept (identifying essential genes) so maybe we put this under genome-annotation too as CRISPR can be used for identifying/annotating gene functions. This tutorial is not really about annotating genomes (it's determining action of a drug) but if it's better to put it there rather than in a topic on it's own we could do that?

**Comment by hexylena** [comment]
Ok, that works for now then

**Review by hexylena — APPROVED** [review]

**Comment by mblue9** [comment]
Thanks a lot @hexylena !

**Comment by hexylena** [comment]
Sure thing @mblue9 !! Great to see more tutorials :)

And one more thing: I'm sorry I missed this @mblue9, it looks like one slide is missing speaker notes:

image

unfortunately that will break the autogenerated video. Would you mind adding notes for that?

**Comment by mblue9** [comment]
Fixed [here ](https://github.com/galaxyproject/training-material/pull/3230)@hexylena

**Comment by mblue9** [comment]
Hi @hexylena just wondering if I need to do anything to get the autogenerated video to show up here?
https://training.galaxyproject.org/training-material/videos/watch.html?v=/genome-annotation/tutorials/crispr-screen/slides

**Comment by hexylena** [comment]
No, nothing you need to do. Look like something's gone wrong with the video generation.
 I'll look into it.

**Comment by mblue9** [comment]
Ok great thanks!

**Comment by hexylena** [comment]
I'm struggling to get the video building working again, something is wrong with the dependencies and I don't know what, I can't reproduce it locally. I'll build the video manually, locally. and upload it.

**Comment by mblue9** [comment]
Ok thanks @hexylena !
I just realised I should probably add some pronounciations into https://github.com/galaxyproject/training-material/blob/main/bin/ari-map.yml
e.g CRISPR = crisper 
have you already made the video or will I do that first?

**Comment by hexylena** [comment]
I've made it, https://training.galaxyproject.org/training-material/videos/watch.html?v=/genome-annotation/tutorials/crispr-screen/slides you can use it to check pronunciation and I'll re-make it whenever you're done :)

**Comment by mblue9** [comment]
>I've made it, https://training.galaxyproject.org/training-material/videos/watch.html?v=/genome-annotation/tutorials/crispr-screen/slides you can use it to check pronunciation and I'll re-make it whenever you're done :)

Great, done here https://github.com/galaxyproject/training-material/pull/3236

**Comment by mblue9** [comment]
Forgot to say I got asked if the slides robot voice could have an Oz accent but I assume that's not possible 😆

**Comment by hexylena** [comment]
Oh defo possible! Only the woman's voice is good, the man's a bit synthetic
sounding. I'll get that swapped in for ya. We can have her goin on about
how grouse crispr is in no time 🤣

**Comment by mblue9** [comment]
>Oh defo possible! Only the woman's voice is good, the man's a bit synthetic
sounding. I'll get that swapped in for ya. We can have her goin on about
how grouse crispr is in no time 🤣

 😃  Ohh brilliant!! 🙌 🎉

**Comment by shiltemann** [comment]
This is so cool! Thanks @mblue9!  I think I am going to do this tutorial myself during Smorg next week, this looks very intersting :)

**Comment by mblue9** [comment]
Aw thanks @shiltemann 🥰

**Pull request merged**
