### PR TITLE
Added Reference-based RNA-seq FAQ files

### PR DESCRIPTION
**Pull request by rahmot**
I added Reference-based RNA-seq FAQ files to the transcriptomics topic.

### CODE REVIEW

**Comment by rahmot** [comment]
Hi, I want to let you know that I grouped these FAQ files by the training lessons title (referring to the area). Not really sure if this works, kindly let me know. Gracias!

**Comment by hexylena** [comment]
@rahmot what about moving those into the tutorial-specific region? I think some of the questions are specific to that tutorial, maybe it would make sense? If you move those FAQs into an `faqs` subdirectory of the tutorial it would show that it's specific to that tutorial

For example the metagenomics tutorials use this:

```
topics/metagenomics/tutorials/mothur-miseq-sop/faqs/adapting_to_different_data.md
```

If you create those faqs subdirectory in the individual tutorial directories, can you add an `index.md` in each of the faqs folders? It should look like

```
$ cat topics/metagenomics/tutorials/mothur-miseq-sop/faqs/index.md
---
layout: faq-page
---
```

**Comment by rahmot** [comment]
@hexylena thanks for the illumination! I was thinking of that as well because it will be too bulky to have everything under the transcriptomics topic. Correcting that straight away

**Comment by rahmot** [comment]
@hexylena apologies for the delay. My PC crashed during the weekend, just fixed it. I have moved the faq files to ref-based tutorials. Kindly check it out. Thanks!

**Review by hexylena — APPROVED** [review]
This is perfect!

**Comment by hexylena** [comment]
No worries for the delay :)

**Pull request merged**
