### PR TITLE
Add an emoji to the homepage

### PR DESCRIPTION
**Pull request by willdurand**
We are testing Heroku Preview Apps :)

### CODE REVIEW

**Comment by willdurand** [comment]
closing as this was an example.

**Comment by afgane** [comment]
Does a PR need to be open for this preview page to work? I just stumbled here and don't quite see what's supposed to be happening here :/

**Comment by bgruening** [comment]
The preview website will be removed after a day. You are unfortunately too late :)

**Comment by afgane** [comment]
Thanks for clarifying that. I wasn't clear if I was missing something.

It's like a trigger - there's now a deadline for reviewing PRs :)

**Comment by bgruening** [comment]
Yes, review fast - spreading knowledge can not wait ;)
I don't think this isn't a big problem, this feature is more intended for people who want to check the changes without building it locally. Core contributor can probably build it locally at any time for the review.

So more for a preview than a review imho ;)

**Comment by willdurand** [comment]
"after a day" once the PR is merged or closed. otherwise, the site is up as long as the PR is open.


The only new thing I noticed is that PRs from forks don't create new websites automatically (for security/billing reasons apparently). @martenson can create them on the Heroku dashboard though.

**Comment by martenson** [comment]
We can also change the 1-day to something different...

**Pull request closed without merging**
