### PR TITLE
Goenrichment

### PR DESCRIPTION
**Pull request by dsobral**
I've added a Workflow. Basically I downloaded one from usegalaxy.org after running the tutorial.
I hope this one is good enough like that, as I'm not sure of other ways to easily generate it.

One file in Zenodo slipped through the cracks so I had to change it again.

### CODE REVIEW

**Comment by dsobral** [comment]
I think Travis failed due to some timeout with conda...

**Comment by bedroesb** [comment]
@dsobral Is it possible to change the data library to the latest format? #1255 will convert all data-libraries to that format.

for more information: https://galaxyproject.github.io/training-material/topics/contributing/tutorials/create-new-tutorial-technical/tutorial.html

**Comment by dsobral** [comment]
> @dsobral Is it possible to change the data library to the latest format? #1255 will convert all data-libraries to that format.
> 
> for more information: https://galaxyproject.github.io/training-material/topics/contributing/tutorials/create-new-tutorial-technical/tutorial.html

**Comment by dsobral** [comment]
planemo training_fill_data_library seems to be failing for some reason:

` File "/home/dsobral/miniconda3/lib/python3.7/site-packages/planemo/training/utils.py", line 19, in init_from_dict
    self.title = dict['title']
KeyError: 'title'`

Although title is defined in tutorial.md
I've tried with other tutorials and I get the same error...

**Comment by bedroesb** [comment]
I came across several of these problems when I used planemo training_fill_data_library on all tutorials. I've made some changes to the planemo module in how he reads the meta data from the tutorial.md file to get it working. I was planning to talk about it with @bebatut /or open an issue. 
I did quickly did it for you:

```
---
destination:
  type: library
  name: GTN - Material
  description: Galaxy Training Network Material
  synopsis: Galaxy Training Network Material. See https://training.galaxyproject.org
items:
- name: Transcriptomics
  description: Training material for all kinds of transcriptomics analysis.
  items:
  - name: GO Enrichment Analysis
    items:
    - name: 'DOI: 10.5281/zenodo.2565417'
      description: latest
      items:
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/drosophila_gene_association.fb
        src: url
        ext: tabular
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/go.obo
        src: url
        ext: obo
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/goslim_generic.obo
        src: url
        ext: obo
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/mouse_brain_vs_heart.difgenes.txt
        src: url
        ext: txt
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/mouse_brain_vs_heart.txt
        src: url
        ext: txt
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/mouseOverexpressed.txt
        src: url
        ext: txt
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/mouseUnderexpressed.txt
        src: url
        ext: txt
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/Mus_musculus_annotations_biomart_e92.tab
        src: url
        ext: tabular
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/trapnellPopulation.tab
        src: url
        ext: tabular
        info: https://zenodo.org/record/2565417
      - url: https://zenodo.org/api/files/a4583abd-0a85-457e-a5c0-1fc323535db7/trapnellStudy.txt
        src: url
        ext: txt
        info: https://zenodo.org/record/2565417

```

**Comment by dsobral** [comment]
OK, Thanks. I updated it then.

**Comment by bebatut** [comment]
@dsobral, @bedroesb I know the error. I am working on fixing this issue

**Comment by bgruening** [comment]
@dsobral looks good can you fix the merge conflict?

**Pull request merged**
