### PR TITLE
Moving FAQ - Mismatched Chromosome identifiers and how to avoid them

### PR DESCRIPTION
**Pull request by Melkeb**
This FAQ is part of [Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/). I separated the FAQ to different FAQs because the content was too long.

### CODE REVIEW

**Review by jennaj — APPROVED** [review]
I think it is OK to have broken links to FAQs that will also be approved soon. At the very end of the process we can go through all and check/repair any broken crosslinks. Otherwise, we'll lose context and have much more to do later.

**Comment by Melkeb** [comment]
Noted! Thank you @jennaj for the comments.

**Comment by Melkeb** [comment]
Hi @annefou should I remove method 3 and 4 since its linked to the closed PR or should we close this one as well?

**Comment by annefou** [comment]
I would. For me these "types" of FAQs are more for topics FAQs than for GTN FAQs.

**Comment by beatrizserrano** [comment]
The broken link is really not broken, we merged before: https://github.com/galaxyproject/training-material/blob/main/faqs/galaxy/datasets_BAM_dataset_identifiers.md

So I think it's safe to merge this one :) Thank you @Melkeb and @jennaj

**Comment by beatrizserrano** [comment]
ok, so I was very fast merging, the first link that was broken according to the tests was ok, but not the rest. @Melkeb could you edit this FAQ in another PR? thank you :)

**Comment by Melkeb** [comment]
> ok, so I was very fast merging, the first link that was broken according to the tests was ok, but not the rest. @Melkeb could you edit this FAQ in another PR? thank you :)

Yeah sure I will

**Pull request merged**
