### PR TITLE
Remove tool.yaml files and generate them from workflows for instance annotation during travis build

### PR DESCRIPTION
**Pull request by shiltemann**
`tools.yaml` files can be generated from the workflow files using ephemeris, so I've removed them from this repo. 

I have added a script to generate the tool.yaml files from the workflows for all the tutorials. The tools.yaml files are still needed for the instance annotation and badge generation, and the script might also be useful for Galaxy admins looking to support certain tutorials

(wip until I test a bit more)

### CODE REVIEW

**Comment by erasche** [comment]
:tada: :tada:

**Comment by bebatut** [comment]
Do we need the `tools.yaml` files if we have the workflow?

**Comment by erasche** [comment]
If we don't, I think the issue is that the instances that it can run on won't appear

**Comment by bebatut** [comment]
Sorry I misread and did not take the time to check the PR. I thought you were generating again all `tools.yaml` files from workflow and stored them here... 
Looks good now that I understood

**Comment by shiltemann** [comment]
k, got a chance to test this, should be good now :)

**Comment by bebatut** [comment]
Thank you!

**Pull request merged**
