### PR TITLE
Lint for unnecessary box titles

### PR DESCRIPTION
**Pull request by hexylena**
@shiltemann based on your review comments in https://github.com/galaxyproject/training-material/pull/3825/files/9b26232656a9acbf29013a4d458b0160cc06c199..c55d124f43f95e492f0e09073bcc9677a41ca015

I added linting on these unnecessary box titles and then automated their removal in a lot of cases.

image

### CODE REVIEW

**Comment by hexylena** [comment]
Failing due to unrelated issue:

> node-pre-gyp ERR! install response status 503 Egress is over the account limit. on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v83-linux-glibc-x64.tar.gz 

oops

**Comment by shiltemann** [comment]
oh nice! thanks @hexylena

**Comment by hexylena** [comment]
ahh that error si relevant. will fix.

**Review by shiltemann — DISMISSED** [review]

**Comment by hexylena** [comment]
Linting should be passing now, fingers crossed.

**Review by shiltemann — APPROVED** [review]

**Pull request merged**
