### PR TITLE
Reorder alphabetically the topics

### PR DESCRIPTION
**Pull request by bebatut**
It is a first attempt to re-order the topics (here in alphabetical order)

### CODE REVIEW

**Comment by shiltemann** [comment]
cool, I think alphabetical makes sense, but perhaps give the introduction topic special status and put it first? What do you think?

**Comment by bebatut** [comment]
Yes I think so, but I need to figure out how to do that 😄

**Comment by nsoranzo** [comment]
I'm fine with fully alphabetical.

**Comment by shiltemann** [comment]
this will do it btw if we decide this is what we want:

```
{% assign sorted_topics = "" | split: "," %}

{% assign sorted_topics_pre = site.data | sort | order: "title" %}
{% for topic in sorted_topics_pre %}
    {% if topic[0] != "introduction" %}
        {% assign sorted_topics = sorted_topics | push: topic %}
    {% else %}
        {% assign sorted_topics = sorted_topics | unshift: topic %}
    {% endif %}
{% endfor %}
```

**Comment by bebatut** [comment]
@shiltemann you are the best! It was exactly what I wanted to do (but I could not manage...)
I think it also makes sense to have the "Introduction" first and the other topics in alphabetical order after. I push that 😄  😄

**Comment by shiltemann** [comment]
done :)

**Comment by bebatut** [comment]
Thanks a lot!

**Comment by bgruening** [comment]
Top!

**Comment by nsoranzo** [comment]
@shiltemann Not sure why, but on the right column "Galaxy Server administration" comes before "Development in Galaxy" (maybe it's sorting by the directory name? I thought it was by title :confused: )

**Pull request merged**
