### PR TITLE
add spelling for proteomics slides

### PR DESCRIPTION
**Pull request by foellmelanie**
not sure if the > is correct. In the text it is written: '>'

### CODE REVIEW

**Comment by hexylena** [comment]
`>` is right, I'll take care of it, I just need to test it doesn't break other things :)

**Comment by hexylena** [comment]
Which slides deck is this change for?

**Comment by shiltemann** [comment]
@hexylena It will be for these: https://github.com/galaxyproject/training-material/pull/2323

@foellmelanie would you like to add your speaker notes onto my PR? Or shall we merge that one, and you open a new one for the speaker notes/updates?

**Comment by foellmelanie** [comment]
Thank you all. @shiltemann I plan to merge into your PR

**Review by hexylena — APPROVED** [review]
Looking forward to the speaker note PR @foellmelanie :)

**Pull request merged**
