### PR TITLE
Add missing section label

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Review by martenson — APPROVED** [review]

**Comment by hexylena** [comment]
not merging this one until it passes (since it deploys the git-gat repo from this PR anyway and that's what I'm re-running.)

```
{"version": "0.1", "suitename": "Galaxy Tool Tests", "results": {"total": 1, "errors": 0, "failures": 1, "skips": 0}, "tests": [{"id": "minimap2/2.20+galaxy0-0", "has_data": true, "data": {"tool_id": "minimap2", "tool_version": "2.20+galaxy0", "test_index": 0, "time_seconds": 40.28350567817688, "inputs": {"reference_source|ref_file": {"src": "hda", "id": "f8c43d3bbbbdd9d4"}, "reference_source|reference_source_selector": "history", "fastq_input|fastq_input1": {"src": "hda", "id": "26d744393f4de250"}, "fastq_input|analysis_type_selector": "sr", "fastq_input|fastq_input_selector": "single"}, "job": {"model_class": "Job", "id": "f29cf06d0c17115c", "state": "ok", "exit_code": 0, "update_time": "2021-06-08T13:26:50.154247", "create_time": "2021-06-08T13:26:15.820127", "galaxy_version": "20.09", "command_version": "2.20-r1061\n", "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2/2.20+galaxy0", "history_id": "26d744393f4de250", "external_id": "325170", "command_line": "ln -f -s '/data/0/3/b/dataset_03b28af3-29db-4239-ad17-f7cf97fe1b36.dat' reference.fa && minimap2 -x sr          -t ${GALAXY_SLOTS:-4} reference.fa '/data/a/6/b/dataset_a6bcfc9b-54e2-458f-a455-0959a922c34a.dat' -a | samtools sort -@${GALAXY_SLOTS:-2} -T \"${TMPDIR:-.}\" -O BAM -o '/srv/galaxy/jobs/000/3/outputs/galaxy_dataset_311cac24-76c1-4fab-9d07-b01bc284009a.dat'", "params": {"reference_source": "{\"__current_case__\": 1, \"ref_file\": {\"values\": [{\"id\": 1, \"src\": \"hda\"}]}, \"reference_source_selector\": \"history\"}", "fastq_input": "{\"__current_case__\": 0, \"analysis_type_selector\": \"sr\", \"fastq_input1\": {\"values\": [{\"id\": 2, \"src\": \"hda\"}]}, \"fastq_input_selector\": \"single\"}", "indexing_options": "{\"H\": \"false\", \"I\": \"\", \"k\": \"\", \"w\": \"\"}", "mapping_options": "{\"F\": \"\", \"N\": \"\", \"X\": \"false\", \"f\": \"\", \"g\": \"\", \"kmer_ocurrence_interval\": {\"__current_case__\": 1, \"interval\": \"\"}, \"m\": \"\", \"mask_len\": \"\", \"max_chain_iter\": \"\", \"max_chain_skip\": \"\", \"min_occ_floor\": \"\", \"n\": \"\", \"p\": \"\", \"r\": \"\"}", "alignment_options": "{\"A\": \"\", \"B\": \"\", \"E\": \"\", \"E2\": \"\", \"O\": \"\", \"O2\": \"\", \"no_end_flt\": \"true\", \"s\": \"\", \"splicing\": {\"__current_case__\": 0, \"splice_mode\": \"preset\"}, \"z\": \"\", \"z2\": \"\"}", "io_options": "{\"K\": \"\", \"L\": \"false\", \"Q\": \"false\", \"Y\": \"false\", \"c\": \"false\", \"cs\": null, \"eqx\": \"false\", \"output_format\": \"BAM\"}", "chromInfo": "\"/srv/galaxy/var/tool-data/shared/ucsc/chrom/?.len\"", "dbkey": "\"?\"", "__input_ext": "\"input\""}, "inputs": {"ref_file": {"id": "f8c43d3bbbbdd9d4", "src": "hda", "uuid": "03b28af3-29db-4239-ad17-f7cf97fe1b36"}, "fastq_input1": {"id": "26d744393f4de250", "src": "hda", "uuid": "a6bcfc9b-54e2-458f-a455-0959a922c34a"}}, "outputs": {"alignment_output": {"id": "f29cf06d0c17115c", "src": "hda", "uuid": "311cac24-76c1-4fab-9d07-b01bc284009a"}}, "tool_stdout": "", "tool_stderr": "[M::mm_idx_gen::0.003*1.31] collected minimizers\n[M::mm_idx_gen::0.004*1.23] sorted minimizers\n[M::main::0.004*1.23] loaded/built the index for 1 target sequence(s)\n[M::mm_mapopt_update::0.004*1.23] mid_occ = 1000\n[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1\n[M::mm_idx_stat::0.004*1.23] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569\n[M::worker_pipeline::0.013*1.07] mapped 100 sequences\n[M::main] Version: 2.20-r1061\n[M::main] CMD: minimap2 -x sr -t 1 -a reference.fa /data/a/6/b/dataset_a6bcfc9b-54e2-458f-a455-0959a922c34a.dat\n[M::main] Real time: 0.022 sec; CPU: 0.014 sec; Peak RSS: 0.004 GB\n", "job_stdout": "", "job_stderr": "", "stderr": "[M::mm_idx_gen::0.003*1.31] collected minimizers\n[M::mm_idx_gen::0.004*1.23] sorted minimizers\n[M::main::0.004*1.23] loaded/built the index for 1 target sequence(s)\n[M::mm_mapopt_update::0.004*1.23] mid_occ = 1000\n[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1\n[M::mm_idx_stat::0.004*1.23] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569\n[M::worker_pipeline::0.013*1.07] mapped 100 sequences\n[M::main] Version: 2.20-r1061\n[M::main] CMD: minimap2 -x sr -t 1 -a reference.fa /data/a/6/b/dataset_a6bcfc9b-54e2-458f-a455-0959a922c34a.dat\n[M::main] Real time: 0.022 sec; CPU: 0.014 sec; Peak RSS: 0.004 GB\n", "stdout": "", "job_messages": [], "user_email": "admin@example.org", "job_metrics": [{"title": "Cores Allocated", "value": "1", "plugin": "core", "name": "galaxy_slots", "raw_value": "1.0000000"}, {"title": "Job Start Time", "value": "2021-06-08 13:26:47", "plugin": "core", "name": "start_epoch", "raw_value": "1623158807.0000000"}, {"title": "Job End Time", "value": "2021-06-08 13:26:50", "plugin": "core", "name": "end_epoch", "raw_value": "1623158810.0000000"}, {"title": "Job Runtime (Wall Clock)", "value": "3 seconds", "plugin": "core", "name": "runtime_seconds", "raw_value": "3.0000000"}]}, "output_problems": ["Output alignment_output:  different than expected, difference (using diff):\n( /tmp/tmpxrgqnmzyminimap2-test1-fasta.bam v. /tmp/tmpanitowyxminimap2-test1-fasta.bam )\nBinary data detected, not displaying diff"], "status": "failure"}}], "galaxy_url": "https://gat-3.oz.training.galaxyproject.eu"}
Traceback (most recent call last):
  File "/usr/local/bin/galaxy-tool-test", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/verify/script.py", line 364, in main
    run_tests(args)
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/verify/script.py", line 447, in run_tests
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/verify/script.py", line 281, in run_test
    verify_tool(
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/verify/interactor.py", line 1050, in verify_tool
    raise e
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/verify/interactor.py", line 1046, in verify_tool
    job_stdio = _verify_outputs(testdef, test_history, jobs, tool_id, data_list, data_collection_list, galaxy_interactor, quiet=quiet)
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/verify/interactor.py", line 1222, in _verify_outputs
    raise JobOutputsError(found_exceptions, job_stdio)
galaxy.tool_util.verify.interactor.JobOutputsError: Output alignment_output:  different than expected, difference (using diff):
( /tmp/tmpxrgqnmzyminimap2-test1-fasta.bam v. /tmp/tmpanitowyxminimap2-test1-fasta.bam )
Binary data detected, not displaying diff
```

**Comment by mvdbeek** [comment]
Ah, we probably need pysam here, so we can do diffs ...

**Comment by mvdbeek** [comment]
hmm, ephemeris in 0.10.6 should bring in pysam ... @hexylena can you check if pysam is installed ?

**Comment by hexylena** [comment]
It's on gat-3.oz.training.galaxyproject.eu if you want to test yourself as well.

```
ubuntu@gat-3:~/git-gat$ pip freeze | grep -i ephemeris
ephemeris==0.10.6
ubuntu@gat-3:~/git-gat$ pip freeze | grep -i pysam
1 ubuntu@gat-3:~/git-gat$ pip freeze | grep -i sam
1 ubuntu@gat-3:~/git-gat$
```

**Comment by hexylena** [comment]
manually added pysam and re-running the tests.

**Comment by hexylena** [comment]
yep, looks better with it installed.

```
Total run time: 0:00:00.807800
2021-06-08 13:36:34,017 INFO  - Storing log file in: /tmp/ephemeris_7_lhdxzw
2021-06-08 13:36:34,075 INFO  - Executing test 'minimap2/2.20+galaxy0-0'
2021-06-08 13:36:47,583 INFO  - Test 'minimap2/2.20+galaxy0-0' passed
2021-06-08 13:36:47,584 INFO  - Report written to 'standard output'
2021-06-08 13:36:47,584 INFO  - Passed tool tests (1): ['minimap2/2.20+galaxy0-0']
Failed tool tests (0): []
Skipped tool tests (0): []
Errored tool tests (0): []
2021-06-08 13:36:47,584 INFO  - Total tool test time: 0:00:13.543755
{"version": "0.1", "suitename": "Galaxy Tool Tests", "results": {"total": 1, "errors": 0, "failures": 0, "skips": 0}, "tests": [{"id": "minimap2/2.20+galaxy0-0", "has_data": true, "data": {"tool_id": "minimap2", "tool_version": "2.20+galaxy0", "test_index": 0, "time_seconds": 13.479611873626709, "inputs": {"reference_source|ref_file": {"src": "hda", "id": "93804190fda8c5e6"}, "reference_source|reference_source_selector": "history", "fastq_input|fastq_input1": {"src": "hda", "id": "f759543650b90f14"}, "fastq_input|analysis_type_selector": "sr", "fastq_input|fastq_input_selector": "single"}, "job": {"model_class": "Job", "id": "d8be473c4a72d2bb", "state": "ok", "exit_code": 0, "update_time": "2021-06-08T13:36:42.114938", "create_time": "2021-06-08T13:36:39.302316", "galaxy_version": "20.09", "command_version": "2.20-r1061\n", "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2/2.20+galaxy0", "history_id": "60bbf531cfac051f", "external_id": "342398", "command_line": "ln -f -s '/data/2/5/3/dataset_253c5c62-f7b9-4b72-9d30-8ea776110889.dat' reference.fa && minimap2 -x sr          -t ${GALAXY_SLOTS:-4} reference.fa '/data/8/d/b/dataset_8db0a983-c2e9-490c-a7e8-7f533fbb8b16.dat' -a | samtools sort -@${GALAXY_SLOTS:-2} -T \"${TMPDIR:-.}\" -O BAM -o '/srv/galaxy/jobs/000/9/outputs/galaxy_dataset_c29181ee-d6cd-4bd3-b4b3-c14f322e01ee.dat'", "params": {"reference_source": "{\"__current_case__\": 1, \"ref_file\": {\"values\": [{\"id\": 7, \"src\": \"hda\"}]}, \"reference_source_selector\": \"history\"}", "fastq_input": "{\"__current_case__\": 0, \"analysis_type_selector\": \"sr\", \"fastq_input1\": {\"values\": [{\"id\": 8, \"src\": \"hda\"}]}, \"fastq_input_selector\": \"single\"}", "indexing_options": "{\"H\": \"false\", \"I\": \"\", \"k\": \"\", \"w\": \"\"}", "mapping_options": "{\"F\": \"\", \"N\": \"\", \"X\": \"false\", \"f\": \"\", \"g\": \"\", \"kmer_ocurrence_interval\": {\"__current_case__\": 1, \"interval\": \"\"}, \"m\": \"\", \"mask_len\": \"\", \"max_chain_iter\": \"\", \"max_chain_skip\": \"\", \"min_occ_floor\": \"\", \"n\": \"\", \"p\": \"\", \"r\": \"\"}", "alignment_options": "{\"A\": \"\", \"B\": \"\", \"E\": \"\", \"E2\": \"\", \"O\": \"\", \"O2\": \"\", \"no_end_flt\": \"true\", \"s\": \"\", \"splicing\": {\"__current_case__\": 0, \"splice_mode\": \"preset\"}, \"z\": \"\", \"z2\": \"\"}", "io_options": "{\"K\": \"\", \"L\": \"false\", \"Q\": \"false\", \"Y\": \"false\", \"c\": \"false\", \"cs\": null, \"eqx\": \"false\", \"output_format\": \"BAM\"}", "chromInfo": "\"/srv/galaxy/var/tool-data/shared/ucsc/chrom/?.len\"", "dbkey": "\"?\"", "__input_ext": "\"input\""}, "inputs": {"ref_file": {"id": "93804190fda8c5e6", "src": "hda", "uuid": "253c5c62-f7b9-4b72-9d30-8ea776110889"}, "fastq_input1": {"id": "f759543650b90f14", "src": "hda", "uuid": "8db0a983-c2e9-490c-a7e8-7f533fbb8b16"}}, "outputs": {"alignment_output": {"id": "d8be473c4a72d2bb", "src": "hda", "uuid": "c29181ee-d6cd-4bd3-b4b3-c14f322e01ee"}}, "tool_stdout": "", "tool_stderr": "[M::mm_idx_gen::0.004*1.26] collected minimizers\n[M::mm_idx_gen::0.005*1.21] sorted minimizers\n[M::main::0.005*1.21] loaded/built the index for 1 target sequence(s)\n[M::mm_mapopt_update::0.005*1.21] mid_occ = 1000\n[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1\n[M::mm_idx_stat::0.005*1.20] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569\n[M::worker_pipeline::0.015*0.96] mapped 100 sequences\n[M::main] Version: 2.20-r1061\n[M::main] CMD: minimap2 -x sr -t 1 -a reference.fa /data/8/d/b/dataset_8db0a983-c2e9-490c-a7e8-7f533fbb8b16.dat\n[M::main] Real time: 0.023 sec; CPU: 0.015 sec; Peak RSS: 0.004 GB\n", "job_stdout": "", "job_stderr": "", "stderr": "[M::mm_idx_gen::0.004*1.26] collected minimizers\n[M::mm_idx_gen::0.005*1.21] sorted minimizers\n[M::main::0.005*1.21] loaded/built the index for 1 target sequence(s)\n[M::mm_mapopt_update::0.005*1.21] mid_occ = 1000\n[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1\n[M::mm_idx_stat::0.005*1.20] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569\n[M::worker_pipeline::0.015*0.96] mapped 100 sequences\n[M::main] Version: 2.20-r1061\n[M::main] CMD: minimap2 -x sr -t 1 -a reference.fa /data/8/d/b/dataset_8db0a983-c2e9-490c-a7e8-7f533fbb8b16.dat\n[M::main] Real time: 0.023 sec; CPU: 0.015 sec; Peak RSS: 0.004 GB\n", "stdout": "", "job_messages": [], "user_email": "admin@example.org", "job_metrics": [{"title": "Cores Allocated", "value": "1", "plugin": "core", "name": "galaxy_slots", "raw_value": "1.0000000"}, {"title": "Job Start Time", "value": "2021-06-08 13:36:39", "plugin": "core", "name": "start_epoch", "raw_value": "1623159399.0000000"}, {"title": "Job End Time", "value": "2021-06-08 13:36:41", "plugin": "core", "name": "end_epoch", "raw_value": "1623159401.0000000"}, {"title": "Job Runtime (Wall Clock)", "value": "2 seconds", "plugin": "core", "name": "runtime_seconds", "raw_value": "2.0000000"}]}, "status": "success"}}], "galaxy_url": "https://gat-3.oz.training.galaxyproject.eu"}
+ git checkout main
Previous HEAD position was 9539485 admin/singularity/0009: Update the job_conf.xml with singularity destination
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
```

**Comment by mvdbeek** [comment]
Working on a new release for ephemeris, which will then require pysam.

**Comment by mvdbeek** [comment]
Alright, https://pypi.org/project/ephemeris/0.10.7/ is out and does come with pysam as a dependency.

**Comment by hexylena** [comment]
fantastic!

still catching a couple more things, so, will merge after.

**Comment by hexylena** [comment]
```
+ git checkout cab4b092408b9caabcdfb103b11119a5104f340c
HEAD is now at cab4b09 admin/job-destinations/0014: Configure dtd in job conf
+ ./.scripts/7-job-destinations-test/3.sh
Traceback (most recent call last):
  File "./.scripts/7-job-destinations-test/run_test.py", line 22, in <module>
    assert gi.datasets.download_dataset(output_id).decode() == f"Running with '{N_THREADS}' threads\n"
AssertionError
```

**Comment by hexylena** [comment]
dunno what the real error is

**Comment by hexylena** [comment]
but at least it got to job 3! that's good.

**Comment by hexylena** [comment]
```
ubuntu@gat-3:~/git-gat$ ./.scripts/7-job-destinations-test/3.sh
Running with '2' threads
 Running with '1' threads
Traceback (most recent call last):
  File "./.scripts/7-job-destinations-test/run_test.py", line 23, in <module>
    assert gi.datasets.download_dataset(output_id).decode().strip() == f"Running with '{N_THREADS}' threads"
AssertionError
```

**Review by hexylena — APPROVED** [review]
Ok, this covers the rest, fantastic.

**Comment by hexylena** [comment]
We're done!

**Pull request merged**
