### PR TITLE
image11

### PR DESCRIPTION
**Pull request by Swathi266**
Suggesting to replace the existing tutorial image 11 with the suggested image

### CODE REVIEW

**Comment by shiltemann** [comment]
Hi @Swathi266 thanks for your PRs! If you could use the same filename for the image as was used in the tutorial previously, it will automatically be updated in the tutorial. (but let me know if you would like some help doing that)

**Comment by Swathi266** [comment]
I am not sure how and where to change the file name

**Comment by shiltemann** [comment]
@Swathi266 ok no worries, I can take care of it! :+1:

**Comment by Swathi266** [comment]
Ok. Thank you @shiltemann

**Comment by shiltemann** [comment]
@Swathi266 I have updated the image name to replace the old one. Do you know why the numbers are so different now? Perhaps @AnnaSyme can have a look to see if it makes sense to update this image?

**Comment by Swathi266** [comment]
@shiltemann Maybe its because it represents a unique identifier for each specific change?

**Comment by AnnaSyme** [comment]
thanks @shiltemann @Swathi266 I will take a look

**Comment by AnnaSyme** [comment]
could you tell me what tutorial this image is in? thanks! @shiltemann

**Comment by Swathi266** [comment]
@AnnaSyme Image after running velvet in the tutorial - https://training.galaxyproject.org/training-material/topics/assembly/tutorials/general-introduction/tutorial.html
Stats file

**Comment by AnnaSyme** [comment]
thanks @Swathi266 @shiltemann I think it's ok that the numbers are different, as it's just showing the top of the file, and overall the assembly is similar (or the same). If you wish to replace this image could I suggest also replacing the preceding image of the contigs file to match? as the top three contigs in that file are then represented as the top three lines in the stats file. Thanks!

**Comment by Swathi266** [comment]
@AnnaSyme Yes please.
https://github.com/galaxyproject/training-material/pull/5439

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
Thanks @Swathi266! And thanks for the review @AnnaSyme! :+1:

**Comment by Swathi266** [comment]
Thank you @shiltemann @AnnaSyme

**Pull request merged**
