### PR TITLE
Add <Ezichi-Fav> as contributor/ Updated all abbreviations on High throughput Molecular Dynamics and Analysi…  491a580 …s (Computational chemistry)

### PR DESCRIPTION
**Pull request by Ezichi-Fav**
I edited the Contributors.yaml file to add my details in preparation for my main contribution.

### CODE REVIEW

**Comment by bebatut** [comment]
Hi @Ezichi-Fav. Welcome to the GTN! Being on the contributor list is not a pre-requisite to contributing to the GTN.

So we do not add people to the contributor list until their first contribution to avoid inaccurately increasing our statistics. We will leave this pull request open until you make your first contribution and merge it then :)

If you are looking for ideas of how to contribute here, please take a look [at this issue with contribution ideas](https://github.com/galaxyproject/training-material/issues/2070), or have a chat with us on [Gitter](https://gitter.im/Galaxy-Training-Network/Lobby)/[Matrix](https://app.element.io/#/room/#Galaxy-Training-Network_Lobby:gitter.im) :)

**Comment by Ezichi-Fav** [comment]
Updated all comments on High Throughput Molecular Dynamics and Analysis (Computational Chemistry)

**Comment by Ezichi-Fav** [comment]
Updated all comments on High Throughput Molecular Dynamics and Analysis (Computational Chemistry)

**Comment by simonbray** [comment]
duplicate of https://github.com/galaxyproject/training-material/pull/2979

**Pull request closed without merging**
