### PR TITLE
Add video transcripts to plates, batches, and barcodes slide deck

### PR DESCRIPTION
**Pull request by mtekman**
Convert the Plates, Batches, and Barcodes slide deck into a video

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
This looks great! I love how easy it is

**Comment by mtekman** [comment]
https://training.galaxyproject.org/training-material/videos/watch.html?v=transcriptomics/tutorials/scrna-plates-batches-barcodes/slides

Is this video still being generated? I cannot get it to play in either Firefox or Chrome -- it mentions a missing key?

**Comment by hexylena** [comment]
Yeah, need to wait for https://github.com/galaxyproject/training-material/actions/workflows/video.yml to run again. looks like it'll go in a couple minutes.

**Comment by mtekman** [comment]
oh thanks!

**Comment by hexylena** [comment]
ping me if it doesn't show up after 14:30?

**Comment by mtekman** [comment]
working great, thanks!

**Pull request merged**
