### PR TITLE
Add mini-tutorial for group tags

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek we want to avoid images as much as we can. Can you maybe cut the image that only the select box is seen?

**Comment by bebatut** [comment]
@mvdbeek thanks a lot for this really nice and useful tutorial.
I did some formatting, let me know if they are ok for you

**Comment by mvdbeek** [comment]
sure, thanks, that looks good! I wanted to simply the wrapper a bit more, but it's good to have for now!

**Comment by shiltemann** [comment]
thanks @mvdbeek, this is great!

**Pull request merged**
