### PR TITLE
Initial draft for Singularity tutorial

### PR DESCRIPTION
**Pull request by torfinnnome**
More descriptive text is probably wanted.

### CODE REVIEW

**Comment by hexylena** [comment]
Hey @torfinnnome this looks like a fantastic start! I'll have some edits on top of this I'm sure, thanks for getting this started though. Did you have this re-setup on one of the GAT machines after I had to rebuild them?

**Comment by torfinnnome** [comment]
Yup, @hexylena, it's configured and running on gat-1.oz.training.galaxyproject.eu.

**Comment by hexylena** [comment]
perfect, i'll probably mess with that a bit ok? Just to get some of the outputs so students can confirm their commands are working correctly.

**Review by hexylena — APPROVED** [review]
I've commented out the CVMFS portion pending a response from @bgruening in Instructor chat, but this looks great so far.

I swapped to a golang role which should support more operating systems, I'm not sure debian/rhel all standardised their package names.

Additionally I merged in the environment variables as default since they don't hurt / they're important for admins to be aware of.

**Comment by bgruening** [comment]
I'm fine if we leave the CVMFS part out for now. It maybe adds too much complexity for the moment and we need to sort out our Stratum0 story as well.

**Comment by bgruening** [comment]
@torfinnnome thanks a bunch for taking the lead here and creating the tutorial. Very much appreciated!

**Pull request merged**
